### ISSUE TITLE
Kontakt: Posílání emailu

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#102]
Na front-endu bude formulář "Napište nám", který pošle e-mail na info@cestiadvokati.cz.
Potřebujeme POST endpoint na back-endu, který bude přijímat:
* tělo zprávy,
* e-mail odesílatele (v zadání není, teď nevím, jestli má být povinný),
* klíč vygenerovaný recaptchou.

**Comment by repli2dev** [comment]
Čeká na captchu ve větvi `wip-71-disputes`.

**Comment by repli2dev** [comment]
Větev je mergnutá do developu.
