### ISSUE TITLE
pozdější zveřejnění dokumentu u NSS

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#104]
Příloha dokumentu byla zveřejněna později, než v období zveřejnění metadat daného dokumentu.

Například v období 22. 3. - 28. 3. (1 běh crawleru)
je tímto případem dokument '7 Ads 35/2017 - 26'.
Příloha dokumentu se objevila až 29. 3.

**Comment by repli2dev** [comment]
- Je tam k dispozici čeho se lze chytnout? (nějaký příznak `modified` etc?)
- Nestačilo by posunout tu periodu dál do minulosti? Přeci jen stahovat věci takhle brzy možná nechceme?
