### ISSUE TITLE
Stejnojmenní advokáti

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#105]
hláška při vyhledání advokáta, který má v ČAK jmenovce (totožné jméno i příjmení)
> Vámi vyhledaný advokát má jméno i příjmení shodné s alespoň jedním dalším advokátem. Jeho statistiky tedy mohou být nepřesné. Přečtěte si, proč tomu tak je [odkaz na “O projektu - Způsob zpracování”].

@tpapouskova Nemělo by se to zobrazit spíše v detailu advokáta? Protože když dám vyhledávat, bude celkem jasné, že je tam více advokátů stejného jména.

@repli2dev Mám dojem, že v případě detailu advokáta nebudu potřebovat něco z back-endu

**Comment by tpapouskova** [comment]
Do detailu advokáta, ok, určitě.
ALE
Ještě se nad tím zamysleme - protože my už nějaké statistiky zobrazujeme ve
výsledcích vyhledávání a někteří lidé si třeba detail advokáta ani
nerozkliknou, možná bych to dala i sem.

Dne 7. dubna 2017 10:10 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
@repli2dev Potřebuju v detailu advokáta (https://devel.cestiadvokati.cz/api-doc/Advocates.5.php) posílat informaci, že advokát má jmenovce.

Rád bych tam dal nějakou možnost na ty jmenovce prokliknout -- buď přímo přes id advokáta a nebo na search obrazovku pro dané přesné jméno (tam je problém, že fullname, které dostávám, obsahuje i tituly).

**Comment by repli2dev** [comment]
@tomvej máš to v detailu advokáta... matchuje to všechny jména advokáta X (tedy včetně historických) proti všem jménům ostatních advokátů (včetně historických) + se zobrazují aktuální jména. Takže může nastat situace, kdy tam uvidíš pro osobu X jméno Y, pokud X se jmenovala Y, nebo Y se jmenovalo X.

Druhá věc je, že to matchování je bez titulů, jen jména. (Matchování od soudů je povětšinou ale prefixové, nepletu-li se.)

@tpapouskova ve vyhledávání to chce probrat. Těžko říct jakou by to mělo mít formu zde... možná indikace u konkrétního advokáta (boxu), že výsledek může být fuzzy, protože k danému advokátu jsou stejně jmenující se? (+ "viz detail").

**Comment by tomvej** [comment]
Je to tam.

@repli2dev : Možná by bylo fajn posílat ještě sídlo, protože teď jsem to zkoušel a výpis stejnojmenných advokátů:
* JUDr. Jiří Novák
* JUDr. Jiří Novák

Což vypadá vtipně.

**Comment by repli2dev** [comment]
@tomvej Máš to tam.

**Comment by tomvej** [comment]
@repli2dev Díky.

A je tam rezidence -- dal jsem tam jen město, ale myslím, že se to podstatně zlepšilo. Smutné je, že JUDr. Jiří Novák a JUDr. Jiří Novák sídlí ve stejné budově, asi by si s nimi někdo měl promluvit, že nám kazí UI.
