### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#106]
Na frontend chceme před veřejným spuštěním dostat GA abychom mohli sledovat co se bude dít.

**Comment by tomvej** [comment]
* https://developers.google.com/analytics/devguides/collection/analyticsjs/
* https://github.com/react-ga/react-ga
* https://web-design-weekly.com/2016/07/08/adding-google-analytics-react-application/
* http://stackoverflow.com/questions/34836500/how-to-set-up-google-analytics-for-react-router

**Comment by tomvej** [comment]
Zároveň to znamená, že musíme naimplementovat cookie disclaimer. Vidím to jako:
1. Popup nahoře (ve stylu d20.cz).
2. Nějaký odstavec v sekci o projektu.

**Comment by repli2dev** [comment]
Nemyslím si: http://www.vzhurudolu.cz/blog/36-eu-cookies

**Comment by tomvej** [comment]
Ah, tím se to trochu zjednodušší.

**Comment by tomvej** [comment]
Tak se mi něco podařilo nastavit. Je to tak, že analytika se nesleduje na devserveru (npm start), jen se vypisuje do konzole.

Otázkou je, co chceme sledovat.
* Čas uživatele na jedntlivých stránkách (samozřejmě).
* Load time aplikace (posílám to, ale zatím jsem na stránce analytiky neviděl výsledky).

Napadá mě pár věcí:
* kdy uživatel klikne na kontakt, ale nenapíše nám.
* kdy uživatel rozporuje, ale neodešle to.

**Comment by tomvej** [comment]
Ještě se dají sledovat load časy entit.

**Comment by tomvej** [comment]
Zatím jsem udělal úplně nejprimitivnější část -- stránky a load time. Jdou i ostatní věci, co jsem tu psal, ale znamenají trochu více práce, takže to chci nejdřív probrat.
