### ISSUE TITLE
Podbarvení detailu případu podle výsledku

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#109]
Na stránce advokáta by bylo fajn, kdyby se rámeček a footer podbarvil podle výsledku.

Je třeba připravit prototyp.

**Comment by tomvej** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Podbarvit rámeček případu podle úspěchu -- footer](https://trello.com/c/2ZEsPkVd/34-podbarvit-ramecek-pripadu-podle-uspechu-footer)

**Comment by tpapouskova** [comment]
Tohle mi stále připadá smysluplné, šlo by to?

**Comment by tomvej** [comment]
@xorelvistor Můžeš mi, prosím, poslat ty ikonky?

**Comment by xorelvistor** [comment]
@tomvej 
dal jsem je do složky `icons` na [GDrive](https://drive.google.com/drive/folders/0By2NMS-JnGIxZHVLNnJ1a0UyNHc), formáty PNG, SVG

**Comment by tomvej** [comment]
@repli2dev Nějak se nám na develu nezobrazují obrázky, i když ve `www/frontend/` jsou. Myslíš, že by to mohlo být něco s nastavením nginxu?

**Comment by repli2dev** [comment]
@tomvej Co tě přimělo generovat obrázky přímo do rootu (`/a07ced463ffebb82e82d847a4903b56d.svg`)? Taková nemůžu s daným `.htaccess` fungovat. Kdybys je hodil do `assets` složky (kam patří), tak by to mělo projít bez problémů.

**Comment by tomvej** [comment]
Přiměl mě webpack, který dává všechno na jednu hromadu. Nenapadlo mě,
že pro obrázky platí vlastní pravidla, každopádně, teď to vím. Podívám
se, jestli to půjdou do assets.

**Comment by repli2dev** [comment]
Ono by to šlo asi ohackovat skrze matchování přípon, ale tomu bych se rád vyhnul... a dělal to jen pomocí prvního adresáře.

**Comment by tomvej** [comment]
Ok, přesunul jsem to do `assets/webapp`. Zvláštní adresář to má z toho důvodu, že ho budu před buildováním promazávat.
