### ISSUE TITLE
Implementace crawleru pro stahování dat z Nejvyššího správního soudu

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#11]
- [ ] script, který je schopen v zadaném časovém intervalu stáhnout všechna dostupná rozhodnutí
- [ ] zdrojové kódy jsou dostupné v příslušném repozitáři

**Comment by papousek** [comment]
Nemůžu si pomoct, ale chybí mi tam nějaký requirements.txt, pomocí kterého bych nainstaloval potřebné závislosti.

**Comment by xorelvistor** [comment]
Mě taky...potřeboval bych ho vygenerovat. Nějaký vhodný a chytrý nástroj?

**Comment by papousek** [comment]
```
pip freeze > requirements.txt
```

**Comment by xorelvistor** [comment]
Tak už tam je requirements.txt

**Comment by papousek** [comment]
Díky! Zkusím si to u sebe rozjet.

**Comment by papousek** [comment]
@xorelvistor Supr. Všechno funguje. Jak dlouho ti trvá jeden běh?

**Comment by xorelvistor** [comment]
Když jsem stahoval kompletní databázi (2003-2016), tak to bylo 3-4 hodiny (bez stahování souborů rozhodnutí), s nimi pak kolem 10 hodin.
