### ISSUE TITLE
Datum rozhodnutí v případech advokáta

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#114]
Potřeboval bych posílat datum rozhodnutí v případech advokáta, aby se dalo zobrazit na front-endu.

**Comment by tomvej** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [datum rozhodnutí v detailu případu](https://trello.com/c/02WHMRjY/30-datum-rozhodnuti-v-detailu-pripadu)

**Comment by repli2dev** [comment]
Hmm, momentálně v databázi žádné takové datum nemáme. Na případu ho můžu založit, otázkou je, jak by se mělo plnit (ideálně z oficiálních dat). Na dokumentu momentálně též není, tam ale má jiný význam -- je to datum daného konkrétního rozhodnutí spjatého s tím dokumentem.

**Comment by tomvej** [comment]
Jo, to je důvod, proč jsme to předtím neimplementovali. Čistě
sémanticky, není datum rozhodnutí datum posledního rozhodnutí z
dokumentů případu?

**Comment by repli2dev** [comment]
V obecnosti není... A. nedořešené případy by pak měly datum rozhodnutí jen proto, že bylo vydáno nějaké předběžné rozhodnutí netýkající se výsledku. B. dořešené případy by měly špatné datum, protože po finálním rozhodnutí občas přicházejí opravná rozhodnutí (aka typo...).

**Comment by tomvej** [comment]
Já věděl, že jsem něco zanedbal...

______________________________________________________________

**Comment by tpapouskova** [comment]
V databázi decision_date už máme. Navrhuji postupovat takto:

- Radime, Ty bys měl být schopen tento sloupec naplnit bez problémů. Jde o datum rozhodnutí u dokumentu, který používáš pro taggování výsledku.
- Tome, Ty bys tím pádem mohl toto datum na stránku případu vložit. U NSS a ÚS bude po Radimově zásahu naplněno. U NS bude holt chvíli chybět.
- Honzo, u NS jsme se shodli, že od roku 2015 datum rozhodnutí už snad mít budeme od NS. Pokud to v naprosté většině případů bude datum rozhodnutí posledního dokumentu v daném případu, tuto heuristiku použijeme na předchozí roky.

**Comment by tomvej** [comment]
@repli2dev Nevíš, v jakém stavu je tohle? Mi na FE zatím nic nechodí.

**Comment by xorelvistor** [comment]
u NSS a ÚS již bylo naimplementováno, otázkou ale je, zda bylo upraveno API...to nevím.

**Comment by repli2dev** [comment]
@tomvej @xorelvistor ty sloupečky tam jsou (a zpřístupnil jsem je v API case a API advocate-cases), v některých případech (jako NSS a ÚS) jsou i naplněny, nedá se ale na to spoléhat, to že je tam null značí, že je buď nemáme (NS), že nebylo rozhodnuto.
