### ISSUE TITLE
Vyhledávání advokátů (neber lower case atp.)

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#117]
Nejsem si úplně jistá, jestli je tohle něco, co jste chtěli řešit / řešíte / jste se rozhodli neřešit.

Při zadávání jména advokáta jsem si všimla, že nelze zadat "šimáčková" (resp. to nevyhodí žádný výsledek), podobně bez výsledku zůstává "Simackova".

Tedy 2 věci.
- Chtělo by to, imho, zadané hodit to lower case a bez diakritiky a vyhledávat takto. Ale tuším, že tohle jsme s Honzou kdysi dávno řešili a on na to měl jiný názor.

- Chtělo by to nějakou hlášku typu "Omlouváme se, na základě Vašeho dotazu se nám nepodařilo najít žádného advokáta. Je možné, že jste se spletli [, zapomněli zadat jméno a příjmení advokáta ve správném tvaru (např. "Novák Jan")] nebo že Vámi hledaný advokát dosud nevystupoval v řízení před Nejvyšším soudem, Nejvyšším správním soudem ani Ústavním soudem."

(Pokud budeme chtít, aby uživatelé zadávali jméno a příjmení advokáta v určitém tvaru, navrhuji toto naznačit změnou šedého textu ve vyhledávacím rámečku na "Zadejte jméno (např. "Novák", případně "Novák Jan") nebo IČ".)

**Comment by tomvej** [comment]
Jo, s hláškou "Nikoho se nepodařilo najít" do budoucna počítám -- nejspíš to budu řešit v rámci #81.

Z uživatelského hlediska dává smysl minimálně to nemít case sensitive -- a asi by byly fajn i ty háčky a čárky. Jako že Češi jsou, co se týče formy psaní na netu, dost hovada, ale myslím, že nemá cenu snažit se je vychovávat. :)

**Comment by repli2dev** [comment]
Bylo by fajn, kdyby to umělo case insensitive a accent insensitive search, implementovat to ale není úplně jednoduché, protože databáze to by default nějak vhodně neumí.

**Comment by tomvej** [comment]
Samozřejmě netuším, jak to máme naimplementované, ale kombinace tohohle
by nefungovala?

http://stackoverflow.com/questions/7005302/postgresql-how-to-make-case-
insensitive-query
https://www.postgresql.org/docs/current/static/unaccent.html
Samozřejmě, musíš udělat index nad lower(unaccent(NAME)).

**Comment by repli2dev** [comment]
O tom víceméně umím, ale ony jsou to jen roztroušené funkce, které se musí ještě poskládat tak, aby fungovaly...

**Comment by repli2dev** [comment]
Provedeno, zatím jednoduše pomocí funkce unaccent, bez speciálních indexů (nezhoršuje to složitost), index je v momentálním setingu neproveditelný... Like v PostgreSQL neumí uplně používat indexy, unaccent neumí být použitý v indexu, protože funkce není immutable, dokonce ani concat není immutable...

Jinak řečeno, třídu složitosti to nezhoršilo, takže to budeme řešit (pravděpodobně full-text search), až to bude problém.
