### ISSUE TITLE
Odstranit rámeček okolo "Dokumenty" v detailu případu

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#118]
...rámečky jsou jinde používány jako klikací dlaždice, tu ne, tož bych ho dala pryč

**Comment by tomvej** [comment]
Jo, tady s tím jsem nějakou dobu pracoval a rámeček se mi zdál nejlepší, když jsem zvážil ostatí možnosti:
https://drive.google.com/open?id=0By2NMS-JnGIxV2pSU1pNamNVdHc
https://drive.google.com/open?id=0By2NMS-JnGIxWUlmdk5LZjRiYm8

**Comment by tpapouskova** [comment]
Mně ta první (bez čáry pod nadpisem) rozhodně přijde nejlepší.

2017-04-22 14:56 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:
