### ISSUE TITLE
Odstranění rozhodnutí do určitého data (jiné pro různé soudy) z databáze

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#119]
Při prohlížení statistik úspěšnosti taggování jsem si všimla, že v databázi zjevně máme a zpracováváme i rozhodnutí, která bychom neměli - jde o to, že jsme se rozhodli pro NS a NSS zpracovávat rozhodnutí od určitého roku, kdy nám soudy zaručily, že jsou všechna z daného roku dostupná.

Konkrétně:
- Nejvyšší soud: Konečná rozhodnutí o dovoláních v občanskoprávních věcech (rejstříky Cdo, Cdon, ICdo, NSČR, Odo, Odon) vydaných po 1. 6. 2000 a v trestněprávních věcech (rejstřík Tdo) vydaných po 1. 1. 2002.
- Nejvyšší správní soud: Konečná rozhodnutí o kasačních stížnostech (rejstříky As, Ads, Afs, Ars, Azs) vydaná po 1. 1. 2006.

Pro NS se nyní v databázi nachází i rozhodnutí z 1998 a 1999 (sice tam taggování neuspělo, takže to z hlediska počítání statistik nevadí, ale stejně bych je odstranila).

Pro NSS se v databázi nachází i rozhodnutí z 2003-2005.

Myslím, že o omezení crawlerů na tato data jsme se spolu bavili, takže chyba u NSS bude imho spíše v tom, že se na výše uvedená data neomezilo nahrávání dat získaných z tabulky od soudu (žádala jsem ještě dříve, než jsem zjistila, že to budeme chtít až od 2006, a tudíž v poskytnuté tabulce jsou rozhodnutí od počátku činnosti NSS). U NS bude problém asi v nesmazání dříve nacrawlerovných rozhodnutí...

Co se pak týče ÚS, tam by bylo dobré mít od 1. 1. 2007 jen konečná rozhodnutí o ústavních stížnostech. V žádosti o informaci toto omezení uvádím, takže by bylo jen dobré ověřit, že je obsaženo v crawleru.

Půjde to?

**Comment by tpapouskova** [comment]
Omezení přepsáno (relevantní hlavně pro Honzu).

- Nejvyšší soud: Konečná rozhodnutí o dovoláních v občanskoprávních věcech (rejstříky Cdo, Cdon, ICdo, NSČR, Odo, Odon) **podaných** po **1. 1. 2001** a v trestněprávních věcech (rejstřík Tdo) **podaných** po 1. 1. 2002.
- Nejvyšší správní soud: Konečná rozhodnutí o kasačních stížnostech (rejstříky As, Ads, Afs, Ars, Azs) **podaných** po 1. 1. 2006.

Radime, v zájmu konzistence bude třeba, abys trochu poměnil crawler. Teď asi zaklikáváš, že se mají stahovat rozhodnutí o ústavních stížnostech vydaná (**Datum rozhodnutí**) po 1. 1. 2007 a rozhodnutí bez omezení (tj. nejen ústavní stížnosti) vydaná do 31. 12. 2006. Bylo by ale dobré, abys zaklikával, že se mají stahovat rozhodnutí o ústavních stížnostech podaných (**Datum podání**) po 1. 1. 2007 a rozhodnutí bez omezení (tj. nejen ústavní stížnosti) o věcech podaných do 31. 12. 2006. Navrhuji takto crawler upravit a staženým datovým souborem přemazat ten stávající (a zajistit, že se k tomu nově staženému datovému souboru správně přijoinují data od ÚS ohledně advokátů a že se nový soubor správně otagguje Tvým algoritmem taggování výsledku). Dává Ti to smysl?

**Comment by xorelvistor** [comment]
@tpapouskova 
#### Nejvyšší správní soud
- formulář pro vyhledání umožňuje určení typu data jako **rozhodutí** nebo **napadení**
- v současné stavu je volba ponechána na defaultní hodnotě, což je **rozhodnutí**
Jak jsem psal již v issue #90 nezaznamenal jsem rozdíl při použití té či oné volby. Takže jestli tomu správně rozumím, měl by se využít přepínač **napadení** ať už funguje či ne. :-)
#### Ústavní soud
- v současné době je pro vyhledávání využito **datum zpřístupnění**, jehož změna již byla předmětem nějaké jiné issue.
Nejsem si jist, zda část o _rozhodnutí bez omezení_ lze nějak transformovat do voleb formuláře. Nebo je to jen formalismus? Asi bych si to potřeboval ujasnit - ideální by byl snímek obrazovky s vyplněným formulářem dle požadovaných kriterií.
Co přesně je myšleno _datovým souborem_, soubor s daty (CSV)?

**Comment by repli2dev** [comment]
V rámci tohoto tasku zřejmě naimplementuji omezení případů pro portál českých advokátů, které zobrazí jen spisovky podané až od určitých roků (mající v sobě rok), tak jak mi to specifikovala Terka. Ostatní data v systému být mohou, ale nebudou vstupovat do statistik, ani nebudou na portále viditelné (protože by zkreslovali statistiky).

**Comment by repli2dev** [comment]
@tpapouskova začal jsem to implementovat, narazil jsem u NSS na spisovku `aps`, `aos`, `ans` o kterých nemluvíš, co s nimi? Jinak tahle filtrace vytřídí cca 13000 případů.

**Comment by repli2dev** [comment]
@tpapouskova protože jsem nenašel žádné zmínky o daný spisovkách v e-mailech, githubu atp., prozatím předpokládám, že je nechceme.

@xorelvistor @tomvej @papousek @tpapouskova 
Zařídil jsem nový pohled `vw_case_for_advocates`, obsahuje jen ty případy, které jsou relevantní pro portál českých advokátů (dle Terčiné specifikace)... A API dotazy (vyhledávání, statistiky,...) už se přes něj filtrují (stačí ho `JOIN`out). Administraci upravím v rámci #93.

**Comment by tpapouskova** [comment]
Ad "aps" "aos" a "ans" u NSS - musí jít o dříve používané rejstříkové značky, které už teď nepoužívají.

Ale když se dívám na rozhodnutí v těchto rejstřících, jsou pro nás relevantní. Prosím tedy o zahrnutí i těchto rejstříků, je-li to realizovatelné, a v tomto smyslu měním relevantní část textu "O projektu".

**Comment by xorelvistor** [comment]
rejstříky zařazeny
