### ISSUE TITLE
Nasazení crawleru pro stahování dat z Nejvyššího správního soudu

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#12]
- [ ] nainstalovat všechny potřebné závislosti na virtuální server
- [ ] zapojit script do systému, aby se data nahrávala do databáze

**Comment by xorelvistor** [comment]
- [x] nainstalovat všechny potřebné závislosti na virtuální server

**Comment by xorelvistor** [comment]
@repli2dev 
Co všechno je pro to potřeba?
Napsat PHP skript spuštějící Crawler a přidat záznam o crawleru do DB? Nebo ještě něco?
Ještě mě napadá, jak se bude řešit spuštění daného virtuálního serveru pro danný crawler, součást příkazu v PHP?
A co (a kde) je potřeba nastavit pro automatické spouštení crawleru a následný import?

**Comment by repli2dev** [comment]
Ano, stačí napsat skript, přidat správný záznam s názvem třídy do tabulky úloh. Spouštění toho crawleru pak realizuje CRON (viz pod `cestiadvokati.cz` příkaz `crontab -e`, kde už se inspiruješ u mých záznamů.

Nevím přesně co myslíš tím "pouštěním daného virtuálního serveru". Virtuální server je stroj samotný, ne? Nebo myslíš něco s Xkama?

**Comment by xorelvistor** [comment]
Díky, a ještě taková drobnost nasazení aktuální verze repozitářů na stagging prostředí se provádí jak?
Spuštením virtuálního serveru jsem měl na myslí ```virtualenv pro Python``` Papi jej tam nainstaloval kvůli lepší práci (a efektivitě?) na serveru.

**Comment by repli2dev** [comment]
@xorelvistor ad virtuální prostředí... tak to netuším, já to u svého neřeším -- mám jarko v repozitáři a pak ho jen spouštím. V tvém případě to do PHPka patří v případě, že to celé je tak nějak sebeudržovací. Naopak by to tam nepatřilo, pokud "hotovou" instalaci crawleru dodáváš (a garantuješ) zvenku.

Nasazení staging by se měl provádět `deploy-devel`.

**Comment by xorelvistor** [comment]
@repli2dev, @papousek 
Provedl jsem commit do ```win-develop-jobs```, ale po spuštění  ```deploy-devel```  se poslední soubory (mnou commitnuté) neobjevily. Kde dělám chybu?

**Comment by repli2dev** [comment]
@xorelvistor chyba je v tom, že `wip-develop-jobs` je pracovní větev, která už byla mergnuta do `develop`u, ze které `deploy-devel` nasazuje.

**Comment by papousek** [comment]
@xorelvistor Ahoj. Nevidim v databazi advokati-devel (pod uzivatelem "advokati-ro" zadne dokumenty k NSS.

**Comment by xorelvistor** [comment]
pravidelný běh je nastaven  na úterý a import na středu, takže pokud budou nová data, objeví se tam. Stejně tak i u ÚS.

**Comment by papousek** [comment]
Nešlo by to spustit dřív, abychom zjistli, že to funguje?

**Comment by xorelvistor** [comment]
@papousek stalo se
crawler NSS  hh:15, import hh:20
crawler ÚS hh:25, import hh:30

**Comment by papousek** [comment]
@xorelvistor Neni divne, ze pro Ustavni soud to do databaze nic nenahralo?

@repli2dev @xorelvistor Jaktoze je v databazi tak malo dokumentu, viz tento dotaz:
```
SELECT court_id, COUNT(1) FROM document GROUP BY 1
```
vrati
```
court_id	count
2	        224
1        	39
```

**Comment by xorelvistor** [comment]
@papousek  Od počátku října nemá zatím ÚS žádné nové rozhodnutí, tudíž se nic neimportovalo. Crawler byl spuštěn až nějakého 10. října. Crawler NSS také běží jen krátkou dobu a data v databázi jsou zatím jen nová. Mám provést ruční import starších dat?

**Comment by papousek** [comment]
@xorelvistor Bylo by to fajn. Ať vidíme, že to funguje.
