### ISSUE TITLE
Obarvení 2 slov v průvodním textu na Home

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#120]
Bylo by super obarvit v textu na home - viz aktuální verze na GH - slovo NEMERITORNĚ červeně a slovo MERITORNĚ zeleně. Papi zkoušel ohackovat (viz ta aktuální verze), ale možná Tě napadne lepší řešení...

**Comment by tomvej** [comment]
Což nebude fungovat, protože jsem z bezpečnostních důvodů zakázal použít plain HTML v markdownu. Oops. :) Navíc to vypadá, že náš parser to nedává (otestováno): https://github.com/rexxars/commonmark-react-renderer/issues/9 Takže i kdyby nešlo o bezpečnost, inline html nedáme. Problém je, že se vždycky posunujeme na škále mezi rich textem a možností přeložení -- čím víc si budeme vymýšlet, tím hůře se to bude překládat.

První možnost je přepsat to do komponenty, tzn. text by se musel rozsekat na jednotlivé části (pět). To asi nedává smysl.

Druhá možnost je upravit parser tak, aby slova "nemeritorně" a "meritorně" (plus varianty) vyhledával a barvil je, pokud to bude omezený počet slov nebo výrazů (nejlépe vyhledatelných regexem), jde to udělat vcelku rychle.

Třetí možnost je najít jiný markovací jazyk. Je ale celkem těžké najít takový, který bude dostatečně jednoduchý (a bezpečný), ale zároveň bude provádět takové zhůvěřilosti jako barva (jako že nic proti, ale zvýraznění slov barvami je dost ... netypografické).

**Comment by tpapouskova** [comment]
Já vím, obarvování textu je zlotřilost, v našem případě to ale bohužel dává
dost smysl.

Jsem pro 2. řešení a díky za něj!

Dne 22. dubna 2017 14:38 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Uh. No, to bylo trochu těžší než bych očekával. Je to ještě trochu jinak -- nakonec obarvuju věci mezi dvěmi + zeleně a mezi dvěmi - červeně, takže se to dá použít na více místech.

Je to ale dost hack -- spoléhá to na to, že je to až ten nejspodnější stupeň formátování -- tj. uvnitř už nebude bold, italics, link, ani nic podobného. Ještě jsem tam dal escapování, tzn. `\+` a `\-` by se mělo zobrazit jako + a -.

P.S. VERZÁLKY taky nejsou úplně dobrý způsob jak něco zvýraznit, lepší je **tučné písmo**.
