### ISSUE TITLE
Udržet zascrolování při klikání na filtry v sekci "Případy"

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#122]
Teď, když kliknu na nějaký filtr, se stránka vyscroluje zase úplně nahoru, takže abych viděla výsledky, filtrování, musím opět scrolovat dolů...

**Comment by tomvej** [comment]
Okay, to bude velmi vtipné na opravu. Problém je, že v okamžiku, kdy změním filtr, se vymažou případy, které tam už jsou. Tím se zkrátí stránka, tzn. posune se scroll nahoru. Pak se tam objeví případy, ale scroll už se nevrátí.

Víceméně vidím dva způsoby:
1. V okamžiku, kdy se načtou první případy, zascrollovat na vrcholek případů (tzn. filtr soudů). Bude to vypadat trochu nepřirozeně, protože to bude se zpožděním až po načtení případů, ne na kliknutí na filtr
2. Nějak záměrně prodloužit stránku, aby se to nevyscrollovalo zpátky. Trochu tam pomůže, že se přidá nějaký loading indicator, ale prostě se tam bude muset přidat prázdný div. Nebo zachovat předchozí případy, ale to není úplně ideální, když už je změněn filtr.

**Comment by tpapouskova** [comment]
Abych se přiznala, naprosto nedokážu posoudit výhody a nevýhody Tebou
navrhovaných alternativ, tudíž to nechávám zcela na Tvém úsudku.

Dne 30. dubna 2017 21:47 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by xorelvistor** [comment]
Filtrování je stejně jen možné při viditelnosti prvku filtru nebo grafu, takže je podle mě korektní zascrollovat na filtry.  Mě se v některých případech zaskrolluje na případy, ale asi se toto chování odvíjí od počtu zobrazených případů v daném filtru. A nemohlo by to nějak vyřešit přichycení filtrů při scrollování, což by ti umožňovalo použít filtry kdykoliv a kdekoliv? Třeba v liště redukce grafu na select?
Jen přemýšlím....:-)

**Comment by tpapouskova** [comment]
Tohle už je hotovo, není-liž tak?

**Comment by tomvej** [comment]
Není, chrome to nějak dělá sám od sebe. Ve firefoxu ještě nefunguje.

______________________________________________________________
