### ISSUE TITLE
Skóre advokátů na úvodce

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#125]
Trochu se toho bojím, ale asi to bez toho bude bezzubé. Zkoušela jsem dotaz nad databází (na GoogleDrive) a docela zajímavé výsledky to háže.

Na úvodku by to chtělo dát žebříčky advokátů (asi bych tam dala vedle sebe 2, advokáti s největší převahou meritorních rozhodnutí nad nemeritorními a naopak a nad to možnost dát to jen na jednotlivé soudy, tedy v podstatě stejný filtrační mechanismus, jaký teď máme na stránce advokáta). + Odkaz na podstránku, kde zveřejníme data ke stáhnutí a výhledově možná i nějaké další žebříčky (něco jako cestiadvokati.cz/analytika).

Samostatnou otázkou pak je, zda pořadí advokáta v daném žebříčku budeme zveřejňovat i přímo na jeho stránce. Obecně by to asi smysl dávalo.

**Comment by repli2dev** [comment]
Chápu-li tvou poptávku správně tak chceš aby se pro každého advokáta vzal počet meritorních a nemeritorních a spočítalo se `M/(M+N)`, tedy například `10/(10+5) = 66.6 %` a toto skóre advokátů se pak seřadilo sestupně (a to jak celkově, tak po jednotlivých soudech).

Technicky je to proveditelné (i když ty dotazy mohou být výkonnostně náročné), ale vidím zde následující problém: skóre je spočítáno z nepřesných dat (ne všechny případy jsou otagovány, ne všichni advokáti mají vůbec nějaký případ, protože nebylo vše správně otagováno)... a tedy zobrazovat "přesné" pořadí je zavádějící. Chtělo by se to zamyslet jak do toho zahrnout nejistotu daného skóre.

**Comment by tpapouskova** [comment]
Je to trochu jinak. Kdybychom to totiž počítali na %, pak bys měl jako
"nejlepšího" advokáta toho s jednou podanou a zároveň meritorně projednanou
věcí. Jako klient ale hledáš advokáty, kteří mají nejvíc meritorních
zkušeností. Tedy myslela jsem M - N.

Chápu, že nemáme přesná data. Sama jsem dost zvažovala, jestli žebříčky
zařazovat. Ale pak jsem se koukla na M - N u advokátů a zjistila, že
rozdíly jsou mnohdy tak velké, že snad i při nedostatku dat odráží nějakou
zprávu o skutečnosti.

Dne 1. května 2017 10:18 Jan Drábek <notifications@github.com> napsal(a):

**Comment by tomvej** [comment]
@repli2dev Mám drobný problém s řazením -- bavili jsme se, že to budeme řadit podle příjmení. Jenže, já dostanu celé jméno i s balastem (tituly), takže máme možnosti:
1. Budu to řadit podle jména i s tituly.
2. Zkusím nějaký spešl regex na odstranění titulů, který nebude 100% spolehlivý.
3. Budeš mi posílat příjmení zvlášť.
4. Bude se to řadit na BE (po aplikaci stránkování).
5. Nebudu to řadit.

Co dává největší smysl?

**Comment by tpapouskova** [comment]
@tomvej Chapu, ze jde o neuzavreny proces, jen ale jiz v teto fazi signalizuji, ze si asi bude potreba nejak pohrat s uvodkou... Ty zebricky by rozhodne mely byt az pod tim textem.

Muj navrh. Z sedeho pole uplne vyhodit nyni vlastne zbytecne obrovsky nadpis "Cesti advokati.cz" a text, ktery je ted uplne na konci stranky, hodit do toho sedeho ramecku pod vyhledavaci pole. A zebricky pak nechat pod tim sedym rameckem (a nad ne jeste hodit to preklikavatko na jednotlive soudy, viz vyse). No a vzhledem k tomu, ze jsou ty zebricky tak uzke, mezi ne bych dala jeste prostym textem vysvetleni, jak jsem k nim dosli ("Spocitali jsme pro vas, kterych 10 advokatu ma nejvetsi prevahu meritornich konecnych rozhodnuti nad nemeritornimi a naopak. Upozornujeme ovsem, ze data, ktera jsme pro vypocet pouzili, nemusi byt uplna [odkaz na "O projektu"]."

**Comment by tomvej** [comment]
Díky za feedback, tady jsem si nebyl úplně jistý, budeme to muset ještě domyslet. Ne všude ale souhlasím.

1. Nadpis by tam někde měl být.
2. Text zkusím přesunout, uvidíme co to udělá.
3. Idea je, aby úvodka byla co nejjednodušší, tzn. pokud možno žádné přepínání. Pokud tam chceme přepínání, je lepší rovnou založit stránku žebříčky (a kliknutí na advokáta člověka nepřenese na advokáta ale na stránku žebříčků).
4. Doprovodný text zkusím doplnit.
Oukej, vypadá to, že bychom měli příští schůzku věnovat grafice, tohle není jediný problém, který řeším.

**Comment by tpapouskova** [comment]
Hmm, jestli to není moc náročné, zkus to, moc prosím, udělat dle původního
návrhu. Když to bude vypadat fakt hrozně, samozřejmě ustoupím.

Dne 9. června 2017 8:37 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Zkusím. Přepínač teda ještě nepůjde, na to nemám data z BE.

**Comment by tpapouskova** [comment]
Btw. Kdyby šlo do schůzky dotáhnout ty navrhované grafické změny (část textu do barevného pole, část textu mezi ty dva rámečky, viz výše) bylo by to super (ať případně vidím, že na nich opravdu nemá smysl dál trvat).

**Comment by tomvej** [comment]
Zkusím to udělat. Ten text mezi sloupečky vypadá fakt blbě, takže mě nenapadlo to tam nechávat, ale ok, ještě to tam přidám. U textu v rámečku jsem se sekl na dvou věcech:
* nemůže to mít stejnou velikost jako text nad políčkem pro vyhledávání (bylo by to moc velké),
* modrá barva odkazů není vůbec dobrá na fialovém pozadí.
Obojí vyžaduje nějaký hack CSS, ale ok, pokusím se o to.

______________________________________________________________

**Comment by repli2dev** [comment]
@tomvej přidal jsem sloupec `sorting_name`, řazené je to ale zatím dle M-N (jako může to řadit i backend, ale nějak mi přijde, že pak je porušena ta logika toho co to dělá (stejně by to bylo až druhé řazení))

**Comment by tpapouskova** [comment]
Re-otvírám, protože se mi zdá, že jsme nedotáhli to přepínání žebříčků podle jednotlivých soudů. Já preferuji, aby bylo přímo na úvodce, pokud ho chceš dát jinam, potřebuji vidět návrh. Někde to ale být musí, protože je to dost relevantní.

**Comment by tomvej** [comment]
Kousavá poznámka: Kdy že chceme releasovat?

Na úvodce by ideálně nemělo být přepínání něčeho. Pokud chceme někde statistiky, měla by to být zvláštní stránka. Potřebujeme něco takového před releasem?

**Comment by tpapouskova** [comment]
Koncem července, stihne-li se grafika a dodá-li ÚS data obratem, jak
sliboval (a neshodí-li nám plány Úřad pro ochranu osobních údajů oznámením
povinností registrovat se jako správci osobních údajů, což probereme v
úterý a což by reálně release posunulo na konec srpna...).

Máš pravdu, tohle není prioritní, předpokládáme-li, že zhruba 2 týdny po
releasu necháme web běžet na zkoušku jen tak a masivně propagovat jej
začneme až poté. Spolu s vlnou masivní propagace by to tam ale už asi mělo
být...

Dne 15. července 2017 11:14 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tpapouskova** [comment]
Připomínám dohodnuté - že se na úvodku dají vedle sebe 3 tabulky, každá pro jeden soud, každá z půlky zelená a z půlky červená. (Lze tady počítat už jen prostou převahu M nad N, anebo klidně i zachovat stávající komplikovaný vzorec, protože vzhledem k rozdělení dat na 3 skupiny bude stejně házet naprosto stejné výsledky.)

Rovněž připomínám, že jde o provizorní řešení. V celkově nové verzi webu toto budeme řešit trochu jinak (bude tam víc různých žebříčků).

**Comment by tomvej** [comment]
Backend tohle ještě nepodporuje, přidávám @repli2dev

**Comment by repli2dev** [comment]
Připravil jsem na to backend ve větvi `wip-125-detailed-score`, předělal jsem (zpětně nekompatibilně) `/api/advocate-rankings/` tak, že nyní vrací pod klíči id soudů a pod nimi seznam s jednotlivými advokáty v daném decilu... aby se nemuselo klást 6 dotazů na žebříčky, ale jen 2... Navíc jsem přidal parametr `id_court`, kterým se výsledky omezí jen na konkrétní soud.

Nyní je to k pokračování na @tomvej.

**Comment by repli2dev** [comment]
Mergnuto + nasazeno, zavírám.
