### ISSUE TITLE
Barevnější design

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#126]
Slova dvou testerů - "proč je to šedé?". Prý by to chtělo dodat barvu, aby to přitáhlo pozornost. Já osobně ale fakt nevím, kam.

Napadlo mě jen obarvení horní lišty a rámečku na úvodní stránce (z šedé na nějakou právnicky modrou). Já osobně bych už nic dalšího nebarvila, ale nechávám na Tvé úvaze.

**Comment by tomvej** [comment]
Horní lišta asi není problém, i když nevím, jestli to až tak moc pomůže. Možná barevnější detaily -- vyhledávání podle mě nejde moc zlepšit. Ty ikonky by tomu mohly pomoct, zkusím udělat prototyp.

Pak by se to dalo celé ještě předělat do [material designu](http://www.material-ui.com/#/), což je dost práce.

**Comment by tpapouskova** [comment]
Nic, co představuje "dost práce" rozhodně nedělejme! Nejdřív to dostaňme do
spustitelné verze, pak sežeňme peníze a "dost práce" si nechejme až na
hraní na potom.

Dne 25. dubna 2017 9:10 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by repli2dev** [comment]
Já si myslím, že "proč je to šedé" se hlavně vztahuje na úvodní stránku a podbarvení hledacího boxu, ten bych změnil. (A možná bych to udělal dost podobně jako https://otvorenesudy.sk/.)

Dál by tomu za mě asi pomohlo:
1. Mít logo
2. Vhodné ikonky v textu (případně "motivační obrázky")

**Comment by repli2dev** [comment]
Mě šlo o provedení menu + jumbotronu.

**Comment by tomvej** [comment]
Začneme barvou lišty a jumbotronu -- zkusíme nějakou modrou nebo fialovou.

Ještě zkusím připravit prototypy ikonek v seznamech.
