### ISSUE TITLE
Rozporování finálních tagování

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#129]
- [x] Zařídit, aby nešlo rozporovat tagování, které je `is_final`.
- [x] Zpropagovat informaci o finálnosti tagování na frontend (2x).
- [x] Disablovat na frontendu radio tlačítka co rozporovat na základě informace z detailu případu.
- [x] Zobrazit na frontendu namísto tlačítka pro rozporování, tlačítko pro kontakt, pokud je alespoň jedno tagování finální.
- [x] Nezobrazovat tlačítko pro rozporování pokud jsou obě tagování finální.

**Comment by repli2dev** [comment]
@tpapouskova prosím o schválení navrženého řešení.

**Comment by tpapouskova** [comment]
Jsem jednoznačně pro.

Prostor pro zamyšlení vidím v případě, kdy bude jedno z taggování is_final a druhé ne (typicky si přečtu rozhodnutí a zjistím jeho výsledek, ale jméno advokáta tam třeba bude naprosto chybět). Navrhuji, aby prozatím nešlo rozporovat taggování, které je is_final v obou směrech (tedy je advocate is_final a zároveň case result is_final), a ty další dvě situace (buď advocate is_final a case result není nebo naopak) se zatím nechaly nedořešené (respektive se v nich systém choval stejně, jako když ani jedno není is_final).

**Comment by repli2dev** [comment]
@tpapouskova vzhledem k tomu, že systém umí rozporovat i samotný výsledek/advokáta nevidím v popsaném řešení nějakou výhodu.

Implementované řešení (momentálně na úrovni API) je takové, že můžeš nemůže rozporovat obojí, když je alespoň jedno final, ale jednu věc (advokáta/výsledek) samostatně rozporovat můžeš.

@tomvej zbytek úprav je na tobě... Rozpracované je to ve větvi `wip-136` (kvůli úpravě reportu chyb).
