### ISSUE TITLE
Zobrazit v detailu advokáta informace o M/N skóre daného soudu

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#135]
Další tip z uživatelského testování.

Pro úplnost bychom mohli někam dát informaci o tom, jakou část podání ten který soud zpracovává meritorně/nemeritorně/zastavením. Důvod je ten, aby případné negativní skóre advokáta u ÚS lidé nevnímali jako zas až takovou hrůzu v kontextu toho, že ÚS vlastně zas tak moc věcí meritorně nerozhoduje.

Úplně si nejsem jistá konkrétním zpracováním této připomínky. Asi bych někam dala časovou osu s překliky na jednotlivé soudy (vlastně to stejné, co máme na stránce advokáta, jen tam půjdou všechny případy s otagovaným výsledkem, bez ohledu na taggování advokáta). Ale kam? Na úvodku k těm žebříčkům advokáta? Nebo možná na stránku advokáta pod ta tři velká čísla s tím, že jak bude člověk překlikávat v časové ose mezi jednotlivými soudy, budou se mu pod časovou osou zobrazovat i skóre daného advokáta související s daným soudem (tohle bych asi preferovala...)?

**Comment by repli2dev** [comment]
@tpapouskova Mají se do výpočtu statistiky zahrnout i advokáti, u kterých nemáme nic? (Skončí prostředních decilech...) Hlavně je to asi otázka jestli vůči zobrazovanému pořadí/kvantilu. Kdybys někdy chtěla skutečně ukázat pořadí, tak pak by bylo zavádějící, respektive teď se ti do decilu vejde míň lidí.

**Comment by repli2dev** [comment]
Zatím jsem to udělal jen pro advokáty, pro které něco máme.

@tomvej je to ve větvi `wip-136`, přibylo nové pole v detailu advokáta a nový zdroj `/api/advocate-rankings/<decile>`

**Comment by tpapouskova** [comment]
Souhlas, pro advokáty, o kterých nemáme žádná data, to IMHO opravdu nemá
smysl dělat.

2017-05-06 14:40 GMT+02:00 Jan Drábek <notifications@github.com>:

**Comment by tomvej** [comment]
Ok, mám problém, nevím, kam to plácnout. Když se podívám na tu stránku (už je to na develu), nevím, kde a jak to zobrazit, protože se mi zdá, že už tak je toho tam dost. Leda že bychom ji celou nějak přeskládali. Ideálně se o tom můžeme ve středu pobavit.

**Comment by tpapouskova** [comment]
Já bych to dala v odstínech šedi inverzně k existujícím sloupcům
jednotlivých soudů a při najetí bych zobrazila vysvětlující text.

Btw. narazila jsem na anomálii - pána, co nemá u jednotlivých soudů napsaná
čísla https://devel.cestiadvokati.cz/advocate/13913 .

Dne 9. června 2017 8:40 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
To není vůbec špatná myšlenka.

Ha! Zajímavá je, že výšky sloupců jsou správné. Navíc, děje se to pouze sporadicky. Podívám se na to.

**Comment by tpapouskova** [comment]
Jen menší úprava názoru - možná by bylo lépe inverzní sloupečky (skóre jednotlivých soudů) dát spíše do velmi světlých (skoro až neviditelných) odstínů barvy webu (? purpurová), páč šedou už máme barvu u zastavených řízení, tak aby se to nepopletlo...

**Comment by repli2dev** [comment]
@tomvej máš to připravené.

Nakonec mi přišlo nelogické dávat to do detailu advokáta... Je to nezávislá věc... proto `/api/court-statistics/`.

**Comment by tomvej** [comment]
@repli2dev Honzo, prosím, nezavírej mi issue, když na nich mám ještě já nějakou práci, pak hrozí, že na ně zapomenu. Nebo mi vytvoř nové issue.

**Comment by tomvej** [comment]
@repli2dev Jo, dávát to na vlastní API je určitě dobrá myšlenka -- natáhne se to na začátku a konec. Ještě bychom mohli přejít na GraphQL, to by nám tyhle věci vyřešilo. :)

**Comment by tpapouskova** [comment]
Ještě moc prosím o jednu maličkost. Chtělo by to při přejetí myší nad těmi sloupečky zobrazit text "pro srovnání: podíl jednotlivých typů rozhodnutí ve všech rozhodnutích soudu (bez ohledu na advokáta)". Jinak uživatel naprosto netuší, na co to vlastně kouká.

**Comment by tpapouskova** [comment]
Hele, já tam pořád to vysvětlení nevidím a ani nevidím nové vypsané issue, které by to řešilo. Proč je tedy toto zavřené?

**Comment by tomvej** [comment]
Huh. Netuším, tohle zjevně zavřené nemá být. Já si říkal, že mi chybí něco, co jsem měl udělat.

**Comment by tomvej** [comment]
Nasazeno na devel
