### ISSUE TITLE
API: Správný kód HTTP

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#136]
Dle: http://stackoverflow.com/questions/942951/rest-api-error-return-good-practices

**Comment by repli2dev** [comment]
Za mě je to implementováno, nyní @tomvej, prosím oprav svoji implementaci. Minimálně oba zdroje související s disputací a odesíláním zprávy budou mít problém, protože `result` pole jsem rozdělil na `result` a `error`.

**Comment by repli2dev** [comment]
Najdeš to ve větvi `wip-136`, pak ji můžeš zamergovat.

**Comment by tomvej** [comment]
Zkoušel jsem to, e-maily se dají odeslat a stránka nezkolabuje při chybě. Takže to zamerguju, ať nemáme moc konfliktů a pak budu řešit zobrazení chyb (zatím se psaly od konzole).

**Comment by tomvej** [comment]
Whoo, ono se to uzavřelo. Zobrazení informace budu řešit v #133
