### ISSUE TITLE
Změny u ČAKu

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#139]
Web ČAKu prochází změnami, mění se tvary  URL, struktura HTML, způsob stránkování, zobrazuje jen 500 advokátů

**Comment by repli2dev** [comment]
Chápu to tak, že z vyhledávání jich nejde dostat více než 500?

**Comment by repli2dev** [comment]
Btw. hledání via příjmení funguje prefixově, takže teoreticky lze projít celou abecedu (bez háčků) a tam, kde počet výsledků překročí 500 rekurzivně opakovat dále.

**Comment by xorelvistor** [comment]
Namátkovým zkoušením abecedy (počáteční písmeno příjmení) jsem zatím nenašel případ, kde by počet výsledků byl větší než 500. Počet zobrazených záznamů na stránku lze upravit parametrem v adrese. Další co jsem vypozoroval je, že se vyskytují jen aktivní advokáti. Potřeboval bych si nějak ověřit, počty zobrazovaných advokátů ČAKu a naše (se stejným kriteriem), abych mohl říct, zda (ne)zobrazuje všechny advokáty a není jich více než 500. 
Když budete mít čas analyzovat změny společně se mnou, dost mi to pomůže.

Sice mám zas teď co psát do textu diplomky, ale moc času na úpravy do nové funkční verze nemám. :-)

**Comment by xorelvistor** [comment]
Tak se mi  podařilo pomocí prefixového vyhledávání vytěžit 11457 advokátů, což je o 22 více, než máme v databázi my (jen aktivní), což by mohl být ten přírůstek od doby, co ČAK crawler selhal (1 běh). Když už jsem byl v těch úpravách, tak jsem dopsal extrahování firmy a datové schránky. Novou verzi zatím ještě ladím...
Jak budeme řešit změnu remote-identifikatoru?

**Comment by tpapouskova** [comment]
Omlouvám se, že reaguji až nyní.

Osobně bych věci moc neuspěchávala, na stránkách ČAK stále visí varování o
nefunkčnosti vyhledávání (viz níže). Možná je tedy stávající stav je
dočasný. Na druhou stranu je ale dobře, že jsi to Radime již změnil, ono
podobné omezení by v budoucnu (nenastalo-li nyní) určitě nastat mohlo.

"*Vážení, *
*Seznam advokátů není v tuto chvíli plně funkční. Omlouváme se za vzniklé
technické potíže, na jejichž odstranění intenzívně pracujeme. V případě
nutnosti ověření si informací nás kontaktujte telefonicky na telefonních
číslech:*


*                                                               273 193
223                                                               273 193
220.Děkujeme Vám za pochopení."*

Dne 16. května 2017 2:08 Bc. Radim Jílek <notifications@github.com>
napsal(a):

**Comment by repli2dev** [comment]
Když jsme to začali řešit, tak tam varování ještě nebylo...  Pokud tam vydrží ještě tak týden-dva, bude relevantní dotaz co jim vlastně nefunguje (abychom na ty data náhodou nespoléhali) a kdy to tak vidí opravené.

**Comment by repli2dev** [comment]
Možná bych i ten crawler a import dat do té doby raději zastavil, co myslíte? @tpapouskova @xorelvistor ?

**Comment by tpapouskova** [comment]
Zcela souhlasím a dávám si poznámku, že jim mám za 14 dní kdyžtak napsat,
případně připomenout vám, že máte crawler opět spustit.

2017-05-18 10:46 GMT+02:00 Jan Drábek <notifications@github.com>:

**Comment by xorelvistor** [comment]
Já jsem změny zapracoval hlavně proto, abych mohl odevzdat "funkční" kód - jestli dojde na ukázku, bylo by krajně nepříjemné, kdyby skript spadl :-). Souhlasím s pozastavením stahování.  Ale stejně bude potřeba se zamyslet nad tím, jak nová a stará data skloubit dohromady. Časem... :-)

**Comment by xorelvistor** [comment]
commitnu upravenou verzi crawleru, ale zatim  ho nebudu spouštět

**Comment by xorelvistor** [comment]
tak co jsem koukal, ČAK už funguje bez omezení....jedinou změnou je nový stav "vytvořen", který ale nevím, co přesně znamená....upravil jsem tedy crawler ČAKu na dřívější chování (načtení všeho místo průchodu abecedou), ale s novou strukturou stránek.

**Comment by tpapouskova** [comment]
Super, díky moc!

Dne 17. července 2017 20:49 Radim Jílek <notifications@github.com>
napsal(a):

**Comment by xorelvistor** [comment]
upraven a rozšířen import advokátů (zatím nasazeno na produkci, tam ještě není co zkazit :-))
prosím @repli2dev, aby se podíval na řešení updatu `remote_identificator`  [583b99420c55e42ed249ff909d60dc460a17f4d1](https://github.com/datoszs/czech-lawyers/commit/583b99420c55e42ed249ff909d60dc460a17f4d1)

**Comment by repli2dev** [comment]
@xorelvistor okomentoval jsem daný commit.
