### ISSUE TITLE
Potvrzení rozporování na FE

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#140]
> Bavili jsme se o tom, že je potřeba udělat nějakou URL, která bude příjmat požadavky z backendu a pak dle toho frontend zareaguje, například:
> 
> Reset link -> redirect na stránku, která vyšle request s parametry email, key na API stránku potvrzení a reflektuje případnou odpověď.
> 
> Chtěli jsme to tak, aby backend nemusel znát formát odkazů frontendu.

**Comment by tomvej** [comment]
@repli2dev Úplně nerozumím tomu (a nepamatuju si jak jsme to řešili), že back-end nemusí znát formát odkazů front-endu. Jak si to představuješ?

Jako že třeba bude jen jeden link, na který se tyhle požadavky budou přeposílat a podle nějakého parametru front-end rozhodne, co všechno provést?

**Comment by repli2dev** [comment]
Představoval bych si to následovně.

- Backend vygeneruje odkaz na verifikaci jako <HOST>/link/<request>
- Frontend bude mít routu na adresu /link/<request> (request v base64).
- Frontend si rozbalí request do JSONu, kde najde parametry `type` a `params`.
- Frontend podle `type` určí, co má s žádostí o routování dělat.
- V případě, že `type` = `disputation-verification` s parametry (v `params`) `code` a `email`, pak se vyšle dotaz na API a zobrazí stránka s přeloženou odpovědí.

Přijde ti to takto rozumné?
Za mě v tom vidím výhodu, že je formát odkazů je zexplicitněn, tedy nebudu muset mít uvnitř realizace API natvrdo nastavenou adresu per jednotlivé linky do frontendu.

**Comment by tomvej** [comment]
Jo, takhle by to šlo. Osobně bych dal přednost třeba

<HOST>/link/<type>?<params>

Aby to bylo lépe čitelné, tj. params budou v query, že by to bylo pěkněji čitelné, na druhou stranu, pokud chceme potenciálně nějakou hlubší, tak to jak to říkáš je v pohodě. Navíc je to neprůhledné pro uživatele, což může být výhoda. Takže zatím počítám s tím, jak jsi to napsal.
______________________________________________________________

**Comment by tomvej** [comment]
@repli2dev Naimplementováno, zbývá napojit BE a otestovat.
Předokládám odkaz ve tvaru `/link/request`, kde `request` je JSON v base64 a má následující formát:
```
{
    "type": "disputation-verification",
    "params": {
        "code": ...,
        "email": ...,
        "id_case": ...,
    }
}
```
`id_case` je id rozporovaného případu a není povinné, ale kdyby to šlo, bylo by fajn, aby přišlo, protože pak zobrazím tlačítko "Přejít na stránku případu", které je dost užitečné, pokud se ti rozporování nepovede.

**Comment by repli2dev** [comment]
Implementováno včetně id_case, fungovalo mi to na lokále hezky.
