### ISSUE TITLE
Úvodka - vyladění

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#143]
Raději i touto formou shrnuji dohodnuté, aby to nezapadlo.

Jumbotron nahoře
- fialový s bílým textem, nebo světlejší pozadí
- vyhodit z něj odstavec "Zjistíte, kolikrát [....] statistiky počítáme." (nyní už je přepsaný, na GH jde o odstavec "U advokátů zobrazujeme[....] statistiky počítáme.")

Pod jumbotron
- umístit vyhozený odstavec (já jej pak ještě přepíšu a zkrátím)
- text "zastavení řízení" vybravit náležitou šedou
- pořešit odrážky (měly by snad vypadat dobře, ale chce to checknout)
- pozn. : tento odstavec dle domluvy přijde i na stránku s výsledky vyhledávání advokáta + by to chtělo nějak pořešit (třeba zobrazením při přejetí) i přímo na stránce advokáta, protože spousta lidí klikne přímo na advokáta v našeptávači a tenhle text tedy potřebují vidět na stránce advokáta

Pod text statistiky
- nejprve oddělit od odstavce výše nějakou linkou
- pak vložit text "Spočítali jsme pro Vás..." (tento pak ještě přepíšu a bohužel mírně prodloužím)
- pod to tabulky, které nebudou mít žádný header a budou řazeny ideálně podle příjmení

Pod statistiky ? jumbotron
-  prostě stejný nafialovělý blok jako je nahoře
- do něj text "Účelem tohoto webu není poskytovat právní služby, ani jejich poskytování zprostředkovávat. Web zpracovává data veřejných institucí. Za věcnou správnost těchto dat autoři webu nenesou odpovědnost. Způsob využití zde zveřejňovaných statistik je zcela v rukou uživatelů, autoři webu za něj nenesou odpovědnost."

**Comment by tomvej** [comment]
Disclaimer jsem nakonec dal do žlutého alertu, druhý jumbotron není vhodný. Ten odstavec s odrážkami je dost velký, nevím, jestli se dá dát i na dalš stránky -- každopádně jsem na to založil #145 .

K čertu, pořád nevím, co s těmi "Nejlepšími advokáty". Napadá mě "Naši nejoblíbenější advokáti", to by byl dobrý fór.

**Comment by tpapouskova** [comment]
Supr!

2 maličkosti
- věta "Pokud advokáta, jehož ... komory." patří pod vyhledávací okno do jumbotronu (výhledově od tam zmizí a nahradí ji odkaz na pokročilé vyhledávání podle sídla a zaměření).
- jména advokátů mi nějak připadají napsaná větším písmem než zbytek

**Comment by tomvej** [comment]
* Šedý text bych tam nedával, protože ve výsledku bude méně výrazný než černý text. To úplně nechceš.
* Díval jsem se, jména advokátů mají 14 px, stejně jako ostatní text na stránce. Za to určitě můžou ty tituly, které jsou verzálkami. :)
* Jo, ty nadpisy. Ještě napadlo "Nejúspěšnější podavatelé" nebo "Advokáti nejúspěšnější při podání". To by se ještě mohlo vlízt. Jinak zrušíme.
* Ten odstavec přesunu.

Budu muset vymyslet nějaký lepší způsob na i18n markdownu, nějak se nám to množí a mít na každý soubor vlastní md je trošku blbé, když je to malé. No jo, programmer's life.

**Comment by tomvej** [comment]
Text jsem přesunul. Je moc velký a má špatně barevný nadpis, ale nechci to řešit, dokud nedostaneme barevné schéma, protože to není jen změnit CSS a musel bych to potom dělat znova.

**Comment by tpapouskova** [comment]
Přesunutí textu nevidím (asi není nasazené). Nicméně existuje spousta dalších důvodů, proč toto nechat otevřené :)

- je třeba dát pryč ty nadpisy žebříčků, opravdu
- je třeba odstranit celý text "U advokátů zobrazujeme..." až po "jak přesně statistiky počítáme."
- ve vzniklém prázdném bílém prostoru pod jumbotronem připravit 3 sloupce, do nichž Ti v úterý dodám krátké problem-statementy (k nimž Ti dodám i delší povídání, na něž u jednotlivých problém-statementů bude vhodné odkázat třemi tečkami a zavěsit je někam na web)
- upravit text nad tabulkami (upravila jsem, jen je to třeba nasadit)

**Comment by tomvej** [comment]
Nadpisy už jsou pryč (to je tak, když nedělám deploy pro každé změně). Ok, můžeme to nechat otevřené, ale protože mě provokují issues, se kterými nemůžu nic udělat, tak se zatím odepisuju z assignees.

**Comment by tpapouskova** [comment]
Omlouvám se, ty problem-statementy asi dneska nedotáhnu. Snad ale správně
spoléhám na to, že by to pro Tebe stejně až do pátku nebylo relevantní (a
že tohle není poslední blocker...).

Stejně ale - upřímně se omlouvám.

T.

2017-07-15 10:33 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by tpapouskova** [comment]
Tak jo, problem-statementy nahozeny [tu](https://docs.google.com/document/d/129Kzxt0rMLCbLWUymEZpPcvxYjEcad7aJ0X9qUx7Q1o/edit) .

jak jsem psala, představuji si to tak, že to, co je pod jednotlivými statementy psáno kurzívou, bude zobrazitelné po kliknutí na tři modré tečky na konci každého statementu (tj. nebude to pověšeno přímo na úvodce, ale jinde na webu). 

+ Bych jednotlivé statementy dala do samostatného sloupce a oddělila svislou šedou čárou (kratší než statement, aby to nevypadalo jako tabulka). A zarovnala nějak na střed daného sloupce.

Možná je bude třeba zkrátit, zatím si naprosto nedokážu představit, jak to bude vypadat.

**Comment by tomvej** [comment]
@tpapouskova Přidal jsem problem statements na úvodku. Příští týden budu řešit barvy apod. Jak je to s tím textem pod problem statementy? Ten se má odstranit?

**Comment by tpapouskova** [comment]
Geniální díky moc. Jj, text pod problem statementy prosím zcela odstranit.

Btw. Původní myšlenka byla, že doplňkový text k jednotlivým problem
statementům bude na samostatných "stránkách". Kdyžtak to zvaž. Imho když je
to takto na jedné, je to trochu nahuštěné a navíc je dosti vidět, jak se ty
průvodní texty překrývají... (Ale no pressure, netuším, jak moc je to
náročné...)

2017-08-26 17:46 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by tomvej** [comment]
Text odstraním. Jo, o těch samostatných stránkách tuším, ale zdálo se mi to moc prázdné. Není to moc práce, tak to můžu pro představu napsat a nasadit. Ideálně bych tady u toho zkusil zúžit layout, ale sekl jsem se u toho, jak by se to mělo chovat responzivně.

**Comment by tpapouskova** [comment]
hele, v pohode, asi netreba ani zkouset, Papi me presvedcil o vhodnosti
Tveho reseni argumentem, ze se v tom takto da lepe vyhledavat. uzsi layout
by byl ale fajn, nicmene tez ne nezbytny

Dne 30. 8. 2017 15:42 napsal uživatel "Tomáš Vejpustek" <
notifications@github.com>:
