### ISSUE TITLE
Místo "vyškrtnutý" zobrazovat "neaktivní"

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#144]
Na základě zpětné vazby od uživatele prosím o zobrazování textu "neaktivní" u vyškrtnutých advokátů.

Slovo "vyškrtnutý" totiž prý příliš evokuje, že advokát něco zlého udělal a oni ho za to potrestali vyškrtnutím, což tak ale není. Bude tedy asi lépe nepoužívat zákonný termín a nahradit jej laickým.

**Comment by repli2dev** [comment]
Upraveno a nasazeno.
