### ISSUE TITLE
Vysvětlující odstavec k vyhledávání

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#145]
Follow-up z #143 

Je potřeba umístit na stránku s vyhledáváním advokátů (a pravděpodobně i stránku advokáta) odstavec s informací, jak je hodnotíme: "U advokátů zobrazujeme počet jejich podání, o kterých soudy rozhodly:..."

Problém je, že je vertikálně dost velký (odrážky!), takže jsou dvě možnosti:
1. Dát ho nahoru, kde bude zabírat zbytečně hodně místa.
2. Dát ho dolů, kde ho uživatel nemusí vidět.
3. Redukovat odrážky.

**Comment by tpapouskova** [comment]
A proč ve zmiňovaných variantách není mnou původně navrhovaná? Tj. zobrazovat ten odstavec při přejetí nad polem se statistikami?

**Comment by tomvej** [comment]
To jako myslíš tooltip? Který má odstavec textu a tři odrážky? Jako, viděl jsem v tooltipech i větší zvěrstva (tooltip přes celou stránku s obrázky)...

**Comment by tpapouskova** [comment]
Řešení navrhuji následující.

Na stránku s výsledky vyhledávání pod "Zobrazeny výsledky pro: ..." dát text "U advokáta jsou zobrazeny počty jemu přiřazených meritorních a nemeritorních rozhodnutí a rozhodnutí o zastavení řízení. _Proč? Co to znamená?_" a do těch dvou otázek (psáno kurzívou) dát odkaz na "O projektu", ideálně rovnou zaskrolovaný na druhý odstavec ("Statistiky advokátů nejsou počítány...").

Ten stejný text (i s odkazem) by pak bylo dobré dát i přímo na stránku advokáta. Ale kam? Nápady? Nad těmi statistikami?

**Comment by tomvej** [comment]
Nasazeno na develu.
