### ISSUE TITLE
BUG: u některých advokátů se nezobrazují čísla

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#146]
Přetrvává, proto raději zakládám issue.

Namátkový příklad https://devel.cestiadvokati.cz/advocate/6651 .

**Comment by repli2dev** [comment]
@tpapouskova jaká čísla máš namysli? Načetl jsem si to a viděl jsem jak čísla celkové statistiky, tak po soudech. Mají tam být nějaká jiná čísla?

Jinak pokud se to neděje vždy, hodilo by se vědět jestli nemáš něco v Developer Console (najedeš kamkoliv na stránku a z pravé nabídky vybereš Revize prvku/Prozkoumat prvek/Inspekce) a nahoře klikneš na Console -- červené věci jsou zajímavé. (Funguje pro Chrome, Operu, Firefox).

**Comment by xorelvistor** [comment]
Já viděl tedy jen samé 0. Což mi potvrdilo volání [API](https://devel.cestiadvokati.cz/api/advocate/6651)
Nezobrazení čísel vypadá [takto](https://devel.cestiadvokati.cz/advocate/99999), ale to je "korektní", protože advokát s tímto ID u nás v databázi neexistuje.

**Comment by tomvej** [comment]
Nevím, co to bylo předtím, ale teď jsem to, myslím, odchytil.

Chová se to tak, že když jsem se před tím díval na advokáta, který pro daný soud měl nějaké hodnoty a teď se dívám na někoho, kdo má samé nuly, tak se zobrazí nuly jako čísla, ale zůstane tam sloupeček o velikosti těch předchozích hodnot.

Díky za postřeh, tohle se bude dát řešit.

**Comment by tomvej** [comment]
A vyhrává dělení nulou, takže sloupeček měl výku 'NaNem'. Už by mělo být vyřešené.
