### ISSUE TITLE
Detekce nedostupnosti API

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#148]
Například při deploymentu... místo prázdného webu dát nějakou smysluplnou hlášku.

**Comment by tomvej** [comment]
Úplně nerozumím tomu, jak si to představuješ.
1. Formuláře mají všechny hlášky.
2. Pro jednotlivé části se musí udělat jednotlivé hlášky, což je fakt docela dost práce -- mimo jiné #81 .
3. Technicky by se dalo udělat něco, co by detekovalo určitý return code, například 404 a zobrazilo nějaký div nahoře.

**Comment by repli2dev** [comment]
1. Během deploye je to větší část doby prostě přístupné a na úvodní stránce se nic nezobrazí, žebříčky vypadají prázdně...

3. To by mi celkem stačilo -- když tam přijdu tak ověřit, jestli je API dostupné (tím, že při deployi bych vracel extra pro všechny dotazy na API jeden konkrétní JSON) a ty bys zobrazil overlay nezavřitelný div nahoře.

**Comment by tomvej** [comment]
Tak, ono stačí detekovat chybový kód, pravděpodobně 404 -- což by mohlo postihnout více situací než deploy. Ideálně bych se chtěl vyhnout analýze JSONu.

______________________________________________________________

**Comment by repli2dev** [comment]
Při deploymentu se zobrazí buď stránka s deployment hláškou (která má 503) nebo `{deployment: true}` json (taktéž s 503), pokud je nastavený `HTTP_X_REQUESTED_WITH` na `xmlhttprequest` (což momentálně frontend nedělá).

**Comment by tomvej** [comment]
Ugh. Trochu složitější než jsem myslel. Problém není ani tak s detekcí (i když přeměnit promisy na ságy taky není úplně sranda). Problém je s obnovou. Původně jsem myslel, že bude stačit restartovat routovací ságu, ale vypadá to, že se musí restartovat i různé pomocné ságy. Tzn. uvažuju o zjednodušení problém s tím, že aby se dalo dostat z téhle screeny, bude třeba reload. Později můžeme uvažovat o nějaké komplikované logice s načítání dat.

**Comment by repli2dev** [comment]
Full reload je naprosto OK, nejsme aplikace ve které by bylo něco rozpracované a mělo se jen navazovat nové spojení.

**Comment by tomvej** [comment]
@repli2dev Jak je to s tím `HTTP_X_REQUESTED_WITH`? Já jsem to zatím testoval tak, že jsem založil soubor .deployment-in-progress a chodily mi normálně 503.

**Comment by repli2dev** [comment]
@tomvej Ta 503 ti dojde i bez poslání `HTTP_X_REQUESTED_WITH`, jen obsahem se ta stránka bude lišit -- dojde ti stránka pro uživatele (tedy s nadpisem Probíhá údržba...). Kdybys přiložil toto pole, tak dostaneš JSON, to ale jak tě chápu, netrápí.

**Comment by tomvej** [comment]
Ok, vzhledem k tomu, jak těžké je ten header nastavit, tak jsem ho tam přidal. :)
