### ISSUE TITLE
Nasazení crawleru pro stahování dat z Ústavního soudu

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#15]
- [ ] nainstalovat všechny potřebné závislosti na virtuální server
- [ ] zapojit script do systému, aby se data nahrávala do databáze

**Comment by xorelvistor** [comment]
- [x] nainstalovat všechny potřebné závislosti na virtuální server

**Comment by papousek** [comment]
Jak jsi to instaloval? Nikde neni zadny virtualenv.Jestli si s tim nevis rady, virtualenv ti zitra na serveru udelam.

**Comment by papousek** [comment]
@xorelvistor Ahoj. Nevidim v databazi advokati-devel (pod uzivatelem "advokati-ro" zadne dokumenty k US.
