### ISSUE TITLE
Detail advokáta: chyba ve velikosti sloupců

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#150]
Nejprve navštívím: https://devel.cestiadvokati.cz/advocate/6655 a následně https://devel.cestiadvokati.cz/advocate/120 (pomocí hledání Jiří Novák, tam, zpět, tam)...

Výsledkem je, že ačkoliv ten druhý Jiří Novák má 0 0 0 ve všech statistikách, tak boxy na pozadí jsou vzaty podle prvního Jiřího Nováka.

**Comment by tomvej** [comment]
Mělo by být opraveno v #146 , ale zatím není nasazeno.

Bylo tam dělení nulou, takže výška sloupce byla 'NaNem', což zjevně prohlížeč bral jako "zachovej předchozí".
