### ISSUE TITLE
Při vyhledávání případů nechodí výsledek

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#152]
V #109 jsem zaváděl ikonky i do vyhledávání případů -- a zjistil jsem, že se nezobrazují, protože z BE výsledek nechodí. Kontroloval jsem si, že na detailu případu výsledek je:

* https://devel.cestiadvokati.cz/cases?query=23%20Cdo%20434%2F2011
* https://devel.cestiadvokati.cz/case/16886

**Comment by repli2dev** [comment]
Nikdy nebylo ve specifikaci... přidal jsem ti to (nasaď si to dle libosti).
