### ISSUE TITLE
Filtrování případů ÚS

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#154]
Mám select, který vyfiltruje potřebné případy, ale když jej začlením do selectu toho pohledu, tak mi háže jiné počty.

**Comment by xorelvistor** [comment]
Filtrování pouze případů z roku 2007 a dál, které jsou ústavní stížností.
```sql
select id_case
from "case" c join document on (document.case_id = c.id_case) join document_law_court on (document_law_court.document_id = document.id_document)
where court_id = 3 and year >= 2007 and proceedings_type ilike '%O ústavních stížnostech%'
```

zkoušel jsem začlenění přes EXISTS, ale výsledky se lišily o cca 1000 případů

```sql
SELECT * FROM "case" WHERE
-- NS: Cdo, Cdon, ICdo, NSČR, Odo, Odon
--(court_id = 2 AND SUBSTRING(registry_sign FROM '\m(\D+)\M') IN ('cdo', 'cdon', 'icdo', 'nsčr', 'odo', 'odon') AND year >= 2001)
-- NS: Tdo
--OR (court_id = 2 AND SUBSTRING(registry_sign FROM '\m(\D+)\M') IN ('tdo') AND year >= 2002)
-- NSS: As, Ads, Afs, Ars, Azs, Ans, Aos, Aps
--OR (court_id = 1 AND SUBSTRING(registry_sign FROM '\m(\D+)\M') IN ('as', 'ads', 'afs', 'ars', 'azs', 'ans', 'aos', 'aps') AND year >= 2006)
--OR 
(court_id = 3 AND EXISTS(
	select id_case
	from
	"case" c join document on (document.case_id = c.id_case) join document_law_court on document_law_court.document_id = document.id_document
	where year >= 2007 and proceedings_type ilike '%O ústavních stížnostech%' and id_case = "case".id_case) -- "case" je zde z vnejsiho dotazu
	)
	--OR
	--(court_id = 3 and year < 2007)
order by year
```

@repli2dev Mohl by ses na to prosím kouknout? Ověřit dotaz?

**Comment by repli2dev** [comment]
Odpověď je: JOIN... některé případy mají více dokumentů a tudíž to číslo nesedí, protože se ti ID případu opakuje víckrát, musel bys tam přidat `DISTINCT`... v druhém dotazu to pak víckrát není, protože to neJOINuješ, ale rovnou vybíráš z tabulky `case`.

Btw. než závislý EXISTS je čitelnější nezávislý IN. (Vypadá to, že optimalizátor to v tomto případě zvládne udělat z toho totéž, ale čitelnější je to s IN)... 

Btw. 2. je možné, že tohle těžce shodí výkon celého webu, protože tohle view používáme profiltrování :/ Uvidíme.
