### ISSUE TITLE
Auditování

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#156]
Při libovolném přístupu/změně/zpracování osobních údajů je potřeba přidat do audit logu následující údaje:

1. Kdy
2. Kdo (celé jméno + uživatelské ID), pokud není, tak `Anonymní uživatel`.
3. Odkud (IP + User Agent)
4. Důvod (Vyžádáno veřejností, Vyžádáno autorizovaným uživatelem, Oprava/Úprava, Import...)
5. Operace (Čtení, Změna z X na Y, ...)

Za osobní údaje považujeme momentálně:

- Spojení advokáta a výsledku s případem.
- Informace o advokátovi (jméno, příjmení, adresa, email, telefon...)

Přístupy skrze databázi neřešíme (přístup mají jen správci a ty technicky lze v daném formátu logovat obtížně).

Přístupy skrze command-line utility musí brát v potaz skutečného uživatele a pokud není, měl by odmítnout se spustit (https://stackoverflow.com/questions/4598001/how-do-you-find-the-original-user-through-multiple-sudo-and-su-commands). CRON spuštění se děje skrze systémové uživatele (~ organizace).

Poznámky:

- Při přístupu do gridu se musí zalogovat přístup ke všem jeho položkám.
- Při transakčním zpracování by systém měl logovat přístup vždy, a případné změny pouze při úspěšném doběhnutí transakce.

Otevřené otázky:

- Jak dlouho se mají data uchovávat?

**Comment by repli2dev** [comment]
@xorelvistor s tvým taggerem advokátů je potíž... je totiž udělaný v Pythonu a přistupuje přímo do databáze.

Log je ale souborový, transakční a využívá kontext aplikace (DB uživatel; IP; User Agent...)

**Comment by xorelvistor** [comment]
Ano je...a to hlavně z důvodu rychlosti běhu. Pokud existuje způsob, jak přistupovat k databázi skrze existující rozhraní (z Pythonu), sem  sním.
Můžu udělat nějakou změnu, či poskytnout nějakou informaci, která by to mohla napravit?
Zřejmě diskuze bude ještě předmětem zítřejší schůzky.

**Comment by repli2dev** [comment]
Napadají mě následující řešení:
1. Forkovat (tricky pokud to chceme umět spouštět na Windows...) a mezi procesy komunikovat pomocí socketů co je k logování (na úrovni operation, reason, audited subject type, description)
2. Uložit do tempového souboru, který ten command, pak vždy zpracuje (nehledě na selhání procesu)... A uloží to do logu.

Zatím bych volil variantu 2, implementace bude na tobě.

**Comment by xorelvistor** [comment]
@repli2dev A co by mělo být obsahem tohoto tempového souboru? A kde všude bych měl logovat, to mám logovat i získávání seznamu advokátů z DB a načtení každého připadu?

**Comment by repli2dev** [comment]
@xorelvistor představuji si to jako csvčko s třemi položkami (audited_subject, description, reason), pro inspiraci naplnění i toho, jak toto csvčko přesypat do logu viz: https://github.com/datoszs/czech-lawyers/blob/master/app/Commands/NSAdvocateTagger.php#L118

Načítání (všech) advokátů v tomto případě ignoruj, mají velmi interní a technický důvod proč se k nim přistupuje a skutečně osobní údaj je jen to co se vytvoří.

Navíc do tohoto souboru to dáváš jen tehdy, když ti projde commit, jinak tam mají zůstat jen to co se skutečně provedlo (viz README, ve kterém jsem se to snažil co nejlépe popsat).

P.S. Vyvíjej to už na masteru, produkce už na něm běží.

**Comment by xorelvistor** [comment]
Díky @repli2dev . Koukal jsem do zmiňovaného taggeru a podle něj loguji jen `processed` (jednoznačně přiřazené advokáty případům), ostatní případy, kdy je výsledkem tagování několik možných variant advokáta (levenshtein) pak neloguji, je to ok?
Takže jestli tomu správně rozumím, dávkové načtení seznamu advokátů a případů ke zpracování není třeba evidovat, i když to (asi) odpovídá `reason::REQUESTED_BATCH`?

**Comment by repli2dev** [comment]
@xorelvistor je to tak, logovat všechny potenciální kombinace nedává smysl, ten osobní údaj (nakolik je zde abstraktní povahy) vytvoří v takovém případě až manuální tagovač (člověk) a to už se zaloguje.

Ad druhá poznámka, ano přesně tak. reason::REQUEST_BATCH to úplně neodpovídá, tím bylo myšleno, když si uživatel otevře třeba grid uživatelů, nebo provede hledání... nikoliv však, když si je potřebuješ natáhnout všechny pro interní potřebu.

**Comment by repli2dev** [comment]
@xorelvistor je všechno ok? Dá se issue zavřít?

**Comment by xorelvistor** [comment]
Jen se mi nepodařilo zprovoznit smazání onoho temp souboru z commandu. Končil jsem s hláškou `Unable to delete`, ale na funkci to vliv nemá ;-)

**Comment by repli2dev** [comment]
@xorelvistor potřeboval bych více detailů. Pokud to spouštíš jako cestiadvokati.cz tak ten přístup pro zápis ke složce ve které to je má.

**Comment by xorelvistor** [comment]
@repli2dev S tím problémem jsem se setkal už na locale a na produkci jsem to neověřoval. Jde  o to, že soubor (temp/log), který se vytvoří za běhu toho Pythonu, nešel smazat příkazem v PHP. Proto jsem tu část o mazaní souboru zakomentoval. On se stejně vytváří s právy zápisu, takže je vždy přemazán, ale...

**Comment by repli2dev** [comment]
Ano správné je ho mazat, takže poprosím o investigaci... (ta funkce Filesystem::delete dělá nějakou magii a na windows se chová jinak, možná je problém v tom).

**Comment by papousek** [comment]
@repli2dev Chtěl bych nasadit zveřejňování dat v CSV podobě. Koukám se na to auditování a není mi úplně jasné, jak to jde dohromady. Mám někam zapsat to, že exportuju data (a to pro každého advokáta zvlášť)?

**Comment by repli2dev** [comment]
@papousek Už jsem nad tím přemýšlel a přijde mi to technicky nesmyslné, protože víceméně v ten moment exportu prakticky jen přesypeš ten dump celý do logu.

Reálně to znamená 14000 advokátů * 450 bajtů na záznam v logu => asi 7 MB; pak je tam poslední tagování per případ, který je řádově 200000 * 450 bajtů => asi 90 MB; nemůžeme si dovolit takovou věc logovat, protože pouhých 600 požadavků by stačilo na primitivní DDoS.

Proto navrhuji tam zalogovat jen záznam, že uživatel XYZ stáhnul celkový export z tohoto data. Dává to tak smysl?

**Comment by xorelvistor** [comment]
Mě to smysl dává a možná by tam mohla být ještě informace o počtech (záznamů)
