### ISSUE TITLE
Implementace GDPR

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#158]
Potřebujeme prozkoumat novou legislativu:
1. Vztahuje se na nás? Jaké jsou její důsledky, pro nás?
2. Jak ji implementovat? Není současná implementace OK?

**Comment by repli2dev** [comment]
U druhého odstavce bych doplnil, že tyto věci budeme i po vyřízení archivovat, abychom byli schopni doložit onu změnu i zpětně.

možná jsem to přehlédl ale u 5 odstavce mi chybí nějaké konstatování, že toto přiřazení případ - advokát považujeme za osobní údaj. Také mi tam chybí řečení (a odkaz nahoru) že to ale nestahujeme všechny spisovné značky.

A na začátku mi chybí nějaký stručný úvod stylu... níže jsou popsán jednotlivé zpracování osobních údajů na tomto webu.

**Comment by tpapouskova** [comment]
Náležité úpravy provedeny, díky za návrhy!

Ten úvod jsem tam nakonec nedala, už takto je to nemístně dlouhé a navíc GA
se vlastně netýká zpracovávání os. údajů (v tom odstavci vlastně říkáme, že
z GA žádné os. údaje netaháme)...

Dne 14. května 2018 18:48 Jan Drábek <notifications@github.com> napsal(a):
