### ISSUE TITLE
Read-only přístup k získaným datům

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#16]
- [ ] rozmyslet si formu zpřístupnění rozhodnutí z jednotlivých soudů, nabízí se:
  - HTML stránka s možností jednoduchého vyhledávání a řazení
  - CSV export
- [ ] implementace
- [ ] nasazení

**Comment by repli2dev** [comment]
V první fázi:
 - Vyhledání konkrétního advokáta + detail stránka advokáta se seznamem případů.
 - Vyhledání konkrétní případu se seznamem dokumentů.
 - Detail dokumentu - s odkazem interně a externě.

**Comment by repli2dev** [comment]
![img_0274](https://cloud.githubusercontent.com/assets/475549/20809134/5c73b5a2-b805-11e6-9598-3c239fa150d9.JPG)

**Comment by papousek** [comment]
@repli2dev Na schůzce jsi říkal, že je to vyhledávání dostupné na develu - můžeš prosím poslat link? (v repu jsem to nenašel)

**Comment by repli2dev** [comment]
@papousek to jsme si nerozumněli, je tam všechno co je dokončené a tohle dokončené není.

**Comment by papousek** [comment]
@repli2dev Myslíš, že bys mohl do čtvrteční schůzky nasadit na devel to, co máš u sebe na notebooku (+ případné další věci)?

**Comment by repli2dev** [comment]
Jako neměl by to být větší problém... Jen by se mi hodily nějaká data z tagování advokátů...

**Comment by repli2dev** [comment]
Dotaz k mockování tagování advokátů (pomalý a ohackovaný)
```
INSERT INTO tagging_advocate (document_id, advocate_id, status, is_final, debug, inserted, inserted_by, job_run_id, case_id)
SELECT
NULL,
(SELECT id_advocate FROM advocate WHERE g=g ORDER BY RANDOM() LIMIT 1 ),
(SELECT unnest(ARRAY['failed', 'ignored', 'processed', 'fuzzy']) WHERE g=g ORDER BY RANDOM() LIMIT 1)::tagging_status,
FALSE,
NULL,
NOW(),
2,
NULL,
(SELECT id_case FROM "case" WHERE g=g ORDER BY RANDOM() LIMIT 1)
FROM generate_series(1,1000) as g
```

**Comment by xorelvistor** [comment]
@repli2dev  První advokáti se objevují v databázi...právě běží tagování na serveru

**Comment by repli2dev** [comment]
Je to naimplementované a komitnuté... na server to momentálně nasadit nemůžu, protože tam stále ještě běží tagování advokátů co Radim včera pustil.

**Comment by xorelvistor** [comment]
@repli2dev  Tagování jsem přerušil  (stejně by nedoběhlo do schůzky)...můžeš tedy nasadit. Spustil jsem ```deploy```, ale to asi nestačí, takže máš volný prostor.
