### ISSUE TITLE
BUG: u autocomplete (advokátů) nelze kliknout na nabízené

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#161]
jak na domovské stránce, tak i na stránce Advokáti

**Comment by tomvej** [comment]
Vypadá to jako browser/OS related, u sebe (Linux + firefox/chromium) to nedokážu replikovat. @repli2dev @xorelvistor Mohli byste mi pomoc ověřit ostatní OS?

**Comment by repli2dev** [comment]
@tomvej reprodukováno na OS X v Opeře (Webkit), první proklik prošel, pak jsem se vrátil a zkusil vybrat sokolovou a ta na klik už nereagovala... stalo se mi to na stránce vyhledávání advokátů.

Je to trochu random, ale děje se mi to v 50% případů.

**Comment by tomvej** [comment]
@repli2dev Díky, nedošlo mi, že se to chová nedeterministicky.

Tak to je hodně husté. Zatím podle mého odhadu se to stane, když klikneš moc rychle po inputu na jméno.

**Comment by tomvej** [comment]
Ok, netuším, proč se to děje. Zjevně to potřebuje delší výzkum, ale nevím, kdy se tomu budu moct nejdřív věnovat.

Prozatím rada:
1. Fungují klávesové zkratky (šipky dolů a enter).
2. Když počkáš vteřinu, funguje to taky.

**Comment by xorelvistor** [comment]
reprodukováno na Windows (10) v Chromu a Firefoxu. Počkat vteřinu nestačí, dokonce ani při opětovném návratu do input pole proklik nefunguje. Zkoušeno opakovaně, příčina nenalezena.
