### ISSUE TITLE
Změna ve způsobu počítání žebříčků

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#164]
Už jsme kdysi zmiňovali. Není úplně fér, že v červeném žebříčku figurují advokáti specializující se na ÚS, což je prostě soud, který meritorně téměř nerozhoduje... Tedy jednoduše realizovatelný nápad na změnu ve vzorci počítání žebříčku:

- místo nynějšího počet M daného advokáta - počet N daného advokáta
- to počítat takto: [počet M daného advokáta u NS x (1-celkový podíl M u NS) - počet N daného advokáta u NS x (1-podíl N u NS)] + [počet M daného advokáta u NSS x (1-podíl M u NSS) - počet N daného advokáta u NSS x (1-podíl N u NSS)] + [počet M daného advokáta u ÚS x (1-podíl M u ÚS) - počet N daného advokáta u ÚS x (1-podíl N u ÚS)]

Co myslíte (assignuju všechny, ať se k myšlence můžete vyjádřit)?

Imho by to mohlo být z hlediska implementace jednoduché (všechna potřebná čísla už na frontend chodí). Šlo by to, v případě vašeho souhlasu, samozřejmě, učinit nějak přednostně?

Dejte vědět. Okec nad žebříčkem bych pak změnila obratem.

**Comment by tpapouskova** [comment]
Tady je dotaz, který to počítá a dá se použít jako náhrada za definici pro `vm_advocate_score`:

```sql
SELECT
	*,
	positive - negative AS score,
	NTILE(10) OVER (ORDER BY positive - negative DESC) AS decile
FROM (
	SELECT
		advocate.id_advocate,
		SUM(CASE WHEN tagging_result.case_result = 'positive' THEN 1 - court_stats.positive_ratio ELSE 0 END) AS positive,
		SUM(CASE WHEN tagging_result.case_result = 'negative' THEN 1 - court_stats.negative_ratio ELSE 0 END) AS negative
	FROM advocate
	INNER JOIN vw_latest_tagging_advocate AS tagging_advocate
		ON tagging_advocate.advocate_id = advocate.id_advocate
	INNER JOIN vw_latest_tagging_case_result AS tagging_result
		ON tagging_result.case_id = tagging_advocate.case_id
	INNER JOIN vw_case_for_advocates AS "case"
		ON "case".id_case = tagging_result.case_id
	INNER JOIN (
		SELECT
			court_id,
			AVG(CAST((result.case_result = 'positive') AS INT)) as positive_ratio,
			AVG(CAST((result.case_result = 'negative') AS INT)) as negative_ratio
		FROM "vw_latest_tagging_case_result" AS "result"
		INNER JOIN "case" ON "result".case_id = "case".id_case
		GROUP BY 1
	) AS court_stats ON "case".court_id = court_stats.court_id
	GROUP BY 1
) AS t
```

**Comment by repli2dev** [comment]
Chápu to tak, že pro každý soud se spočítá poměr negativní/pozitivních a každý případ advokáta se pak ohodnotí pro pozitivní/negativní na škále [0,1) a to podle toho jaký je poměr soudu.

Máme-li tedy soud se skóre: 0.6 negativní, 0.3 pozitivní, pak negativní případ advokáta u daného soudu přidá negativní skóre 0.4, zatímco pozitivní případ přidá pozitivní část skóre na 0.7.

Pro získání celkového skóre advokáta se to pak od sebe odečte... Pokud je to takhle tak mi to smysl dává (a je to víceméně to co jsem navrhoval dříve).

Nicméně pár věcí k dotazu:

0. Ten dotaz vynechal `status = processed` u joinu `vw_latest_tagging_advocate` a `vw_latest_tagging_case_result`.
1. Proč se joinuje "case" namísto `vw_case_for_advocates`? Takhle se berou v potaz i případy, které pro portál advokátů nejsou relevantní.
2. Není ovlivněn výsledek tím, že vyházíš z pohledu `vw_latest_tagging_case_result`? Tzn. neměli by být do výpočtu zahrnuty i případy, u kterých nemáme otagován výsledek? A v každém případě, neměly by se brát jen ty s `status = processed`.

**Comment by papousek** [comment]
@repli2dev Podle toho prikladu, co pises, to chapes spravne.

Dotazy:

  0. Mas pravdu, to je chyba.
  1. Mas pravdu, to je chyba.
  2. IMHO to nevadi a staci brat pripady, kde je `status = processed`.
