### ISSUE TITLE
Přidání možnosti identifikovat advokáty IČem při manuálním tagování

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#165]
Hodilo by se, aby bylo možno při manuálním tagování nejen vepisovat jméno (a následně vybírat z našeptávače), ale i přímo vepisovat IČ.

**Comment by repli2dev** [comment]
Ono to hledalo, ale ta komponenta pro hledání na backendu to pak nezobrazila, protože tam nebyl match.

@tomvej pro info, přidal jsem do autocomplete API zdroje sloupec s IČem.
