### ISSUE TITLE
U vyškrtnutých advokátů nezobrazovat e-mail

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#167]
ČAK u vyškrtnutých advokátů zpravidla ani e-mail nezveřejňuje, nicméně tam, kde to dělá, to není z hlediska ochrany os. údajů úplně košér.

Já osobně bych ho z databáze přímo nemazala (konec konců jsme jej získali z veřejného rejstříku), ale na druhou stranu, kdybychom mohli vyškrtnuté advokáty přestat znervózňovat jeho zobrazováním, mohlo by to být fajn.

**Comment by tpapouskova** [comment]
Neuvědomila jsem si, že tohle je možná taky na Toma (potřebujeme nezobrazovat e-maily vyškrtnutých advokátů), tak ho pro jistotu přidávám.

**Comment by tomvej** [comment]
Záleží, jak to chcete. Pro mě to samozřejmě není problém, problém FE implementace však je ten, že ta data přijdou z back-endu a uživatel si je může přečíst v network konzoli -- jako že to asi neudělá, ale ten e-mail půjde internetem.

Zvažoval bych i přidání vysvětlujícího rámečku, že tento právník neposkytuje advokátní služby. Dává to smysl?

**Comment by tpapouskova** [comment]
Chápu, že FE řešení není čisté, ale je-li rychle implementovatelné, prosím
o něj (a následně můžeme dořešit BE).

Ten rámeček je super nápad! Text "Tato osoba již advokátní
služby neposkytuje."

Dne 11. září 2017 12:21 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Je to na masteru.

**Comment by tpapouskova** [comment]
Díky moc, odassignovávám tedy Toma a issue, na němž zbývá dořešit BE, řadím na nižší prioritní příčku.

**Comment by repli2dev** [comment]
@tpapouskova z ČAKu k nám proudí u vyškrnutých advokátů jak e-maily, tak adresy, viz například http://vyhledavac.cak.cz/Contact/Details/28c67ea0-6023-e711-80d5-00155d040b0c 

V duchu zadání tasku bych soudil, že není žádoucí zobrazovat ani ty -- to má ovšem menší zádrhel v tom, že momentálně jsou ti advokáti vyhledatelní a v rámci seznamů advokátů se zobrazuje město.

Prosím tedy o návrh co s tím.

**Comment by tomvej** [comment]
Původně jsem uvažoval, že nebudu zobrazovat ani adresu, ale pak jsem si uvědomil, že ji používáme jako dodatečné rozlišení (např. pro stejnojmenné advokáty). Tak nevím.

______________________________________________________________

**Comment by tpapouskova** [comment]
Adresa je, imho, v pohodě - ta je totiž spojena výlučně s advokátní
činností (když končíš, zrušíš si pronájem kanceláře). E-maily ale někteří
vyškrtnutí advokáti měli soukromé, tak chápu, že je štvylo, když jim na ně
i po ukončení činnosti lidi psali.

Prozatím bych tedy řešila výlučně e-mail.

Pokud se někdo ozve s odůvodněnou stížností, samozřejmě to můžeme ještě
zvážit.

Dne 14. září 2017 10:00 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by repli2dev** [comment]
@tpapouskova nemůže ta adresa být ale i doma?

**Comment by tpapouskova** [comment]
Tak určitě může, že...

Co kompromisní řešení - u vyškrtnutých advokátů zobrazovat jen město?

2017-09-14 11:43 GMT+02:00 Jan Drábek <notifications@github.com>:

**Comment by repli2dev** [comment]
@tpapouskova upravil jsem to tak, dává mi to též smysl. Posílám tedy zcenzurovanou adresu.

@tomvej musel jsem kvůli tomu šáhnout do FE a udělat podmíněný výpis PSČ, v případech, které jsem testoval to prošlo ok, ale pro jistotu na to mrkni.

**Comment by tomvej** [comment]
Ověřeno, je to správně.

______________________________________________________________
