### ISSUE TITLE
Otevírání "dlaždic" v nové kartě/okně

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#168]
Potřebovala jsem si teď pootevírat všechny případy jednoho advokáta a zjistila, že nefunguje right-click (nelze otevírat dlaždice v nové kartě/okně). Pokud by to šlo, bylo by to fajné vylepšení.

**Comment by tomvej** [comment]
Co je jednoduché:
* otevřít v nové záložce na ctrl+click
* otevřít v nové záložce na klik prostředním tlačítkem

Co pravděpodobně nepůjde: Aby se zobrazilo menu na pravý klik jako u odkazu.

**Comment by tpapouskova** [comment]
Ok, když to nepůjde, tak se holt nedá nic dělat.

Nejsem si jistá, nakolik je pak pro návštěvníky nápomocné implementovat
některou z těch dvou dalších variant, mě by třeba naprosto nenapadlo je
zkoušet použít. Nicméně, není-li to nijak složité, přesto bych Tě o
implementaci jedné (kterékoliv) z nich poprosila, a to čistě pro mé účely
(často si potřebuji v ručním tagování vyhledat jednu po druhé všechny
spisovky advokáta a ctr-c ctrl-v nefunguje na dlaždici, ale až na stránce
případu).

Dne 10. září 2017 9:50 Tomáš Vejpustek <notifications@github.com> napsal(a):

**Comment by tomvej** [comment]
Ok, tak jsem se na to díval ... a dá se to udělat. Doufejme, že to nic nerozbije, je to trochu více low level než bych chtěl.

**Comment by tomvej** [comment]
Tak jo, první pokus je v devel větvi (bohužel, na develu je master). Funguje to zatím na dlaždicích. Ještě jsem si říkal, že by se to mohlo udělat podobně na ostatních odkazech, tak nevím, jestli v rámci tohohle nebo založit další issue.

**Comment by repli2dev** [comment]
@tomvej devel je momentálně starý a ještě jsem neodvětvil aktuální pro novou verzi, zatím bych tedy hotfixoval na master, dokud se nám to neustálí, co myslíte? @tomvej, @xorelvistor @papousek

**Comment by tomvej** [comment]
@repli2dev ok, co s tím? Zamergovat do masteru? Do cherrypicku se mi nechce, je to 8 commitů.

**Comment by repli2dev** [comment]
Vidím dvě možnosti: 
1. Merge developu do masteru (again)
2. Rebase rozdílu developu na master (mělo by být bezkonfliktní).

Chápu-li to správně, rád by si to otestoval na developu, že? Pokud ano, tak pak změň si develop instanci checkoutni na co potřebuješ.

**Comment by tomvej** [comment]
Já si to otestovat nepotřebuju. Spíše jestli s tím bude spokojená Terka.

**Comment by tpapouskova** [comment]
urcite bude :)

Dne 11. 9. 2017 22:10 napsal uživatel "Tomáš Vejpustek" <
notifications@github.com>:

**Comment by tomvej** [comment]
Ok, je to zamergováno do masteru. Nasadit z práce nezvládám, když tak večer. Má to jít na devel nebo rovnou na live?

**Comment by tpapouskova** [comment]
IMHO rovnou live

2017-09-12 9:26 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by tomvej** [comment]
Nasazeno.

**Comment by tpapouskova** [comment]
Tohle je hotové, ne?

Zavírám.
