### ISSUE TITLE
stahování Tdo z nsoud.cz

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#169]
Snad jde o ojedinělý případ, ale narazila jsem například na rozhodnutí 4 Tdo 122/2009, ke kterému nemáme stažený dokument, i když na nsoud.cz je.

(Dále 8 Tdo 1455/2015, 3 Tdo 1016/2006...nějak se zdá, že je problém s Tdo rejstříkem, možná obecně ?)

To by asi stálo za prověření.

**Comment by repli2dev** [comment]
TDO nestahujeme, protože nám ty dokumenty k ničemu nejsou (chybí v nich advokáti jestli dobře vzpomínám), takže padlo rozhodnutí je nestahovat.

Stahujeme jen rejstříky: CDO, NSČR, ICDO

**Comment by tpapouskova** [comment]
No vidíš to, to vlastně tehdy dávalo smysl. To je tak, když člověk nemyslí moc dopředu. Jsem trubka, že jsem na toto rozhodnutí úplně zapomněla.

Tudíž to přelabelovávám na enhancement a náležitě přejmenovávám. Do budoucna by to asi bylo fajn, kdyby si advokáti, kterým jsou tato rozhodnutí přiřazena, mohli rovnou na našem webu rozkliknout i jejich text.

**Comment by repli2dev** [comment]
Přidal jsem do crawleru a naimportoval všechno co jsem stáhl (s rozhodnutím v minulosti od 2000 do dneška).
