### ISSUE TITLE
Jak se aktuálně nasazuje nová verze webu a crawlerů?

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#17]
- [ ] Nasazuje se web nějak automaticky (git push někam na produkci)?
- [ ] Je proces nasazení někde zdokumentován? Zvládá tento proces Honza i Radim?
- [ ] Existuje nějaké staging prostředí?
  - typicky asi chceme být schopni si nasazadit zkušební verzi webu
  - může se stát, že někde budeme chtít pouštět zkušební verze crawlerů

**Comment by repli2dev** [comment]
1. Web se automaticky nenasazuje
2. Je zdokumentován. Viz `README.md`, momentálně ve větvi develop. Radim to nějak rozcházel (takže jsme přes mail řešili nějaké chyby), ale jestli to nakonec rozchodil netuším.
3. Ještě neexistuje, ale vytvořím ho.

**Comment by repli2dev** [comment]
Radime, můžeš se vyjádřit k bodu číslo 2? Chápeš postup v `README.me`? Je dostatečně srozumitelný, nebo bys byl raději pro obsáhlejší popis?

**Comment by papousek** [comment]
Díky za info. V příslušném `README.md` mi není jasná věta "On server under the **proper user** and git **branch** just run php deploy.php." (který user a která větev?), ale to k tomu se asi ještě vyjádří Radim.

**Comment by xorelvistor** [comment]
Add bod 2: Rozcházel jsem to a nějak rozjel, většinu nástrojů jako composer a gulp jsem v životě nepoužíval a musel jsem tedy vše instalovat. Ještě k tomu přecházím na nový počítač a budu vše řešit znovu. Kdyby byla nějaká snadnější varianta (co já vím projekt v IntelliJ) uvítám ji...případná schůzka kolem konfigurace a nasazení by taky bodla. Struktura aplikace mi taky není úplně jasná...

**Comment by repli2dev** [comment]
@papousek Zkusil jsem `README.md` více rozvést co se prostředí a módu týče... Tvůj dotaz by měla vysvětlovat sekce **(Example) Configuration** (otázka je, nakolik zveřejňovat naši nasazenou konfiguraci). (Konkrétně všechno kolem advokátů by mělo běžet pod uživatelem `cestiadvokati.cz`, tzn. i web i crawlery.)

@xorelvistor Nějaký krátký hangout k tomu někdy během týdne můžeme dát. Snadnější variantu bohužel úplně nevidím (při zachování vývojářského komfortu).
