### ISSUE TITLE
v prostředí pro man. tag. nejdou vyhledávat spisovky ÚS

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#171]
Zkoušela jsem je zadávat v různých formátech (III. ÚS 503/17, III.ÚS 503/17, III ÚS 503/17, 3 ÚS 503/17, 3. ÚS 503/17), ale nějak mi to prostě nejde...

**Comment by xorelvistor** [comment]
povedlo se mi vyhledat ve tvaru `III. ús 503/17` ale pouze bez použití filtrů výsledků tagování a nebo "trefou" do skutečných výsledků (několik kombinací)

**Comment by repli2dev** [comment]
Přidal jsem tam normalizaci spisovek poté co přijdou... Což znamená, že by to mělo zvládnout různé formáty spisovky US, ale jen když je víceméně celá. Má to ale i nějaké nevýhody -- požírá to mezery atp, kdyby se to projevilo jinde, dejte vědět.
