### ISSUE TITLE
nestažení některých rozhodnutí z nsoud.cz (rejstřík NSČR)

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#172]
například rozhodnutí 29 NSCR 54/2012 už bychom ale stahovat měli, ne? v databázi ale chybí, přestože na webu NS je...

**Comment by repli2dev** [comment]
Ve skutečnosti tam případy byly, jen náš pohled `vw_case_for_advocates` je vyfiltroval (chyběl podmínka na `nscr` (variantu bez diakritiky).
```
select * from "case" where registry_sign ILIKE '29 nscr 54/2012';
select * from "vw_case_for_advocates" where registry_sign ILIKE '29 nscr 54/2012';
```
