### ISSUE TITLE
přidávání chybějících případů do databáze ?v man. tagování?

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#173]
Narážím teď na případy, které zjevně visí na webech soudů, ale my je nemáme v databázi, tudíž je nemůžu na základě stížností advokátů ručně doznačkovat. Pro pružnější reagování na tyto stížnosti by tedy bylo super, kdyby se dalo v prostředí pro man. tagování neexistující případy přímo přidávat. Případně kdybychom našli jiný pro všechny příjemný způsob, jak ty případy do databáze dostat (můžu vám třeba posílat mailem jejich seznam a vy to tam nějak doimportujete či tak...).

**Comment by repli2dev** [comment]
Primárně bych to nechtěl dělat, vedlo by to za mě tříštění pozornosti na to získávat co nejčistší data (tzn. opravdu najít chybu v procesu crawlerů, importu, soudu...) a mít co nejčistčí data (dohrávání a dat).

Ačkoliv obě mají stejný cíl, vedou k využití práce na hodně rozdílných místech -- první řeší příčinu, druhý jen lepí díry.

-----

Pozitivně, je potřeba prohledat importované (ideálně přímo tabulku `case`), jak ukázal případ s NSČR rejstříkem.

**Comment by tpapouskova** [comment]
Ok, s tímto asi souhlasím. Prozatím se to navíc neukázalo jako potřebné.

Tedy zavírám s tím, že když v budoucnu budeme nějakým advokátem informováni, že nám tam chybí mraky jeho případů a řešení se soudy bude na delší dobu, ošéfujeme to nějak jednorázově.
