### ISSUE TITLE
rozhodnutí máme v databázi (jde je vyhledat na webu), ale nejdou rozporovat/manuálně otagovat

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#174]
naprosto netuším, čím to může být, ale například tato rozhodnutí

1 As 4/2010
8 Azs 56/2006
21 Cdo 2685/2016
4 Tdo 6/2015

jde vyhledat na našem webu, ale nejde je rozporovat (zkoušela jsem a nezaslal se mi ověřovací mail) a nejde je pod sp. zn. vyhledat v prostředí pro manuální tagování

**Comment by xorelvistor** [comment]
tento případ 1 As 4/2010 byl v minulosti otagován ručně - ale jen výsledek https://www.cestiadvokati.cz/admin/tagging/case?caseId=233736 (přes id případu v URL adrese)

možná je to tím

**Comment by repli2dev** [comment]
Je to nedomyšleností toho formuláře... vybíráš v jakých skupinách to chceš hledat... pro najít toho prvního zmíněného musíš dát stav výsledku: v pořádku; stav advokáta: selhalo. Obě ty věci mají AND.

Navrhuju tedy doplnění původně zavržené výchozí konfigurace Cokoliv; Cokoliv.

**Comment by tpapouskova** [comment]
A vysvětluje to i to, proč mi vůbec nedošel verifikační kód pro potvrzení
rozporování?

Dne 14. září 2017 7:49 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
@tpapouskova ne, pokud se s tím potkala tak reportuj v samostatném issue.

**Comment by tpapouskova** [comment]
Splitnutí tohoto issue raději nechávám na vás, původně jsem jej vypisovala s představou, že nezaslání verifikačního e-mailu a nemožnost vyhledat rozhodnutí v prostředí pro manuální tagování spolu souvisí (viz iniciální koment).

**Comment by repli2dev** [comment]
@tpapouskova rozporování pro první daný případ mi fungovalo pro obě mé adresy (osobní + gmail). Takže přehazuji na tebe, chci buď další informace nebo zavřít issue ;-)

**Comment by xorelvistor** [comment]
@repli2dev @tpapouskova 
Nebylo by lepší obecně oddělit vyhledávání (pouze) podle spisové značky a vyhledávání za použití filtrů výsledek, advokát, soud? To co Terka popisuje (1 As 4/2010) je případ toho, kdy je rozporován případ, který už má stav `is_final` v jednom z výsledků, máme ověřené/otestované takové chování?

**Comment by repli2dev** [comment]
@xorelvistor po doplnění filtrů "cokoliv" mi přijde první půlka návrhu už zbytečná, protože udělat samostatné vyhledávání případů by bylo náročnější. A to chování co popisuješ ve druhé je chtěné, nezobrazovat is_final věci pro failed, v rámci ok se zobrazí.

Mě přijde, že jsme zapomněli na use case "chci vyhledat případ nehledě na otagování", proto jsem ho začal dnešní úpravou podporovat.

**Comment by tpapouskova** [comment]
Tak jo, pro všechny případy, kdy mi to dříve neposlalo ani verifikační kód,
už mi ho dnes poslalo. Teď jen nejde kliknout na tu šedou lištu v prostředí
pro manuální tagování (ale to jsem pochopila, že stačí počkat na jinou
vhodnou dobu, a zázrakem se to zase opraví :).

Dne 14. září 2017 11:40 Jan Drábek <notifications@github.com> napsal(a):

**Comment by xorelvistor** [comment]
@repli2dev Jasně, po doplnění filtru "cokoliv" je to už bezpředmětné, ale myslel jsem, že se bavíme ještě na úrovni návrhů řešení - nenapadlo mě, že už je to hotové :-)
