### ISSUE TITLE
zohlednit rušení rozhodnutí NS Ústavním soudem

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#175]
Víme o tom, na webu na to i upozorňujeme, přesto by to ale chtělo urychleně řešit.

Nemálo nemeritorních rozhodnutí NS je následně zrušeno Ústavákem, což zkresluje statistiky advokáta (má pak například minus bod u NS, plus bod u ÚS a následně plus bod u NS).

Je tedy třeba:
- z webu NS vycrawlovat další metadata, a to ta, která se nachází v tabulce obsažené v hlavičce (někdy tam je, někdy není) - viz například 30 Cdo 3463/2014
- pokud je v tabulce "výsledek" roven "zrušeno" (měly by tam být 3 stavy - odmítnuto, zamítnuto, zrušeno - ale až bude vycrawlováno, chtělo by to samozřejmě ověřit), zrušit přiřazení daného rozhodnutí advokátu, ale ponechat jej v databázi
(- původně jsem navrhovala zobrazování hlášky na stránce případu o tom, že toto rozhodnutí jsme nepřiřadili, protože bylo zrušeno, to by asi bylo také dobré, ale v prvotní fázi to nechme stranou)

**Comment by tpapouskova** [comment]
Tak to uděláme jinak. Od NS budeme získávat seznam rozhodnutí, která byla v určitém roce zrušena. Seznamy za roky 2012 až 2016 dám na Drive, jakmile je přepíšu do rozumného formátu (pak Tě pingnu). Budeš tedy dělat totéž, co Radim - dostaneš seznam spisovek a zajistíš zohlednění jejich zrušení v databázi. Žádná úprava crawleru.

**Comment by tpapouskova** [comment]
Přepsáno, je to na drivu (ve složce NS, "17_10_12_zrušená rozhodnutí NS 2012-2016").

**Comment by tpapouskova** [comment]
Přeřazeno na @xorelvistor . Moc prosím, v případě tohoto seznamu (ale raději i těch dvou ostatních) se ujisti, že opravdu jako zrušené označíš všechny sp. zn. v seznamu, některé mohou být v chybném formátu (přepisovala jsem to ručně), tak si kdyžtak vyhoď nějakou hlášku a pak to nějak pořeš.

**Comment by repli2dev** [comment]
@tpapouskova @xorelvistor přeformulováno do programátorské řeči: importovací tool nemá vytvářet spisovky když neexistují, ale vyhodit je jako chyby na výstup.
