### ISSUE TITLE
neměli bychom informovat o použití cookies kdy používáme GA?

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#176]
Nejsem si úplně jistá, jak Google Analytics fungují, ale neměli bychom v případě jejich používání návštěvníky upozorňovat, že používáme cookies (viz upozornění, co se teď vyskytují na všech webech - právní důvod tohoto jevu kdyžtak v případě potřeby dohledám)?

**Comment by repli2dev** [comment]
Nemyslím si, my používáme sledování návštěvnosti, ale návštěvníky neprofilujeme sledováním na ostatních webech. Navíc je otázka jestli má daná legislativa v česku závaznost (když jsem se díval posledně, což už je notnou chvilku, tak neměla).

https://www.vzhurudolu.cz/blog/36-eu-cookies

**Comment by ondruska** [comment]
Co alespoň že slušnosti? Byl bych pro dotaz k souhlasu a teprve se souhlasem použít GA viz https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out

**Comment by tpapouskova** [comment]
Tome, co Ty na to? Šlo by to naimplementovat? Příp. co Ty soudíš o potřebnosti implementace vůbec?

**Comment by tomvej** [comment]
Co se týče potřebnosti (právní závaznosti), věřil jsem článku, který
odkazoval Honza. Potřeboval bych k tomu udělat výzkum.

Co se týče pracnosti: Není problém to vypnout, problém je, aby v
okamžiku, kdy to uživatel odsouhlasí, odeslalo to data, která byla
doposud zablokována. Tzn. hrozí, že nebudeme mít téměř žádné
statistiky.

Co se týče slušnosti k uživateli: Z pohledu uvědomělého uživatele jsou
tyhle lišty strašně otravné a omezují použitelnost webu. Co se týče
"obyčejných" uživatelů, nejsem si jistý, jestli takovou informaci
ocení.

Takže za mě bych počkal na výsledek analýzy a ideálně to tam nedával,
pokud nebudeme muset. Pokud to chcete vypnout než budu mít čas se na to
podívat, tak prosím.

**Comment by tpapouskova** [comment]
Souhlas, tedy prozatím nevypínáme, potřebnost vypnutí a podrobnosti k
implementaci probereme na schůzce.

Dne 17. září 2017 20:53 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm
Výjimka by se měla týkat jen first-party cookies (which are set by the web server of the visited page and share the same domain).

https://www.hobo-web.co.uk/eu-privacy-directive-google-analytics-minimally-intrusive-unlikely-to-get-you-into-trouble/
Google sice tvrdí, že jejich cookies jsou first-party, což ale podle mě není úplně pravda, protože jejich doména není doménou stránky, kterou uživatel navštíví. Na druhou stranu, tenhle typ cookies se nepovažuje za moc nebezpečné.

Pak je tam ještě jeden právní pohled: https://brianclifton.com/blog/2012/06/11/google-analytics-and-the-new-eu-privacy-law-3/
Tedy, že dokud GA neshromažďuje nějakou PII (personally identifiable information), je to v pohodě.

Pak je tam ještě tohlencto: http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf
Kde "First party analytics" jsou mezi explicitně nevyňatými. Podle dalšího textu by mohlo stačit upozornění, že je používáme, anonymizace a možnost opt-out.

Takže, nevím, pořádně tomu nerozumím. Kdybych si přečetl jen tu první stránku, tak bychom tam souhlas měli mít. Nejsem si jistý, na čem se zakládají další právní analýzy. Nebo jestli se od té doby něco nezměnilo.

_Nechci, aby to vyznělo, že jsem na někoho z vás naštvaný, jen chci říct, že tenhle výzkum mě značně nebaví a frustruje._

**Výsledek:** Asi záleží jak moc kryté zadky chceme mít. Řekl bych, že bychom souhlas měli mít, ale ty cookies nejsou ty nebezpečné cookies, proti kterým je to právo je určeno. Pokud chcete pokračovat v právní analýze, knock yourselves out.

**Comment by tpapouskova** [comment]
Tím, že jsi se do analýzy pustil, jsi se stal odborníkem. Takže rozhodnutí (a jeho následná implementace) je zcela ve Tvé kompetenci.

Chápu, že bys potřeboval podpořit/poradit, ale momentálně do dané problematiky nemá nikdo větší vhled než Ty. Takže hurá do přijetí zodpovědnosti za samostatné rozhodování : ).

**Comment by tomvej** [comment]
To je právě to, co jsem nechtěl (připomeňte mi, abych se příště o takové věci nehlásil). Navrhuju dvě možnosti:

1. Přidáme do "O projektu" sekci s tím, jaké údaje sbíráme (např. github to má podobně).
2. Pokud se bojíme, že by nás s tím mohl někdo popotahovat, dáme tam odsouhlasení (asi v kombinaci s tím prvním).

______________________________________________________________

**Comment by tpapouskova** [comment]
Tome, rozhodni. Samozřejmě Tvé rozhodnutí je rozhodnutím spolku, nebudeme
ho na Tebe házet, ukáže-li se jako špatné. Já osobně teď ale nemám kapacity
ani důvody Tvé rozhodnutí (ať už bude jakékoliv) zpochybňovat. Takže (za
mě) - měli jsme možnost ověřit si, že nekecáš, ale místo toho jsme se
rozhodli Ti věřit. Protože Tě známe. Stejně jako vy mně věříte, že bychom
měli vyhrát případné soudní spory, já Tobě věřím, že to vyřešíš správně.

Dne 9. října 2017 15:05 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Ok, omlouvám se, že to tak řeším, v tomhle si jsem fakt nejistý.

Rozhodnutí: Přidám sekci o privacy do "O projektu". A explicitní získání souhlasu budu řešit jako future věc.

**Comment by repli2dev** [comment]
@tomvej za mě je zvolené řešení OK. Každopádně netřeba se omlouvat, ona nejistota není jen v našem případě, ale je tak spíš jemně řečeno celoevropská...
