### ISSUE TITLE
případy nelze manuálně otagovat

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#178]
Obešla jsem nemožnost vyhledat sp. zn. ÚS v manuálním tagování tím, že jsem si dané případy narozporovala přes web. Ve výčtu rozporovaných rozhodnutí se mi již zobrazí, nicméně v detailu k nim nelze přiřadit nové tagování (ta šedá liště je neklikatelná).

**Comment by tpapouskova** [comment]
Tak dnes mi nejde ta šedá liště rozkliknout ani u jiných případů (NS, NSS), ještě včera NSS fungovalo (NS nevím). Tak třeba mi jen něco uniká...

Vzhledem k tomu, že teď úplně nemám, jak zareagovat na stížnosti, má toto issue prioritu č. 1 :)

**Comment by repli2dev** [comment]
Problém souvisí s minifikací javascriptu... ta selhává.

@tomvej Potřeboval bych povýšit gulp-uglify na 3.0.0, ale dostávám od NPM hlášku:
```
- uglify-save-license@0.4.1 node_modules/uglify-save-license
czech-lawyers@ /Users/jan/Projekty/DATOS/czech-lawyers
├── UNMET PEER DEPENDENCY chai@4.1.2
├── gulp-less@3.3.2 
├── gulp-uglify@3.0.0 
└── merge2@1.2.0 

npm WARN chai-immutable@1.6.0 requires a peer of chai@>= 2.0.0 < 4 but none was installed.
```
Tohle jsou tvoje závislosti a nechci ti to rozbít (+ té hlášce úplně nerozumím), poradíš?

**Comment by tomvej** [comment]
Jo, tenhle warning by měl být v pohodě. Pokud ti to funguje i přes ten
warning tak ok. Pokud ne, tak je třeba ponížit chai na trojkovou verzi
a případně vyřešit další konflikty verzí. Nic z toho by nemělo ovlivnit
aplikaci, týká se to testovacích skriptů, takže pokud proběhne npm
test, je všechno v pořádku.

Bohužel se tomu teď, ani o víkendu nemůžu věnovat.

**Comment by repli2dev** [comment]
@tomvej už jsem k tomu taky došel... no každopádně uglify knihovna každopádně nefunguje (zmrší výstup tak, že pak hází syntax chyby).

**Comment by repli2dev** [comment]
Minifikaci jsem vypnul, při příštím nasazení by to mělo naběhnout ok.
