### ISSUE TITLE
Získávání informací o advokátech z ČAKu

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#18]
- [ ] Rozmyslet si možnosti pravidelného získávání dat z ČAKu. Nabízí se:
  - posílání e-mailové žádosti o informace - to by mělo být uděláno co nejvíce automaticky
  - stahování dat z webu (API asi neexistuje?)
- [ ] implementace
  - Tak jako tak je potřeba alespoň jednou za měsíc získat aktuální data.
- [ ] Nasazení
  - Od nějakého data se v pravidelných časových interval získají data z ČAKu a nahrají se do databáze.

**Comment by tpapouskova** [comment]
žádost o informaci nám odmítnou (vyzkoušeno), takže jediná cesta je pravidelné stahování z webu

frekvenci bych nastavila stejně jako u soudních crawlerů na týden

**Comment by xorelvistor** [comment]
Jediným "problémem" je to, že data z ČAKu se musí vždy stáhnout všechna, řazení je snad podle abecedy, ale nelze poznat nový záznam. Pokud se budou uchovávat předchozí záznamy, lze porovnávat podle ID daného záznamu a zpracovat jen ty které přibyly. Byla by i možnost uchovávat si jen ID záznamu v nějakém seznamu a ne celé karty advokáta (HTML), ale rozdíl v režii bude asi stejný.

**Comment by papousek** [comment]
To by neměl být až tak velký problém. Otázkou je, jak dlouho bude trvat jeden běh získání dat.

**Comment by xorelvistor** [comment]
Prvotní běh trvá zhruba 3 hodiny (tj. cca 16000 záznamů), každý další běh bude trvat minimálně 8 minut (jen projití všech stránek) + doba potřebná ke stažení nových záznamů a následná extrakce...myslím, že do 15 minut s přehledem. :-)

**Comment by papousek** [comment]
@xorelvistor Mas nekde k dispozici ten crawler a stazane zaznamy?

**Comment by xorelvistor** [comment]
`/home/radim/cak/cak_download.py` a výsledky jsou ve složce `test`. A co nejdřív se to pokusím hodit na Github

**Comment by papousek** [comment]
@xorelvistor Zkus to prioritne hazet na GitHub. Je to pak radove jednodussi se na to mrknout,

**Comment by xorelvistor** [comment]
[Tak tady to je](https://github.com/datoszs/the-czech-bar-association), teda bez těch výsledků.
