### ISSUE TITLE
Prověřit nsčr != nscr u NS

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#180]
Vypadá, že tam máme obojí, je otázka jestli pak nejsou duplicitní.

**Comment by tpapouskova** [comment]
Myslím, že to s tímto souvisí - narazila jsem na to, že na webu to při vyhledávání "29 nscr 54/2012" vyhodí dva výsledky "29 NSČR 54/2012" a "29 Nsčr 54/2012", ačkoliv správně bychom měli mít v databázi jen jeden záznam (ten první), jelikož NSČR = NSCR = nscr = Nsčr atp.

**Comment by repli2dev** [comment]
Dotaz: `select * from "case" c1
cross join "case" as c2 where unaccent(lower(c1.registry_sign)) = unaccent(lower(c2.registry_sign)) AND c1.id_case != c2.id_case` říká že problém se týká 1398/2 případů. 

Od soudu dostáváme `NSCR` odkud se berou varianty s `Č` netuším. každopádně to sjednodím (což ale chvilku zabere, na to je navázané celkem dost věcí) a upravím normalizátor, aby tohle bral v potaz.

Preferovaná varianta je `nscr` pro ukládání v db a `NSČR` při zobrazení, je to tak?

**Comment by tpapouskova** [comment]
presne tak (ad preferovana varianta)

diky moc

Dne 2. 1. 2018 21:27 napsal uživatel "Jan Drábek" <notifications@github.com

**Comment by repli2dev** [comment]
Investigace: špatné spisovky s č se k nám dostali z oficiálních dat od soudu v jedné dávce.

Mám připravenou úpravu `CausaUnifier` skriptu, má to však ale trochu zádrhelů v případě slučování:
 - Data od soudu, datum rozhodnutí, datum podání -- momentální přístup je takový, že pokud je hodnota jednoho z těchto polí u zůstávajícího záznamu prázdné a původní záznam to měl, pak se vloží hodnota z původního záznamu.
 - Dokumenty -- přemigrují se všechny.
 - Disputace -- přemigrují se všechny.
 - Tagování advokátů/výsledků -- musí se vložit znovu, protože kvůli optimalizacím jsme si zakázali změnu případu. Vloží se k původnímu datu, kdy ono tagování proběhlo. Což je problém, protože tak může dojít ke stavu, které nechceme: překrytí správné tagování nesprávným, dvojí lidské tagování.
 - Musíme auditovat, že jsme změnili osobní údaj (tagování), nicméně jen na té úrovni aby to bylo dohledatelné.

V tomto případě dokumenty problém nejsou (nemají), disputace také ne (nemají), tagování zkusím ověřit SQL dotazem.

**Comment by tpapouskova** [comment]
Přiznám se, že tak úplně nerozumím problému (možná je to úbytkem mozkových
buněk v šestinedělí :), páč taggování stávajícím algoritmem by vždy mělo
vést ke správnému výsledku a ruční taggování by se mělo automaticky
zachovat. Bude imho lepší vysvětlit si to na schůzce...

Dne 4. ledna 2018 17:31 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Vyjasněno na schůzce, jde o to, že dovyvinutá utilita pro slučování může vést k špatnému tagování dočasnému/trvalému kvůli sloučení různě proložených tagování (které můžou být i finální).

Obšírně jsem to popsal a nakonec i spustil, jediný případ byl problém a to `29 NSČR 54/2012`, ten jsem opravil ručně na tvoje tagování... následně jsem pak spustil NS tagování aby opravilo případné dočasné problémy s tagováním.
