### ISSUE TITLE
Tag pro označení jazyka je špatně

### ISSUE THREAD

**Issue by ondruska** [datoszs/czech-lawyers#182]
Jestli koukám správně, tak jediná dostupná jazyková verze je česky #181

**Comment by repli2dev** [comment]
@tomvej postaráš se o to?

**Comment by tomvej** [comment]
Jo, podívám. Nějak jsem na to nemyslel a nebo jsem se domníval, že to je jazyk html tagů (jako u XML).

**Comment by tomvej** [comment]
Uzavřeno v #181
