### ISSUE TITLE
Nejednoznačné jméno advokáta

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#183]
Pracuji s předpokladem, že hláška o "stejnojmenných" advokátech by měla být přítomná u všech advokátů daného jména.

Tady to tak není:
 - https://www.cestiadvokati.cz/advocate/2392 - hláška je přítomna
 - https://www.cestiadvokati.cz/advocate/7516 - hláška chybí

**Comment by repli2dev** [comment]
@papousek tohle vypadá spíš jako chyba frontendu, protože v API ty data jsou:
https://www.cestiadvokati.cz/api/advocate/7516
https://www.cestiadvokati.cz/api/advocate/2392
