### ISSUE TITLE
odpřiřadit rozhodnutí NSS zrušená bez náhrady

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#187]
Některá rozhodnutí NSS zrušená Ústavákem nejsou přemazána "novým výsledkem". Advokátu tedy zůstává přiřazen "starý" výsledek, který již ale de facto neexistuje.

Na Drivu ve slozce NSS - importovane tabulky je tabulka "nss_DATOS_EXPORT_odpriradit_zari_2017". Potřebovala bych zajistit, aby u daných sp. zn. došlo k odpřiřazení případně přiřazeného advokáta + aby se u případů s danými sp. zn. na webu zobrazila hláška "Rozhodnutí není přiřazeno žádnému advokátu, protože bylo zrušeno.".

Podobně bude třeba postupovat pokaždé, když od NSS dostaneme nový seznam takových sp. zn. (budeme jej dostávat spolu se jmény advokátu, tj. 1 krát za 1/4 roku). Chce to tedy nějaké stabilní řešení (proto assignuju všechny, nejen Radima, aby se o řešení dalo diskutovat).

Já osobně navrhuji:
- přidat do tabulky "case" sloupec "anulled" a vyplnit tam například "yes", když se daná "registry_sign" matchne se spisovkou v mnou zasílaném seznamu
- vytvořit podmínku, že když je v tabulce "case" ve sloupci "anulled" "yes", v tabulce "tagging_advocate" se do sloupce "advocate_id" vyplní NULL a do sloupce "status" se uvede "processed"
- do tabulky "vw_case_for_advocates" se zpropaguje sloupec "anulled" z tabulky "case" a kdykoliv v něm bude "yes", Tom na webu zobrazí příslušnou hlášku

Ještě něco: Potřebovala bych nějak ověřit, že zrušené rozhodnutí se v budoucnu nepřemazává novým (tj. že nám NSS poskytlo správnou tabulku). Při nacrawlovávání nových rozhodnutí z webu NSS by se tedy měla objevit hláška, kdykoliv se tam narazí na sp. zn., která je "anulled".

**Comment by tpapouskova** [comment]
Na schůzce jsme se shodli, že případ bude dál přiřazen advokátu, jen se mu nebude počítat do žádných statistik. Z toho @xorelvistor vyplývá, že je třeba ještě udělat nové razítko "Zrušeno", aby ho @tomvej mohl dát na dlaždici rozhodnutí zobrazovaného i nadále na stránce advokáta (ale nezohledňovaného ve statistikách, tudíž ani v časovém grafu v sekci Případy).

Hláška na stránku zrušených rozhodnutí: "Zjistili jsme, že toto rozhodnutí bylo zrušeno [rozhodnutím ...]*. Do statistik advokáta, kterému je přiřazeno, ho tedy nezapočítáváme."

* máme-li uloženo v databázi, jinak se vynechá

**Comment by tpapouskova** [comment]
@repli2dev Ještě jedna poznámka, dost klíčová pro návrh dlouhodobého řešení. Může se stát, že rozhodnutí, které zrušilo jiné rozhodnutí, je následně samo zrušeno, tudíž to původně zrušené se "obnovuje". (V našich podmínkách se to stávat nebude, ale kdybychom někdy chtěli rozšiřovat mimo tři vrcholné soudy, bude to relevantní.)

**Comment by repli2dev** [comment]
@tpapouskova přesně jak díš, tohle je klíčové, protože to říká, že zrušenost případu není vlastností případu, ale vlastností celého sporu... tedy ji nelze mít u případu (bez zbytečné technické komplikovanosti obnovování případů), ale je potřeba mít zrušující údaje extra a následně z toho počítat stav zrušenosti.

**Comment by tpapouskova** [comment]
Nevím, ale imho by bylo nejjednodušší prostě dodat podmínku, že je-li
zrušující rozhodnutí taky annulled, zrušené rozhodnutí se jako anulled
neprojevuje.

Zrušenost není vlastností celého sporu, ale konkrétní sp. zn. Mám-li
hierarchické soudy A, B, C, D, může nastat situace, že D zruší C, které
rušilo B, které potvrzovalo A. Tudíž i nadále platí A a B. C pak bude
jednat znovu a může B ponechat v platnosti a navrhovatel se již na D
neobrátí. Tudíž nakonec bude platit A a B a C.

Dne 21. října 2017 9:43 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Není to jednodušší, protože se ti to může řetězit, přesně jak říkáš a to už není jednoduchá podmínka.

Tím, že je to vlastnost sporu jsem měl namysli právě to, že zrušenost je stav řetězce ve které je někde zahrnuta daná spisová značka.

**Comment by tpapouskova** [comment]
Ok.

Asi mi pak jen nějak laicky popiš konkrétní navržené řešení (jak se to tedy
bude ukládat do databáze), abych se nad tím mohla znovu hluboce zamyslet.
Děkuji!

Dne 21. října 2017 10:22 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
! Pozor, změna je konfliktní s `wip-125`, musí se začít implementovat až po ní.

Můj návrh (beroucí v potaz poznámku @tpapouskova):

1. Zavést tabulku `case_annulment` se sloupečky: `id` - primární klíč, `annuled_case` - povinný cizí klíč do tabulky případů, `annuling_case` - nepovinný cizí klíč do tabulky případů, `inserted`, `modified`, `job_run_id`. Tabulka bude mít unikátní klíč složený z `annuling_case` a `annuled_case`.

2. Udělat obecný importer (asi po vzoru importeru oficiálních dat), který naimportuje dodané CSV do této tabulky. Existující páry bude ignorovat, nové páry bude přidávat. Pokud spisovka nebude existovat bude to vypisovat na chybový výstup, v takovém případě se nic neprovede (dokud nedojde k nápravě, pravděpodobně chybná data).

3. Udělat nové view `vw_computed_case_annulment`, které bude počítat, které případy jsou zrušené. Momentálně by měla stačit implementace, že se vezme vše z dané tabulky... Pokud bychom měli složitější hierarchii bude potřeba toto view upravit (dát tam TODO), tak aby bralo v potaz správnou změnu stavu (viz terčiny příklady).

4. Upravit `API\CasePresenter` a `API\CaseSearchPresenter`, přidat sloupec `tagging_result_annuled` a `tagging_result_annuling_id_case`.

5. Upravit `AdvocateCasesPresenter` přidat sloupec `annuled` a `annuling_id_case`

6. Upravit pohled počítající skóre advokátů `vm_advocate_score`, pravděpodobně dalším JOINem (byla by možnost přidat vypočítanou zrušenos i do `vw_case_for_advocates`, ale ten se používá na docela dost místech, kde to úplně není potřeba...

7. Upravit počty případů jednotlivých advokátů (zde je i otázka další sloupce v detailu advokátů), týká se `API/AdvocatePresenter` pole `statistics` a možná i `court_statistics`, totéž `API/AdvocateResultsPresenter` a `AdvocateSearchPresenter`.

Snad jsem na nic nezapomněl.

**Comment by tpapouskova** [comment]
Za mě souhlas.

Dne 21. října 2017 10:40 Jan Drábek <notifications@github.com> napsal(a):

**Comment by xorelvistor** [comment]
@repli2dev Chápu správně, že musím ještě založit `model` a `services` pro `annulment`, nebo se to dá někam přidat?

**Comment by repli2dev** [comment]
@xorelvistor chápeš správně.

**Comment by xorelvistor** [comment]
@repli2dev Mohl by ses mrknout na commity  ve větvi `wip-187-annulment` nedaří se mi to nějak zakomponovat do API - nedaří se mi  získat  `id` z `case_annuling` a `case_annuled` příčemž ostatní  údaje ze záznamu v tabulce  `case_annulment`(`inserted, job_id, id`) se mi daří získat. Možná je nějaká chyba v definici modelu.

**Comment by repli2dev** [comment]
Nějaké obecné poznámky:

**Comment by tpapouskova** [comment]
Radime, pripadne dalsi zahrnuti, jak to s tim odprirazovanim rozhodnuti vypada?

Vzhledem k nekolikrate posunovanemu odhadu nasazeni a taky k pondelnimu jednani na UOOU by bylo dotazeni tehle veci opravdu super.

Diky,T.

**Comment by repli2dev** [comment]
@tpapouskova, @xorelvistor přehodil dodělání (úprav ohledně skóre) a CR na mě, takže se čeká na mě -- já mám teď ale hodně málo času, takže do pondělí se k tomu spíš nedostanu :/

**Comment by tpapouskova** [comment]
ok, tak to se neda nic delat, na UOOU se primo na toto ptat asi nebudou...

Dne 22. 11. 2017 7:53 napsal uživatel "Jan Drábek" <notifications@github.com

**Comment by tomvej** [comment]
Zkoušel jsem u sebe začít něco dělat a přestal mi fungovat BE:
>  Repository 'App\Model\Annulments\AnnulmentRepository' does not exist.

**Comment by xorelvistor** [comment]
koukám, že teď jsou tam dvě složky `app` a `App` a v každé je část, mohlo by to být tím

**Comment by tomvej** [comment]
jj, je to tím, správně je "App"

**Comment by xorelvistor** [comment]
jo, v configu jsou cesty s App

**Comment by tomvej** [comment]
Ok, za mě je to pravděpodobně hotové.

**Comment by repli2dev** [comment]
Jen poznámka, správně je `app` ve filesystému a v `App` v namespacu, takže poprosím @xorelvistor o úpravu.

**Comment by xorelvistor** [comment]
@repli2dev 
Nešlo by to opravit v rámci merge #220 do masteru? Ta chyba totiž v masteru není...ne?

**Comment by repli2dev** [comment]
1. Opravil jsem problém s `App` na `app`, bohužel to znamená, že takhle větev končí (nelze to rozumně v těch difech opravit) a vytvořil jsem novou `wip-187-annulment-fixed`.

2. @xorelvistor dodělej, prosím, importer -- momentálně je nehotový a zbytečně komplikovaný, protože vycházel z copy paste.

3. Udělal jsem všechno ostatní ze svého komentáře až na bod 7., ten dneska nezvládám. Sloupečky jsou `tagging_result_annuled` (resp. `annuled`) a `tagging_result_annuled_by_id_cases`/ (resp. `annuled_by_id_cases`) a ještě jsem přidal `tagging_result_annuling_id_cases` v případu `/api/case/`.

**Comment by repli2dev** [comment]
Je to zamergováno a nasazeno. Ten, kdo máte data, můžete importovat.

**Comment by xorelvistor** [comment]
Naimportována data za NSS a ÚS (celkem 2 soubory)

**Comment by tpapouskova** [comment]
Mohu-li se zeptat, jaký je zde stav? Chybí tedy jen naimportovat NS
(tabulka je na GD)?

A je to již na produkci, tedy mám změnit text v sekci O projektu?


2018-02-04 20:23 GMT+01:00 Radim Jílek <notifications@github.com>:

**Comment by xorelvistor** [comment]
Popravdě jsem netušil, že máme data i od NS, při vývoji jsem to nezkoušel....
Každopádně, když jsem to teď zkusil naráží to na problém normalizace spisové značky NS - který jsme asi zatím nikde nemuseli řešit, jestli se mýlím tak mě oprav @repli2dev - jde o to, že na vstupu máme něco jako `33 Cdo 1111/2014-159` ale případ je uložen pouze pod `33 Cdo 1111/2014` tedy nedojde k jeho vyhledání. @tpapouskova Jinak data ostatních soudů jsou naimportována na produkci, takže podle mě se můžeš pustiti do úprav textu.

**Comment by repli2dev** [comment]
Také jsem netušil, že taková data máme... Každopádně tohle je dotaz na @tpapouskova, mám ty přílepky `-xxx` odstranit? Co vlastně znamenají?

**Comment by tpapouskova** [comment]
ty prilepky delaji ze sp.zn. cislo jednaci (identifikator dokumentu v ramci
pripadu)

pro nase ucely je lze

diky moc

Dne 9. 2. 2018 8:06 napsal uživatel "Jan Drábek" <notifications@github.com>:

**Comment by repli2dev** [comment]
@tpapouskova provedeno... Nicméně vznikl z toho task #227.
