### ISSUE TITLE
odpřiřadit zrušená rozhodnutí ÚS

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#188]
Jakmile se shodneme na způsobu řešení issue #187, bude třeba tento implementovat i pro ÚS (na Drivu je tabulka ve složce ÚS-importovane tabulky s názvem us_odpriradit_zari_2017).

(Tady se jen nelekni, krom jedné sp. zn. jsem to už odpřiřadila ručně a tagging advokáta označila jako final.)

Na rozdíl od NSS není třeba sledovat, jestli se při nacrawlovávání nových rozhodnutí neobjevilo nové rozhodnutí pod "zrušenou" sp. zn., na ÚS věci neobživují pod stejnou spisovkou.

**Comment by tpapouskova** [comment]
(Tady jen poznámka - až to budeš mít hotové, pingni mě, vzhledem k nové shodě na řešení problematiky - že rozhodnutí zůstanou advokátům přiřazena, jen se nebudou zohledňovat ve statistikách - budu muset ručně popřiřazovat rozhodnutí zpět advokátům, protože, předpokládám, když je tam teď tagging final, samo se to nepřetaguje.)

**Comment by repli2dev** [comment]
@tpapouskova ping back... Je to stále relevantní?

**Comment by tpapouskova** [comment]
Relevantní to bylo, právě jsem nicméně ručně popřiřazovala zpět advokátům, takže zavírám.
