### ISSUE TITLE
Dořešit auditování pro open data + zveřejnit data

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#189]
Úkol, ten zní jasně. Papi má připraveno zveřejňování .csv souboru s našimi daty na webu. Je tedy třeba dořešit logování těch, kdo si soubor stáhnou, a pak vytvořit podtránku, na kterou se to šoupne.

**Comment by repli2dev** [comment]
Připravil jsem to ve větvi `wip-189-open-data`, odkaz frontend získá dotázáním `/api/download-export`, ten provede zalogování do auditovacího logu. Je potřeba jej upravit tak, aby zprostředkoval odkaz na daný dump (s tím, že dumpy by měli mít nepredikovatelné adresy, aby nešly stahovat přímo bez audit logu bez alespoň jednoho přístupu via API).

Nyní je to tedy k pokračování na @tomvej.

**Comment by repli2dev** [comment]
Ještě je k zamyšlení, zdali nechceme udělat logování všech stažení, reálně by to nebylo až tak složité, jen bych místo odkazu rovnou vracel obsah (případně komplikovaněji přes handle + další request), ale potřebuji vědět jak velké soubory to jsou (protože v nějaké formě musí protéct přes PHP).

**Comment by tpapouskova** [comment]
Honzo (Papi), tohle je asi otazka na Tebe.

Dne 14. října 2017 16:11 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Upravil jsem to za použít rozšíření Apache XSendFile, takže soubor pošle namísto PHP přímo Apache, nicméně musí být správně nastavená XSendFilePath ve VirtualHostu na absolutní cestu k projektu /storage/exports (kde by měly přijít exporty)... Na serveru je to nakonfigurované pro devel i produkci.

Díky tomu už stahování velkých souborů není problém, takže jsem to mohl předělat na jednorázově použitelné odkazy a každé stažení se tak loguje.

Zbývá tedy napojit automatický exportovač do složky a detekovat správně nejnovější export v dané složce. Což je na @papousek

**Comment by papousek** [comment]
@repli2dev Mám script, který do `storage/export` nahraje *.zip soubor (nakonec má jen pár MB, funguje komprese) a *.json s nějakými metadaty, viz `/var/www/html/czech-lawyers-devel/storage/export`. Složku pro export čístím tak, že tam jsou vždy soubory za maximálně 2 exporty. Cron ještě není hotový, to udělám během tohoto týdne.

Chceš po mě ještě něco? Myslím, že detekci toho, jaký je nejnovější export, by mělo dělat to tvé API. Případně to mohu zapsat do nějakého souboru, například `storage/export/latest.json`, v kterém by něco takovéto:

```json
{
   "data": "cestiadvokati-2017-10-24.zip",
   "meta": "cestiadvokati-2017-10-24.meta.json"
}
```

**Comment by repli2dev** [comment]
@papousek výborně... preferuji variantu přes `storage/export/latest.json` (ať nespoléhám na sort nebo čas modifikace), doimplementoval jsem to a mělo by se to chytnout. Dočasně jsem na develop nasadil tuto větev.

@tomvej teď je to na tebe, cesta pro api je `/api/download-export`, vrátít JSON s `link` klíčem.

**Comment by papousek** [comment]
Pridal jsem do scriptu vytvoreni souboru `latest.json`. Az to bude nasazeny, nastavim cron.

**Comment by papousek** [comment]
@repli2dev Jeste mozna jeden dotaz. Proc to /api/download-export/ vraci adresu a ne rovnou ten soubor?

**Comment by papousek** [comment]
@repli2dev Chapal bych, kdyby se pomoci toho tokenu nejak limitovalo mnozstvi soubeznych stahovani, ale to se nedela.

**Comment by repli2dev** [comment]
@papousek když o tom přemýšlím tak jediným důvodem asi bylo to, že jsme chtěli zalogovat poskytnutí odkazu, což jsme si vyvrátili jako nevhodnou cestu.

Takže se to může stáhnout rovnou, což předělám já... Díky za upozornění :-)

**Comment by repli2dev** [comment]
Zjednodušeno a zamergováno (spěchá)...

@papousek je ještě potřeba to zapnout i pro produkci (zatím jsou tam pro test data co byly na developu).
