### ISSUE TITLE
Vytvořit staging prostředí

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#19]
- [x] založit samostatného databázového uživatele a databázi
- [x] rozchodit subdoménu pod cestiadvokati.cz

**Comment by repli2dev** [comment]
@xorelvistor @papousek  Založil jsem uživatele `advokati-devel-rw` a vytvořil staging prostředí na [devel.cestiadvokati.cz](https://devel.cestiadvokati.cz).

**Comment by papousek** [comment]
@repli2dev Díky.
