### ISSUE TITLE
Přesunout web na novou doménu

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#190]
Doménu ospravedlnosti.cz máme zaregistrovanou a spolu s podstránkou oadvokatech.ospravedlnosti.cz schválenou ze strany ČAK. Nejsem si jistá, jestli opravdu čekat, až budeme mít novou verzi webu, protože to vypadá spíš až na začátek listopadu. Tedy navrhuji udělat vstřícný krok a web přesunout již nyní (důvodem, proč jsem vás přiřadila všechny, je diskuse nad tímto návrhem). Na stávající doménu bych pak vyvěsila info, že "Na základě jednání s Českou advokátní komorou byl vzhledem k zavádějící povaze názvu této domény web přesunut na ...", a po určitém čase by pak došlo k automatickému přesměrování. Tím zároveň dáme vědět, že s ČAK konstruktivně jednáme.

**Comment by tomvej** [comment]
Co se týče informace o přesměrování. Existuje `document.referrer` header, který se dá zcela jednoduše přečíst. Stačí tedy aby se při přesměrování správně nastavil (popř. mám dojem, že prohlížeče ho správně nastavují, takže možná stačí checknout, že se správně nastavuje).

**Comment by repli2dev** [comment]
@tpapouskova + @papousek zvládnete nastavit DNS nové domény aby ukazovala stejně jako stará? Nebo se někde s @tpapouskova potkám?

**Comment by papousek** [comment]
@repli2dev DNS nastavime, pripravis prosim konfiguraci httpd pro novou domenu (vcetne ssl  certifikatu)? Bylo by zaroven fajn, kdybys sem hodil i direktivu pro presmerovani (to ale neni nutne, to uz bych nejak stvoril).

**Comment by tomvej** [comment]
@tpapouskova Hodily by se mi potom nějaké podklady:
* Jak mám změnit texty? Nebo se o to postaráš?
* Jak má vypadat to upozornění o změně domény? Má to být modální okno (["dialog"](https://react-bootstrap.github.io/components.html#modals))? Uzavíratelný [alert](https://react-bootstrap.github.io/components.html#alerts) někde navrchu stránky? Nebo alert jako modální okno? Jaký to má mít text?

**Comment by repli2dev** [comment]
@papousek konfiguraci připravím, ale abych to nedělal na slepo, tak potřebuji nasměrovanou doménu.

**Comment by papousek** [comment]
@repli2dev Testovat to jde pres `/etc/hosts`, ale jdu to nastavit.

**Comment by papousek** [comment]
@repli2dev Zmena se uz projevila.

**Comment by tpapouskova** [comment]
@tomvej Prosím o modální okno (vyskočí na uživatele, který na ospravedlnosti.cz přijde z cestiadvokati.cz) s tímto textem "Na základě vzájemné dohody s Českou advokátní komorou byl obsah webu cestiadvokati.cz přesunut (z důvodu tvrzeně zavádějící povahy názvu původní domény) na novou doménu ospravedlnosti.cz, a to, prozatím, bez dalších změn. Web zpřístupňující statistiky o vystupování českých advokátů před soudy nicméně v budoucnu hodláme neustále graficky i obsahově vylepšovat."

Ad další texty. Bude jen nutné v sekci O projektu nahradit jedinou zmínku cestiadvokati.cz a v sekci Kontakty upravit e-mail. Na úvodce bych si pohrála (velikostně) se spojením "web O spravedlnosti vám přináší data O ADVOKÁTECH" nebo tak nějak, tady to nechávám na Tvé fantazii a estetickém cítění.

**Comment by repli2dev** [comment]
Směrování nastaveno...

Nové domény jsou `oadvokatech.ospravedlnosti.cz` a `oadvokatech-devel.ospravedlnosti.cz`, měly by fungovat i bez HTTPS (přesměrování na HTTPS). Dále pak servisní `adminer.ospravedlnosti.cz`.

Staré domény jsou přesměrovány a to tak, aby případná adresa za doménou zůstala zachována. Když to otestujete budu rád (protože prohlížeče to kešují a prakticky to nejde obejít).

Jediné k řešení pro @tpapouskova je to jak se má chovat hlavní doména `ospravedlnosti.cz` (resp. `www.ospravedlnosti`) - momentálně je tam redirect na advokáty.

**Comment by repli2dev** [comment]
@papousek pro maily budu potřebovat nastavit SPF + DKIM:

MX: přenastavit, aby ukazoval na `mail.cestiadvokati.cz`.
SPF: TXT záznam, viz cestiadvokati.cz `cestiadvokati.cz.	3600	IN	SPF	"v=spf1 mx -all"`

**Comment by tpapouskova** [comment]
Presmerovani mi funguje, jen na me zatim nevyskakuje dialogove okno.

Ad hlavní doména - redirect mi z ní nefunguje (objeví se mi stránka s
textem "DATA"). A vlastně to přináší otázku, zda obsah nehodit rovnou na
tuto hlavní doménu a pod sekundární (oadvokatech.ospravedlnosti.cz) ho
nedat až rozjedeme i další projekty (tudíž budeme pracovat s
osoudcich.ospravedlnosti.cz atp.). Šlo by to ještě? Nevím, jak moc je to
složité, tak se kdyžtak braň.

Dne 26. října 2017 8:29 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
@tpapouskova hlavní doména by měla fungovat, zřejmě jste ji na tvém počítači testovali a zůstalo ti tam uloženo to staré.

Jsem proti tomu aby to bylo na hlavní doméně:
A. je to nesystémové
B. chceme aby si uživatelé zafixovali nějaký obsah někde, tím, že jim ho budeme přesouvat toho zrovna nedosáhneme.
C. chceme aby si ho zapamatovaly i vyhledávače... navíc když bychom to přepnuli najiný obsah budeme se muset drbat se zachováním funkčnosti odkazů na přesměrovaný web (ale zároveň propustit nové).
D. Je to opruz to celé ponastavovat.

Takže za mě je opravdu nejlepší to nedělat.

**Comment by tomvej** [comment]
Dialogové okno se nezobrazuje proto, že ho budu psát až zítra. :)

Je tu ovšem drobný problém. Kontroloval jsem headery v JS konzoli a nevyplňuje se `document.referrer`. Tím pádem nemám jak zjistit, že uživatel byl přesměrován.

**Comment by tpapouskova** [comment]
Díky moc, souhlas tedy, nechme to, jak to je.

Dne 26. října 2017 14:39 Jan Drábek <notifications@github.com> napsal(a):

**Comment by tomvej** [comment]
Trápím se, trápím, předložka na začátku názvu a ještě jednopísmenná je dost hodně neestetická. Vzhledem k tomu, jak se kapitalizují nadpisy je to dost stupidní -- to velké O k sobě přitahuje moc pozornost, ale verzálky (all-caps) vypadají u toho fontu divně. Tak jsem skončil u kapitálek.

Celkově je ten název blbý, strašně dlouhý, s dvojtečkou uprostřed. Ugh. No nic, nevšímejte si mě, doufám, že se to vám a ČAKu bude líbit.

@repli2dev  Dialog implementuju na základě HTTP refereru, což je jediná možnost jak zjistit, že se to přesměrovalo (protože kupodivu, zjistit http request status stránky nejde). Ten se ale nenastavuje.

**Comment by tomvej** [comment]
Většina změn by měla být hotová. Rovnou jsem to nasadil, protože tam nebylo nic výrazného.

Je ještě potřeba změnit e-mailové adresy (nevím, na co). Jsou hadrcoded:

**Comment by repli2dev** [comment]
@tomvej tak koukám, že jsme to nedomysleli, prohlížeče to při 301 redirectu neposílají: https://serverfault.com/questions/180408/way-around-empty-http-referrer-from-301-redirect https://stackoverflow.com/questions/1398277/does-301-redirect-always-preserve-referrer

Ještě se snažím to předat do query stringu... uvidíme jak budu úspěšný.

**Comment by repli2dev** [comment]
@tomvej tak jsem to upravil, aby v případě příchodu ze staré domény přibylo v query stringu `old=1`. Zkoušel jsem upravit podmínku v `Redirect.js`, ale dostával jsem nějaké chyby v modálu.

**Comment by tomvej** [comment]
Ok, ale query string není úplně nejvhodnější, kdyby měl nějakou záložku
a přesměrovával se jinam. Ale tak, předpokládám, že to je dočasné. T.

**Comment by repli2dev** [comment]
@tomvej jasně, že není nevhodnější, ale je to skoro jediná možnost... Nenapadá mě žádná jiná, protože cokoliv co v sobě bude mít redirect, tak ti referer nezachová. Router by to měl po prvním použití zahodit a do adres to nepřidávat... A ano mělo by to být dočasné, jak to chápu.

**Comment by tpapouskova** [comment]
@repli2dev Hloupý dotaz - na jaké adrese mohu přistoupit k manuálnímu taggování? Zkoušela jsem ospravedlnosti.cz/admin , ale to asi nebylo správné. + Pokud jsi náááhodou při přesunu měnil přístupové údaje (heslo), moc prosím o jeho zaslání.

**Comment by repli2dev** [comment]
@tpapouskova oadvokatech.ospravedlnosti.cz/admin/ (subdoména + lomítko na konci)

**Comment by tomvej** [comment]
Přepsal jsem tak, aby to reagovalo na `?old=1` a nasadil na devel ... akorát to nic nedělá, resp. query se nenastavuje.

Druhá otázka, mám uživateli uložit do local storage, že už ten dialog jednou viděl a nemá se otevírat podruhé?

**Comment by repli2dev** [comment]
@tomvej v tom případě máš problém s keší, u mě to funguje perfektně. Ad druhá otázka to je na @tpapouskova, jak tvrdí chceme být v přeučování? Pokud tvrdí, tak chceme zobrazovat hlášku vždy, když z té domény přijdou.

**Comment by tomvej** [comment]
Yep, my cache to blame, už to jede. Ještě jsem uvažoval smazat to
old=1, když to odkliknou, ale ještě nemám jasno, jak.

**Comment by tpapouskova** [comment]
Tvrdi, zobrazovat imho vzdy. Diky!

Dne 30. 10. 2017 21:09 napsal uživatel "Tomáš Vejpustek" <
notifications@github.com>:

**Comment by tomvej** [comment]
@repli2dev Jak to vypadá s e-maily? Jaké se používají?

**Comment by tpapouskova** [comment]
Visí to teď bohužel na Papim, info@cestiadvokati.cz je (a bude) nicméně
stále validní, takže na webu jej zatím ponechejme a doufejme, že se Papi
rozhoupe :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-03 11:17 GMT+01:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by papousek** [comment]
@repli2dev DNS jsem nastavil, ale po pravde tomu moc nerozumim, tak si nejsem 100% jisty, ze je to spravne. Jeste ve starych DNS zaznamech mame google-site-verification token, do novych jsem to zatim nedaval.

**Comment by repli2dev** [comment]
@tpapouskova DNS je OK, nicméně to SPF a DKIM se mi nezdá nastavené (maily to tvrdí též). Google site verification není třeba. Kdyžtak to dokončíme ve středu na schůzce.

**Comment by repli2dev** [comment]
SPF + DKIM nastaveno a otestováno. Adresy `info@ospravedlnosti.cz` a `admin@ospravedlnosti.cz` lze začít používat.
