### ISSUE TITLE
Vyrobit nová razítka

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#195]
Potřebujeme ještě razítka "výhra" a "prohra". Vyrob, prosím, a zašli Tomovi.

**Comment by tpapouskova** [comment]
Pozastavuji, razítka možná nebudou potřeba (nový graf. návrh webu probereme na schůzce)

**Comment by xorelvistor** [comment]
@tpapouskova @tomvej 
Jaké barvy by mělo být razítko "Zrušeno"? Stejně jako "Zastaveno", nebo něco jiného?

**Comment by tpapouskova** [comment]
Dobrá otázka... Navrhuji černou.

2017-11-18 14:43 GMT+01:00 Radim Jílek <notifications@github.com>:
