### ISSUE TITLE
GA pro jednotlivé advokáty a případy

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#198]
Bylo by dobré zjistit, na které případy (a advokáty) se lidé nejčastěji dívají.

**Comment by tomvej** [comment]
@tpapouskova @repli2dev Čím to chceme identifikovat? Advokáty IČem a případy spisovkou?

**Comment by tpapouskova** [comment]
to by bylo ideální

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-06 14:11 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by repli2dev** [comment]
@tomvej @tpapouskova taky mi to přišlo OK, ale pak jsem si uvědomil, že někteří advokáti nemají IČ (řádově desítka případů)...

Co s tím?
a) můžeme posílat místo toho EČ, to by se taky nemělo měnit (i když těch zahraničních co pak přejdou do ČR a tudíž se jim změní EČ může být víc než těch kteří nemají IČ).
b) zajistit akorát, že když to bude prázdné, že se to nebude posílat (a tudíž zkreslovat data).

**Comment by tomvej** [comment]
Za mě jsou obě řešení v pohodě. Chěl jsem se vyhnout (ale o tom tady
nemluvíme):
1) Jménům, která nejsou unikátní.
2) Našim databázovým ID, která nejsou univerzální.

**Comment by tpapouskova** [comment]
Jsem pro cokoliv, co mi umožní zjistit, na jaké případy a advokáty se lidé
dívají nejčastěji. IČ mi přijde nejlepší, protože si ho rovnou zadám do
vyhledávání a advokáta zobrazím (kdyby se to řešilo našimi databázovými ID,
musela bych si otevřít databázi, že...). Chápu, že někteří IČ nemají (už si
bohužel nepamatuji, kdy a proč k tomu dochází), ale neřešila bych je,
pravděpodobnost toho, že se nejčastěji budou lidé koukat právě na advokáta
bez IČ mi přijde zanedbatelná. Což?

Dne 6. října 2017 23:00 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Ok, já to beru tak, že pokud je prázdné IČ, nebude se to posílat. PR upraven.
