### ISSUE TITLE
Selhání migrace

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#199]
Při vykonávání skriptu `2017-09-03-170001-user-fullnames-mandatory.sql` proces migrace (migrations:reset) selže, jelikož nejsou nastaveny `fullname` systémových rolí, které jsou uloženy v databázi a tento skript nastavuje `NOT NULL`.
Nejsem si úplně jist, jestli je řešením vytvořit nový skript migrace, mrkni na to prosím.

**Comment by repli2dev** [comment]
Plná jména si máš doplnit a migraci spustit znovu ;-) proto je to tam na dva skripty. Na produkčních databázích je to už opravené, takže za mě `wontfix`.

**Comment by xorelvistor** [comment]
OK, díky za informaci
