### ISSUE TITLE
Mapování jmen advokátů z rozhodnutí na jména získaná od NS

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#20]
- [ ] implementovat mapování jmen advokátů získaných z rozhodnutí na jména v prvním pádě získaná od NS
- [ ] pak navázat na Radimem již vyřešené (viz jiný issue) mapování jmen advokátů získaných ze soudů na advokáty z ČAK

**Comment by repli2dev** [comment]
Již obsolete, zavírám tedy.
