### ISSUE TITLE
Upgrade na NPM 5

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#207]
Mohli bychom na Tilionovi upgradovat NPM na verzi 5 (+ upgradovat node)? Ta verze by měla už docela stabilní, a hlavně, měla by mít deterministický build (tj. neměl by být potřeba yarn). Takže by neměly hrozit náhodné chyby při nasazování (myslím, že zatím žádné výrazné nebyly, ale stejně).

**Comment by repli2dev** [comment]
Je to tam, ale musel jsem reinstalovat nodejs i npm, takže prosím ověř, že to funguje.

**Comment by tomvej** [comment]
Podařil se mi `npm install` a deploy na devel, takže by to mělo být v pohodě. Díky.
