### ISSUE TITLE
Nenalezení existujícího případu NSS

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#216]
Případ u NSS se sp. zn. "6 azs 291/2017" nejde přes vyhledávání na webu najít. Přitom se vyskytuje v databázi (case i documents). Navíc jej lze vyhledat v ručním tagování. Magic?

**Comment by repli2dev** [comment]
Problém je v tom, že část případů má year = 0 a tudíž neproleze vw_for_advocate.

**Comment by repli2dev** [comment]
@xorelvistor tohle je na tebe... Těch rozhodnutí v databázi s rokem 0 je asi 1700... Celkem věřím odhadu, že chyba je v `CausaImport` ve funkci pro určení roku a to té první isset podmínce... která projde (je to nastaveno), ale očividně v ní není rok (ale třeba jen prázdno)...

Protože se to týká vstupu (respektive NSS/ÚS), přehazuji na tebe, protože pro mě je trochu těžké dostat se k relevantním vstupům.

**Comment by xorelvistor** [comment]
@repli2dev Problém je, že co byly přidány případy, které nemají dokumenty tak u nich není rok, protože ten se u NSS určuje z URL, kde je uložen dokument rozhodnutí. A pokud se tento případ nevyskytl ani v tabulce soudu, tak prostě nemá rok.

Jen nevím, jestli přidat případy s rokem 0 do podmínky `vw_case_for_advocates` a nebo vymyslet něco jiného?

Jestli jsem to správně pochopil, tak s rokem se stejně pracuje jen v grafu na stránce advokáta a to ještě pouze s případy, které jsou otagované - což podle mě případy, které nemají dokument (není to čím podložit) úplně nesplňují.

**Comment by repli2dev** [comment]
To že nemají dokument nás netrápí, ty případy musí být vidět, protože advokáti je chtějí rozporovat.

Krom toho, pokud se určuje z URL dokumentu, není to pak rok rozhodnutí, nikoliv případu? TO by bylo chybně.

Správné řešení je minimálně opravit podmínku aby to propadlo níže na určení roku ze spisové značky + oprava toho co už v DB je (ze spisovky) + prozkoumání jestli náhodou v tom sloupci v datech od NSS nepřichází rok rozhodnutí.

**Comment by repli2dev** [comment]
Jsem líný čekat, takže jsem to opravil teďka.

Poté co bude problém zcela vyřešen je potřeba ověřit jestli se tam ještě takové případy vyskytují a pokud ano provést:

1. Zálohu databáze
2. `UPDATE "case" SET year = (substring(registry_sign from '....$')::int) where year = 0 and court_id = 1;`

**Comment by repli2dev** [comment]
Podle mě byl problém vyřešen.
