### ISSUE TITLE
Stahování a vkládání případů bez dokumentu

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#217]
Potřeba upravit chování odkazů na [neexistující dokumenty](https://oadvokatech.ospravedlnosti.cz/public/document/view/339221) [ - případ (2 As 155/2015)](https://oadvokatech.ospravedlnosti.cz/case/229227) - ideálně u seznamu dokumentů vypsat, že text rozhodnutí tohohle dokumentu nemáme.

**Comment by tomvej** [comment]
@xorelvistor Tam je zásadní otázka: Jak poznat, že se snažím přistoupit k dokumentu, který neexistuje?

Možnost 1: Na detailu případu se vypíše, že nemáme text. Jakým způsobem to poznám? Protože nemůžu zkoušet ten dokument stáhnout a podle toho to zjistit. Takže potřebuju nějakou informaci z back-endu.

Možnost 2: Upraví se 404 na nějaké smysluplné hlášení. Jak poznám, že zrovna tohle url odpovídá dokumentu, který neexistuje? Hm, asi podle URL.

**Comment by xorelvistor** [comment]
@tomvej 
Podle dat z back-endu by se to podle mě dalo zjišťovat kontrolou `public_link`. Ten je prázdný, když k danému dokumentu nebyla nalezena URL s textem rozhodnutí. Za to `public_local_link` nebude nikdy prázdný, protože v DB jsou uložena metadata daného dokumentu, čímž vzniká záznam v tabulce dokumentů a tiše se předpokládá (bohužel), že dokument obsahuje odkaz na text rozhodnutí - do nedávna se totiž případy bez dokumentu v DB nevyskytovaly.

```json

"documents":[  
      {  
         "id_document":339221,
         "mark":"2 AS 155/2015",
         "decision_date":"2017-07-21T02:00:00+02:00",
         "public_link":"",
         "public_local_link":"https://oadvokatech.ospravedlnosti.cz/public/document/view/339221"
      },
      {  
         "id_document":200791,
         "mark":"2 AS 155/2015 - 84",
         "decision_date":"2016-03-16T01:00:00+01:00",
         "public_link":"http://nssoud.cz/files/SOUDNI_VYKON/2015/0155_2As__1500084_20160322082214_prevedeno.pdf",
         "public_local_link":"https://oadvokatech.ospravedlnosti.cz/public/document/view/200791"
      },
      {  
         "id_document":204906,
         "mark":"2 AS 155/2015 - 67",
         "decision_date":"2015-06-30T02:00:00+02:00",
         "public_link":"http://nssoud.cz/files/SOUDNI_VYKON/2015/0155_2As__1500067_20160420083855_prevedeno.pdf",
         "public_local_link":"https://oadvokatech.ospravedlnosti.cz/public/document/view/204906"
      }
   ]
```

Představoval bych si to jen jako nějaký popisek u daného dokumentu - "K tomuto dokumentu nemáme text rozhodnutí" - místo tam v tom panelu dokumentu je. ;-)

**Comment by repli2dev** [comment]
@xorelvistor za mě by mělo správně být upraveno API, aby se v případě, že dokument není nezobrazoval ani `public_link` ani `public_local_link` + ve všech situacích by mělo přibýt `has_document` s hodnotou `true`/`false`. Ať to máme explicitní... co myslíš?

**Comment by xorelvistor** [comment]
Ano, to je samozřejmě ideální řešení a nejlépe čitelné. Taky bych se primárně  vyhnul kontrole na straně FE.

**Comment by tomvej** [comment]
Ok, za mě je jedno, jestli budu kontrolovat `has_link` a nebo `public_link.length === 0`. Po domluvě s Radimem to rozpracuju na druhou variantu a pokud změníte API, tak to přepíšu.

**Comment by repli2dev** [comment]
@xorelvistor když se na to tak dívám, přemýšlím proč tam vůbec záznamy v tabulce `document` vznikají?

Crawler vrátí informaci o tom že by měl existovat dokument, k němuž ale nemá přílohu? Dokážeme pak zpětně určit, že na tento záznam v tabulce máme přidat tuto přílohu? Protože pokud ne, tak máme celkem slušný problém.

**Comment by xorelvistor** [comment]
Crawler nevrátí informaci, že by měl dokument existovat, crawler získá o dokumentu všechna metadata, ale nemá k němu přílohu. Zpětné určení by mělo být možné podle `order_number` (jednacího čísla), které je využito (jeho hodnota) jako identifikátor při vkládání dokumentů. Asi nechceme vytvářet jen záznamy v tabulkách s metadaty bez vazby na tabulku `documents`, ne? Takové chování při importu dokumentů implementované nemáme.

**Comment by repli2dev** [comment]
Přidal jsem do API /api/case/<ID> u dokumentu `is_available`, pokud je `false`, tak tam ty sloupce s cestami nejsou.

**Comment by repli2dev** [comment]
@tomvej jestli jsem nic nepřehlédl, tak je to k doimplementaci na frontendu (ve větvi `wip-217`).

**Comment by tomvej** [comment]
@repli2dev Hotovo. Terka chtěla, ať se ty dokumenty vůbec nezobrazují, tak je rovnou filtruju pryč.
