### ISSUE TITLE
Nezobrazování výsledků tagování u výsledků vyhledávání.

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#218]
Při vyhledávání případů podle spisové značky se nezobrazuje informace o tagování výsledkem (tedy ani obrázek) :-(
Je to chyba, nebo záměr? Aby se nám nehlásili jen k meritorním rozhodnutím?

**Comment by tomvej** [comment]
Jo, tak je to definitivně chyba, je to dané tím, že na dvou RESTovkách se používá jiné DTO:
* `/api/advocate-cases/` používá `result`.
* `/api/case-result/` používá `tagging_result`.

Já používám na obojí stejnou mapovací funkci (nevím, jestli se tam něco změnilo a před tím to fungovalo). Co s tím? @repli2dev Chceme sjednotit API a nebo mám připsat mapovac funkci?

**Comment by repli2dev** [comment]
@tomvej sjednotil jsem to, nyní `/api/advocate_cases` používá `tagging_result` (s tím, že `result` v rootu pro reflektovanou hodnotu, kterou to bylo filtrováno).

**Comment by tomvej** [comment]
Doplnil jsem to na FE.

**Comment by repli2dev** [comment]
@tomvej opravdu tohoto dneska zamergoval a nasadil. Zavírám to tedy.
