### ISSUE TITLE
case sensitive názvy souborů

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#219]
Máme problém s case sensitive názvy souborů. Někdo přejmenoval adresář `App` na `app` (nedaří se mi to dohledat) a zatímco vám to nejspíš funguje, já nerozjedu PHP, protože všechny reference uvnitř souborů jsou na `App`.

Otázka: Co s tím? Můžu to opravit, no problem, ale pokud se to zase bude opakovat...

**Comment by repli2dev** [comment]
Ta složka se má jmenovat `app`, uvnitř projektu jsem nenašel ani jednu referenci na `App`.

Respektive nenašel jsem ji v žádné přímo používané cestě, reálně náš projekt není PSR-4 compliant (to by jednotlivé složky namespaců museli odpovídat složkám včetně casu), my ale pro autoloading tříd naší aplikace používáme `nette/robot-loader`, který prochází složku `app`. Možná tedy pomůže smazat obsah složky `temp`, ve které si robot loader ukládá keš. Pro zbytek pak Composer.

Osobně se mi to špatně testuje, protože OS X má case insensitive systém, takže potřebuji vědět chyby.

**Comment by tomvej** [comment]
Ok, beru, že to má být app a podívám se, co má moje PHP za problém.

**Comment by tomvej** [comment]
Uzavírám, už mi to funguje.
