### ISSUE TITLE
Import do databáze

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#22]
Existuje už nějaký PHP skript ze kterého by se dalo vycházet při implementaci skriptů pro jednotlivé soudy?
Co případně udělat jeden skript a jednotlivé importy rozlišovat parametry?

**Comment by repli2dev** [comment]
Nástřel je ve větvi `wip-jobs`, má momentálně jednu vadu a to, že nebere v potaz, že jeden dokument se může vyskytnout v importech dvakrát.

**Comment by papousek** [comment]
Jen opravim, ze ta vetev se jmenuje `wip-develop-jobs`. Nechtel by ses na to, co psal Honza, podivat?

**Comment by xorelvistor** [comment]
Podívat bych se chtěl, ale prozatím se mi nedaří zprovoznit webovou aplikaci.
