### ISSUE TITLE
Odkazování na neexistující dokumenty na stránce případu

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#222]
Narazila jsem na případ https://oadvokatech.ospravedlnosti.cz/case/231410 - na jeho stránce je celá řada dokumentů, většina z nich ale po prokliku vede na neexistující stránku, jelikož text daného dokumentu nemáme v databázi (není na webu soudu dostupný).

Zdálo by se mi lepší dokumenty, ke kterým nemáme text, v tom pravém sloupci na stránce případu vůbec nevypisovat. Šlo by to?

**Comment by xorelvistor** [comment]
Řeší se v #227

**Comment by tomvej** [comment]
Fixed in #217
