### ISSUE TITLE
Prověřit proč chybí rozhodnutí

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#227]
Při importu zrušených rozhodnutí se našlo 5, které nemáme:

```
Case (annuled) with registry mark [11 tvo 5/2013] not exists.
Case (annuled) with registry mark [11 tvo 34/2013] not exists.
Case (annuled) with registry mark [29 cdo 2930/2009] not exists.
Case (annuled) with registry mark [32 cdo 3413/2009] not exists.
Case (annuling) with registry mark [i. ús 3483/11] not exists.
```

**Comment by xorelvistor** [comment]
@tpapouskova 
Taková spisovka u ÚS není, možná to mělo být `IV.ÚS 3483/11` nebo pak `I.ÚS 3483/12` či `I.ÚS 3483/13` v jiném roce se již nevyskytuje.

**Comment by tpapouskova** [comment]
@xorelvistor  a kde se ta sp. zn. vlastně vzala? Dívám se teď na tabulku zrušených rozhodnutí ÚS (GD - ÚS - importované tabulky - "us_odpriradit_zari_2017.csv") a žádná taková sp. zn. tam není....

**Comment by repli2dev** [comment]
@tpapouskova je to ze zrušených dat NS.

**Comment by tpapouskova** [comment]
Rejstřík "Tvo" nezpracováváme (jde o rejstřík, v němž se nezpracovávají dovolání, ale něco jiného), takže ty první dva chybějící případy jsou v pořádku.

U "29 cdo 2930/2009" jsem udělala překlep. Omlouvám se. Napraveno přímo v tabulce na GD.

U "32 cdo 3413/2009" jde o záhadu. Rozhodnutí není na webu NS, nicméně mělo by patrně existovat (tato sp. zn. je uvedena v materiálech poskytnutých NS i přímo v rušícím rozhodnutí ÚS).

U "i. ús 3483/11" šlo opět o můj překlep. Napraveno.

**Comment by repli2dev** [comment]
@tpapouskova provedeš, prosím, opravu i v dokumentu v importovaném dokumentu? Já jsem tam opravoval více věcí a ne všechny úpravy dokážu replikovat. Můžeš ohledně toho posledního kontaktovat NS, kde je problém? Mimojiné zde je http://kraken.slv.cz/23Cdo3413/2009 (kdyžtak ho vytvořím ručně, ať se nám ta informace uloží).

**Comment by tpapouskova** [comment]
Oprava provedena. NS kontaktuji.

**Comment by tpapouskova** [comment]
Tak NS nám to vysvětlilo - rozhodnutí  "32 cdo 3413/2009" je totožné s rozhodnutím "23 Cdo 3413/2009", které (to druhé) na webu je. Jde o chybu (správné je toliko první označení, druhé je jaksi neplatné...), nicméně její náprava je v blízkém horizontu nereálná.

**Comment by repli2dev** [comment]
@tpapouskova díky za vysvětlení a doptání... upravil jsem tedy toto rozhodnutí na spisovku, kterou máme, naimportoval znovu (a uložil na GDrive).
