### ISSUE TITLE
BUG: nekorektní zobrazování zrušených rozhodnutí na stránce advokáta

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#230]
Nevím, kde přesně se děje chyba, proto přiřazuji oběma.

Příkladmo rozhodnutí I. ÚS 131/01. Je zrušené, tato informace je správně zobrazená na jeho stránce. Nicméně na stránce advokáta, kterému předtím náleželo (Kačmařík), má dlaždice náležející tomuto rozhodnutí stále razítko "nemeritorní". Mohlo by jít buď toliko o estetický problém, nebo by to mohlo být horší a zrušená rozhodnutí by se mohla stále započítávat do statistik advokáta (což tvrdíme, že se neděje a rozhodně bychom nechtěli, aby se to dělo).

**Comment by repli2dev** [comment]
Podle mě jde o chybu u @tomvej, protože na https://oadvokatech.ospravedlnosti.cz/api/advocate-cases/8777 je
```
{"id_case":347882,"id_court":3,"registry_mark":"I. ÚS 131/01","tagging_result":"negative","decision_date":"2001-11-13T01:00:00+01:00","proposition_date":"2001-03-01T01:00:00+01:00","annuled":true,"annuled_by_id_cases":[null]}
```

A tedy případ by měl být anulován (`"annuled":true`).

**Comment by tomvej** [comment]
No, chyba je celkem jednoduchá. FE předpokládá, že dostává `tagging_result_annuled` a nikoliv `annuled`. A teď, jak následující pole vypadá:
* V `CasePresenter` je to `tagging_result_annuled`.
* V `CaseSearchPresenter` je to `tagging_result_annuled`
* V `AdvocateCasesPresenter` je to `annuled` (sic).

Můžu to přepsat, ale lidi, máte chaos v DTOčkách. Navíc, používáte pro každou obrazovku jiné DTO, což nevím, jestli je úplně dobré. Na FE používám na vyhledávání případů a případy advokáta jedno DTO. Samozřejmě, zase, můžu ho zkopírovat. Jen mi tohle nepřijde šťastné. Mimochodem, uvažovali jste o GraphQL?

**Comment by repli2dev** [comment]
Ok, sjednoceno, na daném místě to naběhlo správně. Proč to tak bylo vlastně netuším, ale bylo to tak od prvního návrhu.

Každopádně podobný problém se může potenciálně objevit i u jiných míst, protože na backendu neuvažujeme o tom jaké DTOčka si udělá frontend (nebyl pro to zatím požadavek) -- a posílat například k případu vždy všechno co v systému je, nepovažuji za moudrý (efektivní) nápad.

**Comment by tomvej** [comment]
Posílat všude všechny informace skutečně není efektivní. Proto jsem se ptal na GraphQL, kde si FE sám řekne, které informace potřebuje.

Každopádně, to s těmi DTO je v zásadě moje chyba, protože jsem předokládal, že máme standardně jedno DTO pro stránkovaná data a jedno pro detail. A přišlo mi mírně nelogické, mít pro dvě hodně podobné obrazovky (vyhledávání případu a případy advokáta) dvě rozdílné reprezentace. Každopádně, můžeme se o tom pobavit, například před přípravou nového webu. Jestli každá RESTovka má vždy jiné DTO a nebo můžeme přejít na GraphQL.

**Comment by repli2dev** [comment]
@tomvej o GraphQL jsem zatím jen slyšel, ale zatím jsem neměl čas a motivaci se na něj podívat. Pobavit se koncepčněji o API u nového webu je dobrý nápad.
