### ISSUE TITLE
Chyby v readme připojeného k exportovaným datům

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#232]
Nevím, kolik lidí si to stahuje (asi méně), přesto by bylo dobré opravit readme:
- [x] hned nadpis: odstranit cestiadvokati.cz a místo toho dát oadvokatech.ospravedlnosti.cz
- [x] v následujícím odstavci míří odkaz pod "našich stránkách" zřejmě na devel
- [x] v popisu datového souboru "Případy" chybí popis sloupce "prevent_processing" obsaženého v tomto souboru (imho je tam ten sloupec nadbytečný, pokud už tam ale je, bylo by jej dobré popsat)
- [x] v popisu typů výsledných rozhodnutí chybí "annulled" 
- [x] v popisu datového souboru "Dokumenty" chybí popis sloupce "modified" obsaženého v tomto souboru (imho je tam ten sloupec nadbytečný, pokud už tam ale je, bylo by jej dobré popsat)

A pak jsou tu 2 věci, kterým nerozumím:
- [x] v tabulce případů se nevyskytuje ani jeden případ s výsledkem "annulled", takové případy ale naprosto určitě existují a jsou advokátům přiřazeny
- [x] velmi často se objevuje advocate_id -1, asi půjde o dummy pro nepřiřazení advokátu, pokud je tomu tak, asi by se hodilo to zmínit v readme

**Comment by repli2dev** [comment]
Správně napočítané anulované případy jsou v pohledu `vw_computed_case_annulment`, kde jsou sloupce `annuled_case` s odkazem na případ, který byl zrušen, ten je vždy vyplněn. Některé případy mají i co zapříčinilo toto zrušení, to je pak ve sloupci `annuling_case` (a může být NULL).
