### ISSUE TITLE
Command "migrate-database" is not defined.

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#24]
Postupuju podle README a ted jsem u bodu:
- migrate database by running ``php index.php migrate-database``

Haze mi to tuto chybu:

```
jpapouse@theresa:~/workspace/datoszs/czech-lawyers/www$ php index.php migrate-database

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "migrate-database" is not defined.                      
                                                                  

```

**Comment by xorelvistor** [comment]
to se mi sice nestalo, ale také přidám nějaký problém do pléna
```
pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres"
password retrieved from file "C:\Users\Xorel\AppData\Roaming/postgresql/pgpass.conf"
```

**Comment by papousek** [comment]
@xorelvistor Najdi na svem systemu soubor ``pg_hba.conf`` (u mě třaba v ``/etc/postgresql/<verze>/main/pg_hba.conf`` a do něho přidej řádek

```
local   all                          <uzivatel, kterym se pripojujes k databazil>                    md5
```

**Comment by papousek** [comment]
Tak jsem to tedy nakonec zprovoznil. Aktualizoval jsem README (kam jsem pridal i jeden hack, pres ktery jsem se nedokazal jednoduse dostat: https://github.com/datoszs/czech-lawyers#troubleshooting).
