### ISSUE TITLE
Příkaz na vytvoření uživatele

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#25]
Po zprovoznění aplikace na localhostu se sice vytvoří schéma databáze a uživatelé ``system-*``, ale pro přístup k admin sekci je potřeba mít uživatele vlastního. Příkaz by měl vytvořit nového uživatele s následujícími atributy:
- jméno
- heslo
- type (viz ``app/Enums/UserType.php``)
- role (viz ``app/Enums/UserRole.php``)
- možnost přihlášení.

**Comment by repli2dev** [comment]
Hotovo, v `develop`u je comand line příkaz `app:user-create`
