### ISSUE TITLE
Missing cases

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#263]
Case (annuled) with registry mark [11 tvo 16/2020] not exists.
Case (annuled) with registry mark [29 cdo 1409/2020] not exists.

Reimport 2022-02-14-annuled.csv after fixing

**Comment by repli2dev** [comment]
11 tvo 16/2020 na NS dohledám, ale 29 cdo 1409/2020 nikoliv... můžeš @tpapouskova prověřit, proč? Pro vyřešení budu muset stáhnotu nějaký range kde ty případy byly publikovány a rád bych to udělal naráz.

**Comment by tpapouskova** [comment]
Aha, řešení je jednoduché (srov. mail k Tvému dohledání dvou sp. zn. ÚS rozhodnutí) - 29 Cdo 1409/2020 neexistuje, ÚS zrušil 26 Cdo 1409/2020, a to v systému máme.

**Comment by repli2dev** [comment]
Díky za opravu, co se týče TVO, my je IMHO vůbec neřešíme, takže jsem ten pár odstranil.
