### ISSUE TITLE
Manuální tagování v administraci

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/czech-lawyers#3]
create environment, in which an expert (tpapouskova :) will be able to manually tag court decisions and suggest new algorithms for automatic tagging

**Comment by repli2dev** [comment]
Chceme vytvořit v administraci stránku "Případy" s tabulkou případů následujícími vlastnostmi:

- Stránkovaná (100 na stránku)
- Zobrazuje: spisovou značku, soud, aktuální tagování výsledku (+ čas/stav), aktuálí tagování advokáta (+ čas/stav), počet rozporování + odkaz do detailu.
- Filtrování dle soudů
- Filtrovat na zobrazení pouze fuzzy & failed tagování (alespoň jednoho - výsledku/advokáta)
- Filtrovat na zobrazení pouze rozporovaných.

Na stránce detailu případu bude zopakovány všechny data, zobrazen v iframe dokument (lze-li)... a dole bude formulář, vložit manuální tagování: výsledek, advokát (selectize.js).

**Comment by repli2dev** [comment]
Hotovo... Počet rozporovaných se řeší samostatně v #71
