### ISSUE TITLE
US: používat "Datum publikace" místo "Data rozhodnutí" v crawleru

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#34]

**Comment by xorelvistor** [comment]
@tpapouskova  nechceme taky používat přírustky?

**Comment by xorelvistor** [comment]
první datum publikace je od roku 2007 a týká se rozhodnutí z roku 1993

**Comment by repli2dev** [comment]
@xorelvistor Pokud jsou k dispozici publikační data, tak bych používal spíše ty, protože je to flexibilnější (dá se tím pak stahovat i určité konkrétní období, či období nespojené s dneškem).

**Comment by xorelvistor** [comment]
předěláno a nasazeno
