### ISSUE TITLE
NSS, ÚS, NS: import dokumentů ze žádostí o informace

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#44]

**Comment by repli2dev** [comment]
Ze schůzky: Importer projde vstupní data a zagreguje výsledky pro jednu spisovku a zunikátní je. Poté nahradí původní data u případu novými daty.

Ignorování sloupců a explicitní pojmenování sloupců je žádané.

V případě, že daný případ v našem systému neexistuje, tak ho chceme vytvořit (situace kdy to nemá dokument, či teprve bude zveřejněn).

**Comment by repli2dev** [comment]
NS: `--skip 1 --keys "fullname|result" --delimiter ","`
NSS: `--keys "names|result" --delimiter ","`
ÚS: `--skip "4|5|6" --keys "date|surname|name" --delimiter ","`

Všechny spuštění vyžadují zvýšit memory_limit na aspoň 1024 MB.
