### ISSUE TITLE
NSS, ÚS: otagování výsledků

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#45]

**Comment by xorelvistor** [comment]
@repli2dev  @papousek 
Když chci vyhledávat záznamy  v extra dokumentech (ty specifické pro soud), musím si pro každý typ dokumentu (soudu) vytvořit ```Service```?

**Comment by repli2dev** [comment]
@xorelvistor ne, bude to součást případu (`Case`).

**Comment by xorelvistor** [comment]
@repli2dev  tak jsem vytvořil větev ```working```, kde jsou mnou upravené soubory, snad se s tím nějak popasuješ :-)

**Comment by xorelvistor** [comment]
@repli2dev , @tpapouskova 
Objevil jsem nekonzistenci dat v dabázi pro Ústavní soud. Spisové značky získané pomocí crawleru obsahují zpravidla první číslo vyjádřené římskou číslicí či nějakou zkratkou (pak to asi není číslo), ovšem data získaná od soudu vyjadřují toto číslo arabskou číslicí. Při ručním importu dat ze soudů je tedy vytvořena úplně nová spisová značka, ke které ovšem není vázán žádný dokument. Několik příkladů to snad vysvětlí lépe:
(přímo z naší DB)
| id_case    | registry_sign | inserted | job_run_id | court_id  |
| 150222  |  pl ús 17/94    | 2016-12-01 19:38:24 | NULL | 3 |
| 142988  |  pl.ús 17/94    | 2016-10-22 13:53:34 | 868 | 3 | (crawler)
| 143267  | iv.ús 17/94 |	2016-10-22 13:53:37| 868| 3 | (crawler)
| 150126 | 4 ús 17/94 | 2016-12-01 19:38:24 | NULL | 3 |

tento fakt mi potvrdilo vyhledávání nalusu, které akceptuje oba dva tvary a navíc ignoruje tečky.

**Comment by tpapouskova** [comment]
Jj, na to jsem narazila i já při zpracovávání dat pro svou disertaci. Omlouvám se, že jsem na to pak zapomněla a neupozornila.

Já to vyřešila jednoduchým nahrazením (gsub) "4 ÚS" za "IV. ÚS", aby se to sjednotilo. Předpokládám, že bude třeba toto udělat v rámci nahrávače tabulky od ÚS do systému (Honza?).

Ještě jednou - omlouvám se.

**Comment by repli2dev** [comment]
Správné řešení je: kanonizovat spisovou značku do jednoho tvaru pomocí toho co na to používáme a pak opravit konzistenci databáze (nikoliv upravovat nahrávače, či crawlery). Založil jsem na to samostatné issue #49.

**Comment by repli2dev** [comment]
Bump, #49 vyřešeno.

**Comment by papousek** [comment]
@xorelvistor Už je tohle hotové?
