### ISSUE TITLE
NSS, ÚS: otagování advokátů

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#47]
Přiřazení oficiálních dat soudů k danému případu (```case```) a to v případě, že oficiální data obsahují jen 1 jméno.

**Comment by xorelvistor** [comment]
@papousek , @repli2dev, @tpapouskova 
Snažím se definovat, co přesně vlastně budu dělat a trochu  si nevím rady, jak to skloubit s naší databází.

příklad vstupních dat:
```
7 tdo 646/2009 [{"result": "DOPLNĚNO", "fullname": "Mgr. Gavlasová Jana"}]
8 azs 9/2013 [{"names": "Švandrlík Pavel, JUDr., advokát", "result": "odmítnuto"}]
```
databázová tabulka
```
CREATE TABLE tagging_advocate (
  id_tagging_advocate BIGSERIAL PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES document(id_document) ON UPDATE CASCADE ON DELETE RESTRICT,
  advocate_id BIGINT NULL REFERENCES advocate(id_advocate)  ON UPDATE CASCADE ON DELETE RESTRICT,
  status tagging_status NOT NULL,
  is_final BOOLEAN NULL,
  debug TEXT NULL,
  inserted TIMESTAMP NOT NULL DEFAULT NOW(),
  inserted_by BIGINT NOT NULL REFERENCES "user"(id_user) ON UPDATE CASCADE ON DELETE RESTRICT,
  job_run_id BIGINT NULL REFERENCES job_run(id_job_run) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ON tagging_advocate(document_id);
CREATE UNIQUE INDEX ON tagging_advocate(advocate_id);

COMMENT ON TABLE tagging_advocate IS 'Entries containing tagging of documents to advocates with their history (last inserted tagging of certain document is considered valid).';
COMMENT ON COLUMN tagging_advocate.status IS 'Status of tagging, see its states.';
COMMENT ON COLUMN tagging_advocate.is_final IS 'Set to true when created by flawless human.';
COMMENT ON COLUMN tagging_advocate.job_run_id IS 'ID of job run which added this tagging.';
```

co by měla obsahovat položka ```document_id``` odkaz na jaký dokument? Z dodaných informací nejsem schopen určit, ke kterému dokumentu ono jméno patří. A tvrzení, že patří k dokumentu, podle kterého jsme určili výsledek případu nemusí být pravdivé, nebo se mýlím? Možná je vše v pořádku a moje dotazy vychází z nedostatečného pochopení tabulek a vazeb v databázi (na reálný svět), pak se tedy ptám nemrknul by se na to se mnou někdo?  O tom, že pro přiřazení ```advocate_id``` je potřeba ořezat a vyčistit vstupní data a následně je po částech porovnat až někdy jindy.

**Comment by repli2dev** [comment]
Původně jsme počítali s tím, že jedno konkrétní otagování se bude vázat na konkrétní dokument, protože z něj bude udělané -- důvod je pragmatický -- laditelnost, chceme vědět, z jakého dokumentu to tagger usoudil.

Situace se tedy změnila (s daty od soudů jsme nepočítali), takže bych tu vazbu uvolnil (umožnil ji být NULL), ale nechal bych ji tam, protože v některých případech výše uvedené je stále relevantní (NS například).

**Comment by xorelvistor** [comment]
@papousek @repli2dev 
No jo, ale pokud bude informace o dokumentu NULL, tak se tam bude muset zákonitě objevit odkaz na případ ('case_id'), jinak to nebude vůbec přiřaditelné. Nebo je nějaké lepší řešení?

**Comment by repli2dev** [comment]
@xorelvistor ano, musí se tam objevit `case_id`, protože to je to k čemu to taggování se děje.

**Comment by papousek** [comment]
@xorelvistor Je tohle hotové?

**Comment by xorelvistor** [comment]
nasazeno na server a běží...trvá to :-(
cca 2000 záznamů za 1 hodinu

**Comment by papousek** [comment]
@xorelvistor Co se stalo?

**Comment by xorelvistor** [comment]
no tak pokud se to má výrazně urychlit, tak to nemůžu považovat za hotové, ne?

**Comment by papousek** [comment]
aha :-)

**Comment by xorelvistor** [comment]
- [X] Nasazeno
- [x] Spuštěno - NSS: 0:07:04, ÚS: 0:16:00
- [ ] Crontab plán

**Comment by repli2dev** [comment]
Načasuj to nějak vhodně po stahování... nechám to na tobě.

Ono to asi s bude vyžadovat kompletní reorganizaci až rozjedeme i produkci, ale to budeme řešit až před ten most přijdeme :P
