### ISSUE TITLE
Kanonizovat spisové značky od ÚS + opravit konzistenci

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#49]
Kvůli #45 je potřeba kanonizovat spisové značky od ÚS do jednotné formy a následně napsat jednorázový task, který projde celou databázi a výsledky sjednotí.
 
@tpapouskova:

- [ ]  Definuje formát (`iv.ús 90/96` vs `4 ús 90/96`)

**Comment by tpapouskova** [comment]
Sjednotme to na IV. ÚS ... (pac toto bychom pak meli zobrazovat na webu, protoze v teto forme to pravnicka verejnost zna)

**Comment by repli2dev** [comment]
Vyřešeno. Opravil jsem to ve funkci `Normalize::registryMark` a přidal skript, kdybychom museli upravovat spisovky i v budoucnu.

**Comment by repli2dev** [comment]
Statistika: `Renamed 56894 cases, merged 3125 cases and ignored 0`

**Comment by papousek** [comment]
super!
