### ISSUE TITLE
Informace o soudu v detailu ImportCausa

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#50]
Zobrazení informace, kterého soudu se import dat týkal.

**Comment by repli2dev** [comment]
Je dostačující když to bude ve zprávě/výstupu?

**Comment by xorelvistor** [comment]
Jo, to bude stačit. A ještě mě v souvislosti s tím napadlo, že by nebylo špatné řadit ```Pravidelné úlohy``` podle data ```posledního běhu``` (nejnovější nahoře).

**Comment by repli2dev** [comment]
Zavedeno, spolu s tím, že celý výstup se nově ukládá do DB.

Řazení jsem též zavedl, jen je volitelné (mě například nepřijde moc užitečné).
