### ISSUE TITLE
Statistiky tagování výsledků soudů

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#51]
Statistika o tom kolik máme pro jednotlivé soudy případů, zgrupovaný podle výsledků (positive/negative/neutral/unknown).

Úkolem je to provést, dát sem výsledky i patřičný dotaz.

**Comment by repli2dev** [comment]
Tenhle dotaz by měl najít poslední poslední tagování pro každý případ daného soudu (`1` = NSS, `2` = NS, `3` = ÚS).

```
SELECT case_result, COUNT(*) FROM "case" JOIN (
    SELECT DISTINCT ON (case_id) * FROM tagging_case_result ORDER BY case_id, inserted DESC
) AS last_taggings ON "case".id_case = last_taggings.case_id
WHERE court_id = 2
GROUP BY case_result
```

NSS:
```
"neutral";2693
"positive";24691
"negative";8119
"unknown";41
```

NS:
```
"neutral";4235
"positive";22295
"negative";44765
"unknown";198
```

ÚS:
```
"neutral";208
"positive";704
"negative";6125
"unknown";35
```

**Comment by tpapouskova** [comment]
Mohla bych poprosit o výsledky po jednotlivých letech (přičemž rok beru
podle data rozhodnutí)?

Takhle dojmově se mi kdysi zdálo, že to sedí, ale přece jen by asi bylo
lepší ověřit to oproti ročenkám jednotlivých soudů...

Díky!

2017-01-12 20:50 GMT+01:00 Jan Drábek <notifications@github.com>:
