### ISSUE TITLE
Statistiky úspěšnosti tagování advokátů

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#52]
Statistiky o tom, k jakému procentu případů v systému máme informaci o advokátu + ideálně už i statistiky o maximálním a minimálním počtu případů v systému přiřazených jednomu advokátu.

Provést, výsledek i dotaz přiložit sem.

**Comment by xorelvistor** [comment]
Je to dost jednoduše, ale představu si z toho lze udělat (jestli jsem tedy pochopil zadání...).
```
Celkem pripadu: 187010
Pripadu prirazeno advokatum: 48947
Maximalni pocet pripadu prirazeny jednomu advokatovi: 524
Minimalni pocet pripadu prirazeny jednomu advokatovi: 1
```
```
select
concat('Celkem pripadu: ','',celkem_pripadu),
concat('Pripadu prirazeno advokatum: ','',prirazeno_pripadu),
concat('Maximalni pocet pripadu prirazeny jednomu advokatovi: ','',max(t.cnt)),
concat('Minimalni pocet pripadu prirazeny jednomu advokatovi: ','',min(t.cnt))
from 
(select count(distinct(case_id)) from tagging_advocate) prirazeno_pripadu,
(select advocate_id, count(advocate_id) as cnt from tagging_advocate group by advocate_id) AS t,
(select count(*) from "case") celkem_pripadu
group by 1,2
```

V databázi se zatím nové přiřazení nezobrazují, dokud trochu nepohnu s tou rychlostí.

**Comment by repli2dev** [comment]
Poslední řádek je kind-of-obvious ;-) Reálně tam ale má být 0, vzhledem k těm nepřiřazeným případům).

Představoval jsem si to nikoliv souhrnně, ale po jednotlivých soudech:
`NSS: X případů, Y otagovaných advokátem, advokát s největším počtem přiřazených případů Z (A)`

Jinak ten tvůj dotaz mi přijde, že funguje jen v případě, kdy má každý případ nanejvýš jedno otagování advokáta... V opačném případě `(select advocate_id, count(advocate_id) as cnt from tagging_advocate group by advocate_id)` vrací bogus, protože vezme v potaz i tagování, která nejsou poslední.

**Comment by tpapouskova** [comment]
Hele, co vlastně brání v dokončení tohoto?

Pro další komunikaci (nejen se soudy) potřebuji mít v ruce čísla
- konečných rozhodnutí (sp.zn.) v systému (celkem, NS, NSS, ÚS)
- s otagovaným výsledkem (nominálně či případně % z celkem, NS, NSS, ÚS)
- s otagovaným advokátem (nominálně či případně % z celkem, NS, NSS, ÚS)

Geniální by bylo to mít po jednotlivých letech (přičemž rok beru ze sp.zn.,
nikoliv podle data rozhodnutí).

2017-01-12 20:15 GMT+01:00 Jan Drábek <notifications@github.com>:

**Comment by repli2dev** [comment]
@xorelvistor v rámci tohoto tasku, prosím, založ dokument s dotazy na statistiku, ať je máme kde najít v případě budoucích analýz.

**Comment by xorelvistor** [comment]
na Google disku založen [dokument](https://docs.google.com/document/d/1JGrri7tFQzSSb_QXhkKWIlpS3Az8zwoppFVn1fHSi6Q/edit) s dotazy

**Comment by xorelvistor** [comment]
Terka napsala:

Potřebovala bych ještě další 2 dotazy:
1) Všechny případy daného soudu otagované výsledkem A ZÁROVEŇ advokátem.

2) Nějaký megadotaz, který mi všechny předchozí 4 dotazy (ty první tři Tvoje + ten požadovaný mnou) projede pro každý soud pro každý rok a vyplivne mi nějaké .csv či něco takového s výsledkem.
Konkrétněji, potřebovala bych tabulku s řádky 1992-2017.. a sloupci "ÚS celkem" "ÚS s výsl" "ÚS s adv" "ÚS s výsl a adv" "NS celkem" "NS s výsl"...

**Comment by xorelvistor** [comment]
ten první by mohl vypadat asi takto:
```
select 'Otagováno výsledkem i advokátem' as info, count(*)
from vw_latest_tagging_case_result a
join vw_latest_tagging_advocate b on a.case_id = b.case_id
where a.case_id in (select id_case from "case" where court_id = ?);
```
ovšem dost záleží na tom, jestli bereš v potaz otagování advokátem, které skončilo **failed** (tento dotaz bere vše)

**Comment by tpapouskova** [comment]
Pro tento (! i ostatní !) dotazy, prosím, logicky ber jen ÚSPĚŠNÁ tagování
(tedy, tuším, processed a is_final), tj. taková, která jsou smysluplná z
hlediska návštěvníka webu.

2017-04-22 1:08 GMT+02:00 Bc. Radim Jílek <notifications@github.com>:

**Comment by tpapouskova** [comment]
V rámci zaškolování do SQL jsme s Papim udělali (viz GoogleDrive). Tedy zavírám, příště snad již budu schopna dotazy tvořit sama...
