### ISSUE TITLE
Import advokátů selže

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#57]
```
[Nextras\Dbal\UniqueConstraintViolationException]                                           
  ERROR:  duplicate key value violates unique constraint "advocate_remote_identificator_key"  
  DETAIL:  Key (remote_identificator)=(54220cb9-ab1a-4f17-ba2c-b8487ceeb239) already exists.
```

**Comment by repli2dev** [comment]
Daný člověk 54220cb9-ab1a-4f17-ba2c-b8487ceeb239 je " Sven Andreas Höbel", v současných datech má EČ (identification_number): "50182" a IČ (registration_number): "02326281"... V nových datech, je EČ "17417" a IČ stejné.

Importer používá EČ ke kontrole unikátnosti, protože IČ může být i prázdné...

Můžeš @xorelvistor ověřit proč se změnilo EČ? Nevíš o tom @tpapouskova něco? Pokud to není chyba někde jinde, budeme muset párovat nová a stará data pomocí remote_identificator.

**Comment by xorelvistor** [comment]
V ČAKu je  uvedeno jen nové evidenční číslo (17417), to původní prý neexistuje. Zajímavé je, že ```remote_identificator``` zůstal stejný. Původní evidenční číslo je uvedeno i v logu crawleru z 30. ledna. Takže nějaká změna na straně ČAKu.

**Comment by repli2dev** [comment]
Díky, vypadá to tedy, že budeme muset spoléhat na `remote_identificator`.

**Comment by tpapouskova** [comment]
Pomůže vám nějak, když do ČAKu napíšu a zeptám se?

Očekávám, že napíšou něco jako "tohle se rozhodně nestává, někde jsme asi
udělali chybu, ale rozhodně je ojedinělá...". Anebo taky ne, že...

T.

2017-02-08 8:40 GMT+01:00 Jan Drábek <notifications@github.com>:

**Comment by repli2dev** [comment]
Zeptat se můžeš. Obecně potřebujeme nějaký identifikátor, kterým určíme, že to co jsme stáhli z ČAKu teď je stejný advokát jako ten, který už máme...

Konkrétně se můžeš zeptat, jestli se EČ či identifikátor z adresy může někdy pro jednu osobou změnit (s tím, že IČO obecně ne, ale po vyřazení je nulové, takže vlastně ano)... a u EČ jsme narazili na právě zmíněného pána.

Díky

**Comment by tpapouskova** [comment]
Tak je to takto.

EČ se u českého advokáta nikdy nemění. Problém nastal v případě, kdy byl
advokát do seznamu ČAK zapsaný jako zahraniční advokát (dostal EČ ze
zahraniční řady) a následně splnil podmínky a stal se českým advokátem
(bylo mu přiděleno nové EČ z české řady). Takových případů jsou prý
jednotky.

Pro nás to tedy asi znamená spoléhat se na remote identificator. Případně
tyhle "jednotky" případů nějak odchytat "ručně".

T.

Dne 8. února 2017 10:45 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Provedl jsem to tak, že se prvně hledá existující advokát podle EČ, když se nenajde, tak podle remote identifikátoru... Pokud tam uspěje, upraví se dané EČ.

Spolu s tím jsem upravil importovací skript tak, aby nám výstup běhu uložil do databáze.
