### ISSUE TITLE
NS: otagování advokátů

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#58]

**Comment by repli2dev** [comment]
Přidal jsem kontrolu vyextrahovaného textu (chci aby tam bylo 2-7 slov), což už to vcelku hezky ořeže o ty divné případy. Nicméně to vypadá, že advokáti (namátkově kontrolováno) se vyskytují až 2015+, do té doby spíše sporadicky.

Statistiky NS:
- Počet případů NS: `83921`
- Počet dokumentů k případům NS: `58366`
- Počet případ NS, které mají alespoň jeden dokument: `57865`
- Počet případů bez dokumentu: `26056`

Statistiky tageru advokátů:
- Počet otagovaných: TBD
- Trvání běhu tageru (cca 40 minut)

Otázky:
 - Ukládám jako `failed` kde jsme extrahovali jméno, ale nedokázali ho spárovat s advokáty (0, >1 shod)... je to chtěné?
 - Má smysl ukládat tagování (bez advokáta) jako `failed` i pro ty, které nemají žádný dokument?
 - Má smysl ukládat tagování (bez advokáta) jako `failed` i pro ty, které mají dokument, ale z žádného jsme nedokázali vyparsovat advokáta?

**Comment by repli2dev** [comment]
@tpapouskova 

Potřeboval bych zodpovědět otázky v předchozím příspěvku a zkontrolovat namátkově sestavený soubor případů, které náš tagger nedokáže zvládnout 
[ns-advocate-failed.txt](https://github.com/datoszs/czech-lawyers/files/779646/ns-advocate-failed.txt) (je to CSV, ale GitHub nedal tu příponu) abychom věděli, že něco nepřehlížíme.

-----

Statistika spisovek končích 2016: uspěl na `1595`, neuspěl na `1751`
Statistika spisovek končících 2015: uspěl na `2943`, neuspěl na `3188`
Statistika spisovek končících 2014: uspěl na `3058`, neuspěl na `3183`
Statistika spisovek končících 2013: uspěl na `2563`, neuspěl na `2637`
Statistika spisovek končících 2012: uspěl na `2170`, neuspěl na `2576`
Statistika spisovek končících 2011: uspěl na `2562`, neuspěl na `3036`
Statistika spisovek končících 2010: uspěl na `2720`, neuspěl na `3089`

**Comment by tpapouskova** [comment]
Ukládám jako failed kde jsme extrahovali jméno, ale nedokázali ho spárovat s advokáty (0, >1 shod)... je to chtěné?
-> ano, nedokázali jsme případ přiřadit k advokátu, takže fail

Má smysl ukládat tagování (bez advokáta) jako failed i pro ty, které nemají žádný dokument? Nebo by to měl být spíš ignored?
-> tady by to chtělo asi delší debatu, myslela jsem spíš, že když to ještě nemá žádný dokument, do taggování to ani nejde...i když u Tdo (kde nejsou dvě strany sporu) můžeme taggovat rovnou z tabulky od NS i bez dokumentu

Má smysl ukládat tagování (bez advokáta) jako failed i pro ty, které mají dokument, ale z žádného jsme nedokázali vyparsovat advokáta? Nebo by to měl být spíše ignored.
-> určitě failed

**Comment by tpapouskova** [comment]
Dotaz - u Tdo taguješ podle dokumentu od soudu, je-li tam u jedné spisovky konzistentní advokát (tj. není-li jich tam více), že? (Domlouvali jsme se na tom kdysi v srpnu mailem, ale na GH nemůžu nikde dohledat, že bychom to specifikovali v nějakém issue..)

**Comment by tpapouskova** [comment]
Seznam zkontrolován. 

Přehlížíme, IMHO, iniciály advokátů - někdy jsou uvedeny a měly by Ti stačit k dohledání toho správného advokáta v dokumentu od soudu. Netuším ale, kolik to pokryje případů (tedy jestli stojí za to to řešit).

+ Přehlížíme naprosto zásadní věc - my známe jména advokátů, jen nevíme, který je který (který z více je advokátem dovolatele). Z dokumentu tedy vlastně nepotřebujeme tahat celé jméno advokáta, ale jen informaci o tom, kdo byl vlastně dovolatelem. Pak by nám stačil dokument od soudu, ovšem za předpokladu, že by tam byly uvedeny (stejně jako je tomu zpravidla v těch rozhodnutích) iniciály účastníků (a tedy i dovolatele). Jsem trubka, že jsem si toto neuvědomila dřív (věděla jsem, že celá jména účastníků nám nedají, ale nenapadlo mě se ptát po iniciálech, které beztak uvádí ve veřejném textu rozhodnutí). Teď jsem napsala na NS, jestli by nám ten seznam rozšířili, uvidíme... Sorry!!!

**Comment by repli2dev** [comment]
1. Udělat tagování pro TDO (právě jeden advokát v oficiálních datech -> přiřazení), předtím ověřit jestli je to +- OK.
2. Udělat prematch advokáta vůči výsledkům od soudu (jsou-li) + přidat do Matcheru advokátů první kontrolu na shodu (jméno už je v prvním pádě).

**Comment by repli2dev** [comment]
Ad 1. vyjel jsem si statistiku počtu záznamů od soudu u jednotlivého případu:

```
1	17408
2	1095
3	235
4	54
5	31
6	10
7	12
8	1
9	4
10	1
```

Tedy asi 90 % TDO spisovek má právě jednoho advokáta u sebe uvedeného. Vzorek z ostatních  příloze [tdo-multiple-advocates.txt](https://github.com/datoszs/czech-lawyers/files/785999/tdo-multiple-advocates.txt)... 10 % mi přijde celkem hodně na to, že nám může něco unikat -- je nějak způsob jak si být jistější (názor dalšího právníka, prozkoumání vzorku,...? )

**Comment by tpapouskova** [comment]
Jsem přesvědčena, že tentokrát nám nic neuniká - více advokátů u jedné Tdo
spisovky se objeví za situace, kdy dovolání podávají spoluobvinění. A
myslím, že (když to hodně zjednoduším) 10 % trestných činů rozhodně může
být spácháno ve spolupachatelství.

T.

Dne 19. února 2017 17:53 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Každopádně, nejvíce pomohlo tagování TDO... párování jmen pomocí iniciálů za pomocí dat ze soudů se zdá být málo (cca stovka).

```
Skupina: processed, failed
vše:	37601, 46320
2016: 2045, 1301
2015: 4166, 1965
2014: 3596, 1604
```

**Comment by repli2dev** [comment]
Hotovo i na develu... zabralo to 46 minut i zde.
