### ISSUE TITLE
Integrovat seed front-end projekt

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#59]
Je třeba zaintegrovat seed front-endu do repa -- pravděpodobně do nějaké složky, protože nette používá package.json a gulp.

**Comment by repli2dev** [comment]
V jaké podobě to bude?

Jedna základní HTML stránka + složka s frontend JS?

Jinak gulp tam je čistě jako preprocesor pro JS, CSS a věcí okolo, takže klidně použij pro svůj frontend.

**Comment by tomvej** [comment]
Hm, je fakt, že by se to bít nemuselo -- dependencies by měly mít prázdný průnik. Akorát kdyby se něco do budoucna změnilo, může být trochu problém to vysekat.

Jako seed používám https://github.com/tomvej/redux-starter, z čehož
* src můžu přejmenovat na frontend,
* tools můžu přesunout dovnitř,
* .eslintrc můžu přesunout dovnitř,
* webpack.config.babel a .babelrc se s ničím nebijí,
* zbytek tam je nadbytečný.

**Comment by repli2dev** [comment]
+1

Navíc všechny ty závislosti NPM jsou tam jen kvůli tomu preprocesoru, naše aplikační (~ nette...) závislosti jsou provedeny pomocí Composeru (`composer.json`)... takže směle do toho :-)
