### ISSUE TITLE
Upravit front-end deploy proces

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#60]
Ze zdrojáků se generují bundlované soubory -- index.html, bundle.js a style.css.
* Kam je dát? Do www?
* Mají být v gitu?

**Comment by tomvej** [comment]
Implementační poznámka: Bude třeba přidat hash nebo raději chunkhash do názvů kvůli cache prohlížečů.

**Comment by repli2dev** [comment]
`www/assets` s tím, že že s index.html to bude složitější, protože budu muset vymyslet způsob jak to zpřístupniit API i tenhle index.html.

Ad implemetační poznámka: buď commit hash (nezkrácený), nebo zkrácený (ale ne truncatem, ale pomocí git utility!), nebo build timestamp (uložený někam).

**Comment by tomvej** [comment]
Spíše bych použil https://webpack.github.io/docs/long-term-caching.html, kde je v názvu checksum souboru -- je to rovnou podporované a nemusím vymýšlet, jak to udělat. Můžu tam ještě hodit soubor version.txt, který bude obsahovat build timestamp a commit hash.

**Comment by repli2dev** [comment]
Jako pokud s tím nebude muset nijak pracovat aplikace tak klidně... na jiném projektu jsme řešili problém toho, že s tím musí pracovat i aplikace na backendu a tam by pak musela být mapa soubor = version... To ale tady není potřeba a tedy i version.txt by měl být vlastně zbytečný.

Dávat to do názvu souboru či cesty je no-go, poněvadž to pak způsobuje failování požadavků, respektive minimálně v settingu, že jsou stejným způsobem ošetřeny i obrázky (což by měly být). Lepší je `script.js?blablabla`.

**Comment by tomvej** [comment]
Build front-end aplikace vygeneruje statický content:
* index.html
* bundle.js
* styles.css
(+ soubory s obrázky a fonty)

Browser obdrží index.html, ostatní soubory jsou referencovány v hlavičce. Předpokládá se, že všechny budou ve stejné složce, je celkem jedno, které.

Ideální je, aby se příliš nespoléhalo na jejich názvy, protože:
1) Může se stát, že tam soubory přibudou a bylo by pohodlnější je neřešit (třeba budeme optimalizovat)
2) Kvůli cache v prohlížeči by bylo ideální aby všechny soubory až na index.html v názvu obsahovaly svůj md5 součet, čímž se zaručí, že když se změní, uživatelé jsou donuceni si je načíst znova.

**Comment by repli2dev** [comment]
Provedeno... Nyní se provede při nasazení (via deploy.php) npm script build a všechny soubory z dist se přesunou do www/frontend... 

.htaccess směrování je nastaveno tak, že se nejprve pokouší request uspokojit jako soubor, pak jako soubor v frontend složce (jen vybrané přípony) a pak se všechno hodí na index.html (aby fungovalo history API).

**Comment by tomvej** [comment]
Super, oceňuju, že ses díval na history API, to jsem zapomněl zmínit. Hlavně, ono to není poznat, dokud nezkusíš refresh. :)

Čistě technicky, frontend to mohl rovnou házet do konkrétní složky (output/path v webpack configu), ale důležité je že to funguje. Ještě tam zkusím zavést ty chunkhashe.

**Comment by repli2dev** [comment]
Klidně to změň :)
