### ISSUE TITLE
Zavést .editorconfig

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#61]
Když nás na repu pracuje více, nemuselo by být od věci zavést [editorconfig](http://editorconfig.org/), na styl kódu (hlavně odsazení).

**Comment by repli2dev** [comment]
@tomvej Zavedeno, přidej si tam část pro `.js`, `.css` a případně další věci, které budeš používat.

@xorelvistor čas nainstalovat .editorconfig plugin ;-)
