### ISSUE TITLE
REST: Vyhledávání advokátů

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#62]
URL (návrh): `/advocate?query=string`
Parametry:
* query -- vyhledávací řetězec (jméno advokáta/IČO)

Vrátí stránkovatelný seznam advokátů obsahující následující informace:
* Id (kvůli URL),
* IČ,
* jméno (jméno, příjmení, titul),
* sídlo (asi by stačilo město),
* stav (aktivní, pozastavený, ...?)
* statistiky (počet meritorních/nemeritorních/zastavených, ...)

**Comment by repli2dev** [comment]
URL bude: `/api/advocate/search[/<query>/[<start>-<count>]]`

Schéma:
```
    [
        {
            "id_advocate": 123,
            "identification_number": 11223344
            "fullname": "JUDr. Ing. Petr Omáčka, PhD.",
            "residence": {
                "street": "Pod mostem",
                "city": "Brno",
                "postal_area": "602 00"
            },
            "state": "active",
            "matched": {
                "type": "ic",
                "value": "11223344"
            },
            "statistics": {
                "negative": 12,
                "neutral": 2,
                "positive": 59,
            }
        }
    ]
```
