### ISSUE TITLE
REST: Statistiky advokáta

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#64]
URL (návrh): `advocate/:id/results/?court=string`
Pro daný soud (NS, NSS, ÚS, pokud není zadán tak všechno dohromady) vrací počet meritorních/nemeritorních/... případů v každém roce.

**Comment by repli2dev** [comment]
@tpapouskova tady je diskutabilní, co to znamená v každém roce... Dá se to dělat podle data rozhodnutí a podle čísla spisovky (`/2016`)

**Comment by tpapouskova** [comment]
Ha, pravda, číslo spisovky bude asi lepší

(uživatele zajímá, jak často se v určitém roce advokát rozhodl obrátit na soud, i když sám moc dobře věděl, že to bude zbytečné)

**Comment by repli2dev** [comment]
Provedeno...

Adresa: `/api/advocate-results/<advocate>[/<court>]`

Odpověď:

```json
    {
        "id_advocate": 123,
        "id_court": 2,
        "years" : {
            '2014': {
                "negative": 12,
                "neutral": 2,
                "positive": 59,
            },
            '2016': {
                "negative": 10,
                "neutral": 0,
                "positive": 5,
            },
        }
    }
```
