### ISSUE TITLE
REST: Případy advokáta

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#65]
URL (návrh): `/advocate/:id/cases?year=number&court=string&result=string`
Parametry filtrují rok, soud a výsledek, když některý chybí, bere se pro všechny.
Vrací stránkovaný seznam obsahující následující informace:
* id (pro URL),
* spisová značka,
* datum rozhodnutí,
* výsledek,
* soud

**Comment by repli2dev** [comment]
URL: `/api/advocate-cases/<advocate>` jako volitelné query argumenty jsou `court`, `year` a `result.

V datech pro jednotlivý případ se nevrací datum rozhodnutí, poněvadž ho nemáme jednoduše a spolehlivě dostupný.

**Comment by tomvej** [comment]
Pokud není specifikovaný result nebo year, hází to 500. To asi není správné chování, že?

**Comment by repli2dev** [comment]
Musíš přistupovat bez závěrečného `/`, tedy například `https://devel.cestiadvokati.cz/api/advocate-cases/2`, pak to 500 neháže. (Tohle se týká všech API)
