### ISSUE TITLE
REST: Detail případu

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#66]
URL (návrh): `/case/:id`
Vrátí následující informace:
* id advokáta (pro url)
* jméno advokáta (jméno, příjmení, titul),
* spisovou značku,
* seznam dokumentů:
    * číslo jednací,
    * datum rozhodnutí,
    * URL dokumentu na stránce soudu

**Comment by tomvej** [comment]
Technicky:
1) Asi by tam nemuselo být jméno advokáta, mohlo by se dotáhnout RESTovkou pro detail.
2) Seznam dokumentů může být jiná RESTovka -- záleží, co je jednodušší -- mi přišlo, že tam těch dokumentů nebude mnoho.

**Comment by repli2dev** [comment]
Vyřešeno... URL `/api/case/<id>`

Struktura:
```json
    {
        "id_case": 12,
        "id_court": 2,
        "registry_mark": "42 CDO 4000/2016",
        "tagging_advocate": {
            "id_advocate": 123,
            "fullname": "JUDr. Ing. Petr Omáčka, PhD."
        },
        "tagging_result": "negative",
        "documents": [
            {
                "id_document": 543,
                "mark": "ECLI:CZ:NS:2016:42.CDO.4000.2016.1",
                "decision_date": "2012-04-23T18:25:43.511Z",
                "public_link": "http://example.com/doc/12AS13LAA0"
            }
        ]
    }
```
