### ISSUE TITLE
REST: autocomplete

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#67]
URL (návrh): `/advocate/autocomplete?query=string`
Parametry -- query je vyhledávací string, buď název nebo IČ.
Vrátí seznam:
* id (pro URL),
* jméno (jméno, příjmení, titul),
* jméno pod kterým byl nalezen

**Comment by tomvej** [comment]
Seznam by mohl být stránkovaný a nebo prostě vrátí prvních deset.

**Comment by repli2dev** [comment]
Vracím prvních 30 (to tak maximálně dává smysl, dle mě, stránkované napovídání nikoliv)...

Schéma jsem upravil, protože je podle mě potřeba říct v čem se to protnulo (zda IČ, nebo jméno).

```json
[{
    "id_advocate": 885,
    "fullname": "Mgr. Ondřej Dlouhý",
    "matched": {
        "type": "fullname",
        "value": "Mgr. Ondřej Dlouhý"
    }
}]
```

**Comment by tomvej** [comment]
Jo, takhle to dává smysl.
