### ISSUE TITLE
Server Error v sekci Pravidelné úlohy

### ISSUE THREAD

**Issue by xorelvistor** [datoszs/czech-lawyers#70]
na develu v sekci 'Pravidelné úlohy' se zobrazuje hláška Server Error - 500 a v seznamu úloh je pouze NSCrawler

**Comment by repli2dev** [comment]
Zvýšil jsem `memory_limit` na 256 MB, crashovalo to na tom... protože výstup `App\Commands\NSAdvocateTagger` má cca 120 MB, což bohužel celkem odpovídá úrovni logování...

Máme víc možností: do DB rvát jen částečný log (otázkou je zde, co by to mělo být), ukládat to na FS,...?

**Comment by repli2dev** [comment]
Bude řešeno v rácmi #79.
