### ISSUE TITLE
Počítání statistik pouze z procesed

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#74]
Z čeho všecho se mají počítat statistiky? Momentálně se počítají ze všech posledních tagování (takže i failed, fuzzy)... to asi není chtěné, že?

Taktéž u advokáta, případu... nechceme ukazovat tagování, pokud je fuzzy, že?

**Comment by tpapouskova** [comment]
Přesně tak, statistiky chceme počítat jen z processed, ostatní vůbec
nepočítáme (ani do čitatele ani do jmenovatele).

2017-03-02 11:42 GMT+01:00 Jan Drábek <notifications@github.com>:
