### ISSUE TITLE
Design: Výsledky hledání

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#75]
Napsat jednoduchý mockup stránky s výsledky hledání

**Comment by tomvej** [comment]
@tpapouskova Prozatimní výsledek: https://drive.google.com/file/d/0By2NMS-JnGIxQjVRcVpuQTc4aHc/view?usp=sharing

* Panel nahoře s vyhledávacím polem je tam kvůli hledání (a jeslti budeme v budoucnu třeba filtrovat).
* Se spodní částí panelu právníka jako místo pro doplňkové informace (sídlo, IČO) jsem celkem spokojený.
* Zarovnání horního částí panelu je trochu tristní. Úplně nevím, kam narvat ten label se stavem (ve spodní části to vypadá divně), navíc by se tam hodilo tlačítko "Více" nebo "Detail" aby uživatel nebyl zmatený.
* Nepodařilo semi tam napasovat vysvětlivky k číslům. Možná tooltip?
* Tituly by mohly být měnším písmem než jméno.

**Comment by tomvej** [comment]
Ještě mě napadá, záleží jak moc je status právníka významná informace. Pokud není významný, může se zbavit toho rámečku a dát dolů do lišty v normálním (barevném) textu.

**Comment by tpapouskova** [comment]
Díky.

Postřehy:
- tituly nezmenšovat, právníci je mají rádi
- status bych možná opravdu dala dolů do doplňovacích informací dolů, možná
ani ne barevně, je to prostě jen jedna z dalších informací
- misto status labelu bych tam opravdu dala detail
- labely k číslům bych řešila, není-li to nereálné, zobrazením vysvětlivky
při přejetí
- a ještě jedna generální - zrušme hodnotící barvy červená / zelená, výběr
jiných dvou kontrastních barev nechám na Tobě (modrá / fialová ?)

T.


Dne 4. března 2017 14:53 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tpapouskova** [comment]
PS: Jen pro jistotu (netuším, jestli jsme se správně pochopili) u Šárky a
Dany Novákové v Tvém příkladu by mělo být červené (později jinak barevné
číslo největší, u Iva Nováka by měla být všechna čísla stejně velká.
Zkrátka aby rozdíl ve velikosti proporčně odpovídal rozdílu v hodnotě.

Dne 5. března 2017 23:50 Tereza Papoušková <tereza.papouskova@gmail.com>
napsal(a):

**Comment by tomvej** [comment]
Jo, počítám s tím, že ším vyšší číslo, tím bude ... větší. Já jsem to tam plácal dost narychlo než to budu dělat načisto, takže to je artefakt.

Barvy zkusím vymyslet, čísla by mohly mít ještě rámeček (že by to zároveň vypadalo trochu jako sloupcový graf). Ad hodnotící barvy -- já myslel, že právnky hodnotíme. ;) Ale barvy se dají změnit rychle.

Ad tituly: titul je důležitá informace (a právníci strašně marniví), ale takhle poutá moc pozornosti vůči jménu. Dovedu si představit něco jako https://jsfiddle.net/v21obrrg/

**Comment by tpapouskova** [comment]
Ad tituly - já nevím, mně se to zdá nepřehledné právě tehdy, když je něco
malé a něco velké... ale jako tohle není něco, na čem bych lpěla, takže je
to na Tobě.

Dne 6. března 2017 12:46 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#75 Výsledky hledání](https://trello.com/c/dCVqNXkA/18-75-vysledky-hledani)

**Comment by tomvej** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#75 Výsledky hledání](https://trello.com/c/dCVqNXkA/18-75-vysledky-hledani)

**Comment by tpapouskova** [comment]
Odkaz vyžaduje přihlášení...

2017-03-06 19:38 GMT+01:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by tomvej** [comment]
Jo, to nebylo nic důležitého, trochu jsem experimentoval s integracemi.

**Comment by tomvej** [comment]
Je pro uživatele důležité statistiky jednoho právníka nebo statistiky mezi právníky? Zjednodušeně: Má být 12 u jednoho právníka stejně velké jako 12 u jiného, i když u prvního je to největší číslo a u druhého nejmenší?

**Comment by tpapouskova** [comment]
Hmmm, dobrá otázka. Mám zvrhlý nápad - co to nechat v nominální hodnotě,
ale velikost zobrazovat podle procentuálního podílu nominální hodnoty v
celkovém počtu zpracovávaných rozhodnutí (a velikosti stejných procent
nechávat napříč právníky stejné)? Takto by mi to vlastně dávalo smysl na té
přehledové, abys na jeden pohled viděl i to, kdo toho podal hodně, i to,
kdo je jak moc velká lama.

Jestli je to ale moc mimo, nechme to u procent a stejné % udělejme napříč
právníky stejně velké.

Dne 8. března 2017 21:44 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Hm, nejsem si jistý, jestli jsem Ti rozuměl. Jako že velikost bude místo procentem případů ze součtu případů právníka dána procentem případů ze součtu případů všech právníků na stránce? Hm, technicky to jde, uvidíme, jak to bude vypadat, asi rozhodneme podle toho.

**Comment by tomvej** [comment]
Ještě jsem si hrál se zobrazením čísílek:
* 1.0 https://drive.google.com/open?id=0By2NMS-JnGIxUWZoNGZCX1AwMm8
* 1.1 https://drive.google.com/open?id=0By2NMS-JnGIxaFhSNEwya1NiVWM
1.0 bere velikost fontu podle procenta, ještě jsem tam přidal rámeček, aby to bylo zřetelnější. Ale pak jsem zjistil, že změna velikosti písma vypadá divně, takže navrhuju verzi 1.1, kde je velikost fontu stejná a podíl se zobrazuje rámečkem.

**Comment by tpapouskova** [comment]
Takhle. Puvodne jsem do toho navrhu psala
"Vedle tohoto vpravo tři velké číslovky (jejich vzájemná velikost ideálně
proporční navzájem), zelená pro *podíl meritorních* (positive in
all-minus-unknown), červená pro *podíl nemeritorních* (negative in
all-minus-unknown) a šedá pro* podíl zastaveno* (neutral in
all-minus-unknown)."

A ten nápad byl, že by to (to číslo) nebyl podíl, ale prostě jen nominální
hodnota (tedy ne positive in all-minus-unknown, ale proste jen positive). A
že by jen jeho velikost odpovídala podílu v celku advokáta (!ne všech
advokátů na stránce).

Ad velikost a rámeček - já osobně bych barevný rámeček zcela zrušila a
nechala tam jen různě velká čísla.

T.

Dne 8. března 2017 22:45 Tomáš Vejpustek <notifications@github.com>
napsal(a):
