### ISSUE TITLE
Autocomplete search komponenta

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#76]
Bude se používat na hlavní obrazovce a vyhledávání.
Pravděpodobně udělat úplně custom z inputu a listu nebo něčeho podobného.

**Comment by repli2dev** [comment]
Nějaký důvod nepoužít třeba selectize.js?

**Comment by tomvej** [comment]
Konkrétně pto selectize.js mám velmi dobrý důvod to nepoužít, a to jQuery. Ale jasně, rozumím. Jediný důvod byl si vyzkoušet, jak se to píše. Ještě uvažuju, jak těžké bude to udělat custom a nebo jestli nepoužít něco jako:
https://github.com/reactjs/react-autocomplete
https://github.com/moroshko/react-autosuggest

**Comment by repli2dev** [comment]
Aha, ok :-/ (ta knihovna je dobrá)

**Comment by repli2dev** [comment]
@tomvej autor selectize.js doporučuje pro React https://github.com/JedWatson/react-select

**Comment by repli2dev** [comment]
Letmo jsem to otestoval:
- příliš mnoho výsledků (klidně to velmi protáhne stránku)
- chyba po příchodu na advokáta (viz níže) (http://localhost:8080/advocate/13667)
- chybné zobrazení když přejdu zpět ze stránky advokáta, případů... rozbalovací menu s nápovědou je rozbaleno, to je neočekávané.
- funguje na tab, šipku dolů, funguje enter uvnitř :-)
- zdá se, že to funguje celkem dobře i se zhoršeným připojením (chrome tools)

Máš něco konkrétního co potřebuješ otestovat?

```
uncaught at loadSingleResult TypeError: Reduce of empty array with no initial value
at Array.reduce (native)
    at maxCasesReducer (eval at <anonymous> (http://localhost:8080/main.js:9636:1), <anonymous>:101:16)
    at eval (eval at <anonymous> (http://localhost:8080/main.js:20481:1), <anonymous>:39:31)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:8080/main.js:20481:1), <anonymous>:36:19)
    at Map.withMutations (eval at <anonymous> (http://localhost:8080/main.js:998:1), <anonymous>:1355:7)
    at eval (eval at <anonymous> (http://localhost:8080/main.js:20481:1), <anonymous>:35:23)
    at exports.default (eval at <anonymous> (http://localhost:8080/main.js:9636:1), <anonymous>:195:16)
    at eval (eval at <anonymous> (http://localhost:8080/main.js:20481:1), <anonymous>:39:31)
    at Array.forEach (native)
```

**Comment by tomvej** [comment]
Hlavně mě zajímá, jestli se to chová tak, jak by uživatel očekával. Tu chybu u advokáta jsem vyřešil v 0326eb27eec85ae8a6aff1a02513ec54b6eedab8, to rozbalené menu je fakt divné, ale snad by to nemusel být tak velký problém. Počet výsledků můžu omezit, to je pravda.

**Comment by tomvej** [comment]
Hm, tak rozbalené menu nedokážu zreplikovat.

**Comment by repli2dev** [comment]
Dle očekávání (až na to rozbalené menu) chová.

1. Jdu na stránku advokáta (http://localhost:8080/advocate/121)
2. Kliknu zpět v prohlížeči
3. Kliknu do pole s autocomplete (objeví se box)
4. kliknu dopředu v prohlížeči
5. Kliknu zpět v prohlížeči
6. Vidím otevřené okno

Alternativní postup: lze přejít i na Případy.

**Comment by tomvej** [comment]
Okay, asi nezbyde než udělat komponentu lifecycle aware a zavolat hide, když se zruší.

**Comment by tomvej** [comment]
Tak, to bych měl opraveno, ještě jedna věc mi tam nesedí:
Když vyberu advokáta v seznamu, a pak dám zpět, mám prázdný input, ačkoliv už jsem tam měl něco málo napsaného. Je to očekávatelné chování nebo ne?

**Comment by repli2dev** [comment]
U standardní stránky mi nevadí pokud to zmizí při příchodu na zpět, u frontendových aplikací čekám, že je tam to co jsem vybral.
