### ISSUE TITLE
Implementace crawleru pro stahování dat z Nejvyššího soudu

### ISSUE THREAD

**Issue by papousek** [datoszs/czech-lawyers#8]
- [ ] script, který je schopen v zadaném časovém intervalu stáhnout všechna dostupná rozhodnutí
- [ ] zdrojové kódy jsou dostupné v příslušném repozitáři

**Comment by papousek** [comment]
@repli2dev Je toto už hotové?

**Comment by repli2dev** [comment]
Ano, crawler samotny je v repozitari cz-supreme-court-crawler.

V aplikaci je pak wrapper: app:ns-crawler
