### ISSUE TITLE
Legenda pro statistiky

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#80]
Statistiky právníků jsou tři různě barevná čísla -- potřebujeme nějakou legendu. Otázkou je, jak přesně ji udělat -- jako tooltip (pak by se tam musel dát nějaký otazníček, aby bylo jasné, že tam tooltip je)? Nebo ji nechat plavat na stránce by default s tím, že půjde zavřít?

**Comment by repli2dev** [comment]
Přesvědčili jsme @tpapouskova, že jiné barvy než zelená - červená by byly matoucí.

Afterthough: za mě by se mi asi líbilo, kdyby to nebyla echt zelená a červená, ale zelená a oranžovo-červená (dává to signál, že tam není něco v pořádku, ale zároveň to nemá červenou fatalitu).
