### ISSUE TITLE
Detail advokáta

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#82]
Zobrazí detail advokáta podle id, včetně statistik. Nezobrazí timelinu ani nic jiného.

**Comment by tomvej** [comment]
@tpapouskova Zkoušel jsem nějaký rychlý nástřel:
https://drive.google.com/file/d/0By2NMS-JnGIxeFlwTXJNMEZtd3c/view?usp=sharing
Není to začistěné, není tam velikost písma a chybí tam popisky u statistik.

* Idea byla, když si všichni tak stěžují na ústavní soud, že by se zobrazovaly statistiky i zvlášť a pokud by člověk podržel myš na jedné ze statistik dole, zobrazila by se míto té hlavní.
* Je OK to dělení na panely na levé straně? Nebo mám zkusit něco jiného?

**Comment by tpapouskova** [comment]
Supr, to rozdělení na 3 soudy se mi rozhodně líbí!

Co se týče panelů, jsem spíš proti. Přidržela bych se původní myšlenky (tj.
pouze v prostém textu pod sebe řazené dostupné informace. Panely na mě
působí, jako kdybych na ně měla nějak klikat či co...

Dne 17. března 2017 10:23 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tomvej** [comment]
Ok, v tom máš pravdu, na předchozí stránce máme klikatelné panely. Zkusím jiný návrh.

**Comment by tomvej** [comment]
Tak ty malé legendy se mi úplně rovnou nepodařily, protože jsem zjistil, že na ně nemám data. Takže na to založím nový task, který bude v backlogu.
