### ISSUE TITLE
Statistiky pro jednotlivé soudy

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#83]
Bylo by pěkné, aby se statistiky zobrazovaly nejen podle let, ale podle soudů, viz https://drive.google.com/file/d/0By2NMS-JnGIxeFlwTXJNMEZtd3c/view?usp=sharing vpravo.

**Comment by tpapouskova** [comment]
+ možná by mohlo být dobré dát možnost zobrazit si detailnější statistiky (rozdělené na soudy) už v rámci dlaždic při vyhledávání (například po kliknutí na nějakou ikonku)

**Comment by tomvej** [comment]
Dlaždice by měly sloužit především jako cesta, k detailu, takže jejich scénáře jsou:
* potřebuju vybrat konkrétního advokáta z vyhledávaných,
* potřebuju úplně základní rychlou informaci,
* umožňuje zběžně porovnat vyhledávané právníky.

Za ideálních podmínek by se detail právníka měl načíst poměrně rychle a tlačítko zpět by mělo fungovat taky dobře. Dá se i urychlit přepínání mezi vyhledáváním a detailem:
* některá data se přenesou, nebudou se stahovat znova,
* na stránce vyhledávání se zachová scroll.

Nevím, jestli chceme z vyhledávání udělat takový overkill -- můžeme mít stránku na prohlížení statistiky, porovnávání právníků.

**Comment by tpapouskova** [comment]
Ok souhlasím, byl to jen nápad, a když nad tím tak přemýšlím, asi opravdu
hloupý. Statistiky dle jednotlivých soudů dejme tedy jen až na stránku
advokáta.

Dne 25. dubna 2017 9:18 Tomáš Vejpustek <notifications@github.com>
napsal(a):

**Comment by tpapouskova** [comment]
Nevím, v jaké je toto issue fázi, ale moc pléduji za jeho vyřešení při nejbližší možné příležitosti (opakovaně se mě na to lidé ptají...).

**Comment by tomvej** [comment]
@repli2dev Pokud se to má zobrazovat, měly by se posílat statistiky s back-endu s detailem advokáta.

**Comment by tpapouskova** [comment]
Hotovo, leč zatím s bugy, že?

Bug: u některých advokátů se u jednotlivých soudů nezobrazují čísla ( Petr Pyšný, Alexandr Klimeš, Tomáš Matoušek...)

**Comment by tomvej** [comment]
Vyžaduje vstup od Honzy, zatím je to naimplementováno jako hack, který tam nemůže zůstat. Čísla mizí dost náhodně (občas tam jsou, občas ne),
počkám jestli to nezmizí se změnou implementace, zatím se mi nedařilo spolehlivě replikovat.

______________________________________________________________

**Comment by repli2dev** [comment]
@tomvej máš to připraveno.

**Comment by repli2dev** [comment]
@tomvej Zapomínám, že to dělají i commit message...
