### ISSUE TITLE
Výsledky a případy advokáta

### ISSUE THREAD

**Issue by tomvej** [datoszs/czech-lawyers#84]

**Comment by tomvej** [comment]
Povětšinou to funguje. Mám nějaké problémy s restovkou pro případy, ale zjevně se nevyskytují na DEVELu, takže ok.

ID soudů jsou nejspíš špatně (nevím, který je který), napravím to až budu dělat detail případu.

**Comment by repli2dev** [comment]
Pro jistotu: čísla soudů jsou definovány v číselníku... reprezentuje ho třída `App\Enums\Court` a v databázi tabulka `court`.

**Comment by tomvej** [comment]
Jo, už jsem to opravil podle dokumentů k případům, ale teď to mám i ověřené.
