### ISSUE TITLE
Drobné úpravy UI

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#89]
Za mě pár návrhů:
- tlačítko s odkazem do ČAKu by mohlo mít ikonku "externí odkaz"
- popisky "meritorní"/"nemeritorní" by měli mít tooltip.
- barvy to chce buď standardní, nebo žádné.

**Comment by tpapouskova** [comment]
Geniální. Jako fakt, jsem nikdy ani nedoufala, že to bude vypadat takto
profesionálně!

Pár návrhů (co spadá do oněch 20 ještě plánovaných %, ignoruj):
- Osobně mě ruší ty dva klikatelné boxíky pod jménem advokáta (ve stránce
jeho náhledu). Tlačítko "Zpět" bych dala nad jméno (a možná přejmenovala na
"Zpět na výsledky vyhledávání" a možná zrušila úplně - viz poslední
komentář), tlačítko "Detail na stránkách..." bych dala vedle jména.
- I když advokát nemá vyplněné sídlo, přesto je tam odskok mezi Sídlem a
E-mailem, což je matoucí (viz např. Kateřina Šimáčková).
- Potřebovala bych nějak vizuálně oddělit část s informacemi o advokátu a
část, kde si můžu klikat a filtrovat záznamy. Možná jen mezerou.
- Bude fajn pak doladit, jak se zobrazují spisovky (nemělo by tam být
"afs", ale "Afs", ne "iv.ús", ale "IV. ÚS"). Toto platí i pro stránku
případu, kde se zase vše zobrazuje v kapitálkách.
- Původně byl návrh, aby byla klikatelná i čísla vpravo nahoře (ta hlavní).
Ale to asi opusťme, ať je ta stráka rozdělena logicky na informační (horní
polovina) a klikací (dolní polovina).
- Intuitivně bych čekala, že když kliknu na již označený sloupec (jeho
část), tento se odznačí (zruší se filtr). Podobné očekávání stran odznačení
filtru roku (a případně i typu případů v roce) mám i po kliknutí na filtr
soudu.
- Přišlo by mi dobré dlaždice s případy (spisovkami) jemně podbarvit v
barvě výsledku. Do dolní popisové lišty v rámci jednotlivých dlaždic bych
možná přidala i "Rozhodnuto dne ...", tj. datum konečného rozhodnutí.
- Na stránce případu bych přidala do informační části datum rozhodnutí (viz
předchozí).
- Na stránce případu je v dlaždici dokumentu dolní informační část (datum)
v angličtině.
- Když se ze stránky případu vrátím (kliknutím na jméno) zpět na stránku
advokáta a zde kliknu na "Zpět", čekala bych, že se dostanu na stránku s
výsledky vyhledávání advokátů (a nikoliv zpět v historii prohlížení, tj. na
stránku případu). Možná bych zvážila, zda po zadání dotazu a následném
přejití na stránku konkrétního advokáta nedat odkaz "Výsledky vyhledávání:
[zadaný dotaz]" doprostřed horní lišty, aby se na to šlo vrátit jak ze
stránky advokáta, tak ze stránky případu (a aby nějaké vracecí tlačítko
nenarušovalo informační tok).

2017-03-26 15:48 GMT+02:00 Jan Drábek <notifications@github.com>:

**Comment by tomvej** [comment]
* Zpět na vyhledávání bude řešit #86.
* Mezera při chybějící adrese se vyřešila #97.
* Přidaly se nadpisy, které dělí detail advokáta od případů #98.
* Formátování spisovky v #91.
* Zrušení filtru v #108.
* Na podbarvení detailu připravím prototyp v #109.
* Datum v angličtině vyřešeno v #96.

**Comment by tomvej** [comment]
> - Na stránce případu bych přidala do informační části datum rozhodnutí (viz předchozí).

@repli2dev Už jsem na to zakládal issue a nebo mi to uteklo?

**Comment by tomvej** [comment]
Datum rozhodnutí v případech advokáta: #114

**Comment by tomvej** [comment]
Všechny požadavky mají svoje issue, uzavírám.
