### ISSUE TITLE
ÚS: špatné roky

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#90]
Současná úprava, která dotazuje roky dle spisovek nepočítala s tím, že ÚS má jen suffix toho roku a v roce 2000, pak celé číslo 2000 (WTF?!)).

Můžu celkem jednoduše opravit kód, aby nepočítal s ničím před lomítkem, ale to náš problém moc neřeší, protože rok se používá též pro vyhledávání a pak při počítání statistik, kde se potenciálně slévá s roky ostatních.

Je potřeba si tedy říct, jak se k problému postavit.

**Comment by repli2dev** [comment]
Shodli jsme se na následujícím řešení:

- Do tabulky `case` doplníme sloupec `proposition_date` (datum podání) typu DATETIME, který ale bude moci být prázdný (protože ne vždy ho budeme schopni určit -- například crawler NS ho nedá).
- Upravíme importery dat od soudů, tak aby vytvářely případy s datem podání (@tpapouskova bude při příštím podání chtít rozšířit data o sloupec data podání (u NSS, a ÚS))
- Upravíme crawlery (ÚS, NSS) tak, aby měli
- Zavedeme servisní pohled na případy s správným čtyřmístným rokem (určeným z proposition_date a případně ze spisovky) -- ten pohled nebude brát v potaz položky se špatným rokem, který neumíme určit jinak (`98`) -- nad tím pak budou postaveny statistiky.

**Comment by xorelvistor** [comment]
@repli2dev 
U NSS není přístupné nic jako datum podání, pouze datum rozhodnutí a někdy i datum napadení. Stává se, že rok data rozhodnutí není shodný s rokem ve spisové značce. Napadlo mě využít informaci z URL adresy dokumentu rozhodnutí.
```
sp. zn. 6 Ads 238/2016
http://nssoud.cz/.../2016/0238_6Ads_1600041S_20170405154116.pdf
datum rozhodnutí je 05.04.2017
``` 
Ovšem je tu uveden jen rok, mám tedy ukládat nějaké univerzální datum, řekněme 1. ledna, když z toho budeme stejně potřebovat pro účel grafů jen rok?

**Comment by repli2dev** [comment]
@tpapouskova není náhodou datum napadení totéž jako datum podání?

@xorelvistor jako uvažoval jsem nad tím, že s tím datem podáním je to možná overkill, že prostě ke každému případu chceme přidat rok.

**Comment by tpapouskova** [comment]
Ano, datum napadení je v podstatě totéž co datum podání (plus minus pár
dní). Pokud jsem to ale správně pochopila, Radim tvrdí, že datum napadení
NSS neuvádí vždy...

Dne 6. dubna 2017 21:11 Jan Drábek <notifications@github.com> napsal(a):

**Comment by xorelvistor** [comment]
@tpapouskova 
Problém je, že datum rozhodnutí i datum podání je zapsáno v jednom sloupci, ale nenašel jsem případ (namátkové hledání), kdy by tam byla zobrazena obě data, takže vlastně nevím, které to datum to je. Sice formulář obsahuje radio button pro výběr typu data (rozhodnutí|napadení), ale zobrazované datum je stále stejné (opět namátkové hledání). Další data jsou pak chronologicky uváděna v "Informacích o řízení", což je ale stránka, která není v současném stavu zahrnuta do zpracování.
Není totiž možné vyhledávat rozhodnutí na základě ostatních datumů uvedených na této informační stránce případu. A jelikož vyhledávání probíhá pomocí volby "přírůstky", netuším, podle kterého typu data jsou nám výsledky servírovány.
Snad jsem to napsal srozumitelně...

**Comment by repli2dev** [comment]
@xorelvistor @tpapouskova Zase jsem se do toho zamotal...

1. Nejspolehlivější zdroj roku je spisová značka.
2. ECLI je *nepoužitelné*, protože dle formátu (https://cs.wikipedia.org/wiki/Identifikátor_evropské_judikatury) je rok na začátku *rokem rozhodnutí*... samotný rok podání se v ECLI nacházet nemusí, protože identifikátor v rámci soudu je naprosto volný (dokud je unikátní) a tedy pro ÚS je tam jen kopie spisovky (tedy dvojpísmený rok).
3. U importu dat od soudů nemám, kromě spisovky jak jinak určit datum, potenciálně tam může být, ale možná taky ne.

Hodně nás štvou ty dva procesy získávání dat, které musí být dohromady dostatečně konzistentní... a to momentálně spíše nejsou. Ideální by bylo pro oba procesy mít "datum podání" a "datum rozhodnutí", to je ale problém u NS a jak jsem pochopil i u NSS.

Takže bych řekl, že nám zbývá jediné... Určovat to výhradně ze spisovky:

- 4 znaky => ok
- 2 znaky && < 92 => +2000
- 2 znaky && = 92 => +1901
- 2 znaky && > 92 => +1900
- chyba jinak

Je to takhle vyhovující? Může se stát, že budeme chtít pracovat i se staršími dokumenty? Existují vůbec takové? (@tpapouskova).

(Jinak při opravě jsem přišel na to, že existuje spisovka `Cdo 3357/2007`, zřejmě jde o chybou `29 Cdo 3357/2007`, ale v NS http://nsoud.cz/Judikatura/judikatura_ns.nsf/WebPrint/1F21F9AA1D6082E7C1257F3E00409AAF?openDocument to mají špatně... a pak že v roce 1999 měl i NS nějaké spisovky dvojčíselné.)

**Comment by repli2dev** [comment]
| Soud        | Import dat od soudu           | Import skrze dokumenty  |
| ------------- |:-------------:| -----:|
| NS      | Spisovka (ne vždy) | Spisovka (ne vždy) |
| NSS      | Spisovka      |   Spisovka |
| ÚS | Explicitní (Sloupec `PropDate`)      |    Explicitní z metadat $1 |

**Comment by repli2dev** [comment]
@xorelvistor ad NSS, pod ikonkou i se dostanu na stránku s přehledem dat: http://www.nssoud.cz/mainc.aspx?cls=InfoSoud&kau_id=184846 nemohlo by tohle být použitelné?

**Comment by tpapouskova** [comment]
Souhlasím s Honzovým řešením - určovat ty roky ze spisovky je rozhodně
nejspolehlivější a asi i nejjednodušší. starší dokumenty než 1992 rozhodně
nikdy mít nebudeme.

Jen bych myslela, že by to mělo být spíš takto:

   - 4 znaky   => ok
   - 2 znaky && < 92   => +2000
   - 2 znaky && = nebo > 92   => +1900
   - chyba jinak


Jinak pro přehlednost připomínám, že jsme se dohodli do příští žádosti o
informaci vložit požadavek na informace "spisová značka - datum podání -
datum rozhodnutí - způsob vyřízení (typ rozhodnutí) - jméno advokáta -
identifikátor advokáta (ideálně EČ, případně IČ)" (+ prozkoumám možnost
požadovat i jméno soudce, jemuž věc napadla, ale to spíše pro budoucí web
ceskesoudy.cz :).

Dne 20. dubna 2017 20:42 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Implementováno a nasazeno.

Díky za poznámku k tomu co chceme získávat, za mě to stále platí.

**Comment by tomvej** [comment]
@repli2dev Zkoušel jsi tu migraci nad devel databází? Já jsem dneska dělal restore a hlásí mi to
```
[Nextras\Dbal\NotNullConstraintViolationException]  
  ERROR:  column "year" contains null values 
```

**Comment by repli2dev** [comment]
Zkoušel, ale stáhl jsem si aktuální produkční ve které jsem upravoval jednu spisovku (která měla prázdný řetězec).

**Comment by tomvej** [comment]
Ah, jedna blbá spisovka. Ok, udělal jsem restore a už to jede.
