### ISSUE TITLE
Formátování spisovky

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#91]
Máme kanonizované spisovky v lowercase, ale to je nevhodný zobrazovací formát -- popsat typy spisovek a jak se mají správně zobrazit.

@tpapouskova definuje a přehodí na @xorelvistor nebo @repli2dev

**Comment by tpapouskova** [comment]
Trocha teorie - spisovka se, z našeho pohledu, skládá ze 3 částí: označení soudního oddělení, rejstříkové značky a čísla (tedy číslo označující pořadí nápadu + lomítka + označení roku). Tyto tři části se oddělují mezerou. Pro jednotlivé soudy pak lze první dvě části (třetí netřeba řešit, vždy bude v kýženém formátu) definovat následovně.

Ústavní soud
- označení soudního oddělení: jde-li o číslo, pak velkým římským (I., II., III., IV.), jde-li o zkratku, pak první písmeno je velké (Pl.)
- rejstříková značka: velkým (ÚS)

Nejvyšší soud
- označení soudního oddělení: arabská číslice
- rejstříková značka: zpravidla první je velké (Tdo, Cdo, Cdon, Odo, Odon), neplatí ale pro dva rejstříky (ICdo, NSČR), u nichž ale možná ani nemáme moc rozhodnutí...

Nejvyšší správní soud
- označení soudního oddělení: arabská číslice
- rejstříková značka: první je velké (As, Ads, Afs, Ars, Azs)

**Comment by repli2dev** [comment]
Provedeno.
