### ISSUE TITLE
Revize a naplnění textů pro web

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#92]
Revidovat texty pro nový frontend, dodat Tomovi.

**Comment by tpapouskova** [comment]
Revidováno. Texty na Drivu ("Web - texty"). Kdyby bylo cokoliv třeba "dotextovat", dej vědět.

**Comment by tomvej** [comment]
Pravděpodobně použiju něco podobného: https://github.com/rexxars/react-markdown
Na in-site linky by mohlo fungovat: https://github.com/rexxars/react-markdown/issues/29
Uvidíme, jak to nacpat do reduxu.

**Comment by tomvej** [comment]
Tohle by se mohlo použít pro obsah: https://github.com/fisshy/react-scroll

**Comment by tomvej** [comment]
Tak jo, většina textů doplněna, alespoň tam, kde to dává smysl. Chybí popisky formulářů pro rozporování a kontaktní e-mail.

Delší texty se načítají z markdownu, což trochu omezuje formátování -- ale zjednoduší přepisování.

**Comment by tpapouskova** [comment]
Šlo by to nasadit, prosím, abych se mohla pokochat?

2017-04-04 20:52 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by tomvej** [comment]
Nasazeno. Ještě chybí formuláře pro rozporování a připomínky (včetně
textů), ale budeme na tom pracovat.

**Comment by tpapouskova** [comment]
Supr! Ještě by to pak chtělo naplnit a nasadit tu hlášku pro advokáty
stejnojmenovce a až bude vyhledávání případů, tak i ty 2 texty, co se k
němu vztahují (vše v dokumentu úplně dole).

+ pak mám 2 minuskulní připomínky - jestli by v sekci "O projektu" nešly
zmenšit názvy soudů (připadá mi, že dost vyčuhují a vypadají jako
samostatné nadpisy) a jestli by pak, až uděláte boční vyskakovací formulář
"Napište nám", mohl příslušný text zmizet z části "Kontakty".



2017-04-06 20:36 GMT+02:00 Tomáš Vejpustek <notifications@github.com>:

**Comment by tomvej** [comment]
Na stejnojmenovce jsem založil issue, s tím jsme trochu nepočítali. Až
bude vyhledávání případů, texty přidám (teď doufám, že nezapomenu).

Názvy soudů jsou nadpisy, protože mě nenapadlo, že něco, co je tučným
písmem na zvláštním řádku není nadpis. Zmenším.

Ad vyskakující formulář: Dialogy jsou trochu UI anti-pattern -- navíc,
pokud tu lištu zavřu, protože mi překáží, už se na tu stránku nedostanu
(a nenapadne mě, že stačí refresh). Proto bych preferoval, aby
kontaktní formulář byl i na stránce, kam se dá dostat odjinud,
popřípadě na obou místech, dialog a stránka. Zatím ho dám na kontakt,
pak můžeme uvažovat o dialogu.

**Comment by tpapouskova** [comment]
Ok, supr.

S tím zdvojením kontaktního formuláře souhlasím (dialog i stránka
Kontakty). To mi přijde jako dobré řešení.

Dne 7. dubna 2017 10:18 Tomáš Vejpustek <notifications@github.com>
napsal(a):
