### ISSUE TITLE
Úpravy manuálního tagování

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#93]
- [ ] ~Vyhodit ty co nemají dokument (buď jsou otagovány soudem, nebo není z čeho tagovat)~
- [x] Zrušit filtr zpochybněné
- [x] Zavést filtr výsledek: **selhalo**, rozporováno
- [x] Zavést filtr advokát: žádný, **selhalo**, rozporováno 
- [x] Vyhledávání dle spisové značky
- [x] Stránkování i nahoře
- [x] Při doplňování jména advokáta při manuálním tagování přidá poslední adresu advokáta

**Comment by xorelvistor** [comment]
Byl jsem nějak zmaten a udělal jsem to doplnění adresy do autocomplete i v detailu případu...promiň. Měl jsem pocit, že jsme se bavili, že když jsem si to vymyslel, ať to dodělám :-)

**Comment by repli2dev** [comment]
@xorelvistor ano původně jsem to chtěl, ale pak jsem byl líný na to zakládat samostatné issue. Díky za provedení :-)

**Comment by xorelvistor** [comment]
@repli2dev  můžeš v šabloně detailu (stejně ji budeš upravovat) zrušit u ```iframe``` atribut ```sandbox```? Jeho zavedení sice vyřešilo problémy se zobrazením dokumentů u ÚS, ale nabouralo zobrazení PDF dokumentů u NSS. Budu tedy muset problém se zobrazováním vyřešit jinak.

**Comment by repli2dev** [comment]
@tpapouskova 

> Vyhodit ty co nemají dokument (buď jsou otagovány soudem, nebo není z čeho tagovat)

Když se nad tím zamyslím tak mi to nedává úplně smysl, protože ty se potřebuješ umět dostat k tomu co je rozporováno a nemá dokument, minimálně proto, aby si tomu člověku mohla napsat... sekundárně proto, aby si mohla ověřit, že jsme to třeba nikde nepokazili po cestě (předzpracování dokumentu, import, tagování z něj), či to někdo ručně nezměnil na něco špatného.

**Comment by tpapouskova** [comment]
Ok, to zní rozumně, moc díky za promyšlení! Potom by mi ale dávalo smysl,
aby se tam dalo rovnou prokliknout na danou tabulku od soudu (tj. dokument,
z něhož bylo tagováno). Šlo by to?

(Jen poznámka k poslední poznámce - dle stávajícího návrhu, když to někdo
ručně změní na něco špatného, rozporovat to již nepůjde.)

Dne 16. dubna 2017 18:52 Jan Drábek <notifications@github.com> napsal(a):

**Comment by repli2dev** [comment]
Opět jsem se v tom zamotal, vypsal jsem si tři hlavní use casy a nedává mi navržené řešení příliš mnoho smyslu:

1. Chci se podívat na tagování případu X (nehledě na jeho status, tedy například i úspěšné tagování, naše administrace je jediný způsob jak se na data dá uživatelsky dívat).
2. Chci vidět otagované selhané = tagování výsledku nebo tagování advokáta (či obojí) selhalo (zde není jasné co je to selhalo)
3. Chci vidět rozporované = tagování výsledku nebo tagování advokáta (či obojí) bylo rozporováno (= má rozporování, které nebylo vyřešeno).

Proto, aby šlo daných use casů dosáhnout nelze mít dva filtry, jak bylo navrženo.

Navíc jsem zmaten ze stavu "selhalo", není mi prostě jasné co to je... Možná to mate situace, že tagování advokátů je failed vždy, když to tagger projel a nic nenašel, ale u výsledků takové tagování ani nevznikne, takže i nepřítomnost záznamu je, že to selhalo -- co vlastně chceme?

**Comment by tpapouskova** [comment]
Ad 1, - tento use case neexistuje. Na taggování případu X, které bylo úspěšné, se můžu podívat přímo na webu. Navíc je prostředí pro manuální taggování tvořeno hlavně pro potenciální externí pomocníky, kteří by měli vidět jen to minimum, se kterým nutně musí pracovat. Já aj. se na můžeme podívat přímo do databáze přes adminer.

Ad "selhalo". Myslím tím status "failed". Máš pravdu, že mi nedošlo, že u case result tento status vlastně není používaný...

Co vlastně chceme - vlastně, polopatě řečeno, filtrovat obě taggování podle toho, kdy to pokazil systém, a kdy to systém sice formálně nepokazil, ale nesedí to s realitou. Navrhuji, abychom to dořešili zítra...

**Comment by repli2dev** [comment]
Provedeno, uvidíme nakolik to bude fungovat (potenciálně by se mohlo ukázat, že pomocí filtrů se nejde dostat ke všemu, protože jsme to nějak nedomysleli), ale snad to nenastane.
