### ISSUE TITLE
ÚS, NSS: Stahování a ukládání všech metadat

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#94]

**Comment by xorelvistor** [comment]
@tpapouskova
U NSS  jsem přidal stahování těchto metadat:
- Účastníci řízení
- Opravný prostředek / ústavní stížnost
- Prejudikatura
- rok uvedený ve spisovce viz #90

**Comment by xorelvistor** [comment]
přidáno stahování metadatat z ÚS
zbývá provést extrakci rozšířených metadat zpětně
@repli2dev  máme nějakou možnost aktualizace metadat s využitím existujících příkazů/commands?

**Comment by repli2dev** [comment]
@xorelvistor nevím o ničem takovém. Buď budeš muset napsat nový command a nebo upravit stávající (například flag, který při existenci záznamu s daným record_id nebude jen tupě přeskakovat, ale aktualizuje metadata).

**Comment by xorelvistor** [comment]
všechny soubory dohrány a rozšířená metadata aktualizována

**Comment by repli2dev** [comment]
👍
