### ISSUE TITLE
Fix detailů dokumentů ÚS v manuálním tagování

### ISSUE THREAD

**Issue by repli2dev** [datoszs/czech-lawyers#95]
Vyřeší problémy s detailem rozhodnutí ÚS nečitelný dokument (velikost iframe) a inline script.

**Comment by xorelvistor** [comment]
Řešeno úpravou html dokumentu v crawleru. Ještě bude potřeba zpracovat dokumenty zpětně a provést stejné úpravy pro korektní zobrazení.

**Comment by xorelvistor** [comment]
provedena úprava dokumentů již uložených
